<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Canonical results page for the prompt-injection classifier evaluation.">

<title>Results: tables, figures, and source artifacts – Prompt-injection classifier evaluation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6417478169390d5200ae675d66b5a4f4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Prompt-injection classifier evaluation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./RESULTS.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="./WRITEUP.html">
 <span class="dropdown-text">Cover narrative (hub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./READING_GUIDE.html">
 <span class="dropdown-text">Reading guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/data-decisions.html">
 <span class="dropdown-text">Data decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/model-rungs.html">
 <span class="dropdown-text">Model details</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/eval-design.html">
 <span class="dropdown-text">Evaluation design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/threshold-policy.html">
 <span class="dropdown-text">Threshold policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reference-scorer-audit.html">
 <span class="dropdown-text">Reference-scorer audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/methodology-guarantees.html">
 <span class="dropdown-text">Methodology guarantees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/limitations-and-future-work.html">
 <span class="dropdown-text">Limitations and future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reproducibility.html">
 <span class="dropdown-text">Reproducibility — three reproduction tiers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./decisions/README.html"> 
<span class="menu-text">Decisions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reference">    
        <li>
    <a class="dropdown-item" href="./docs/for-hiring-managers.html">
 <span class="dropdown-text">For hiring managers in a hurry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXECUTIVE_SUMMARY.html">
 <span class="dropdown-text">Executive summary: prompt-injection classifier evaluation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EVIDENCE.html">
 <span class="dropdown-text">Evidence — audit trail</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SPEC_SHEET.html">
 <span class="dropdown-text">Project specification (filled at end of Phase 0)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SUBMISSION_AUDIT.html">
 <span class="dropdown-text">Submission audit — claim status ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NEXT_STEPS.html">
 <span class="dropdown-text">Carryforward + future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions registry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/01_canonical_results.html">
 <span class="dropdown-text">01 — Canonical results</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/02_frozen_vs_lora.html">
 <span class="dropdown-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/03_calibration.html">
 <span class="dropdown-text">03 — Calibration battery</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/04_ood_slate.html">
 <span class="dropdown-text">04 — OOD slate gap visualization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/brandon-behring/prompt-injection-detection-prototype" target="_blank"> 
<span class="menu-text">Repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Entry</a></li><li class="breadcrumb-item"><a href="./RESULTS.html">Results: tables, figures, and source artifacts</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Entry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Landing page (results + meaning)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RESULTS.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Results: tables, figures, and source artifacts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EXECUTIVE_SUMMARY.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Executive summary: prompt-injection classifier evaluation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cover narrative (hub)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./READING_GUIDE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading guide</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Detailed spokes (8 topics)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/data-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/model-rungs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/eval-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/threshold-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threshold policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reference-scorer-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/limitations-and-future-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Limitations and future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility — three reproduction tiers</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/01_canonical_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 — Canonical results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/02_frozen_vs_lora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/03_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 — Calibration battery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/04_ood_slate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 — OOD slate gap visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence + audit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EVIDENCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evidence — audit trail</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SPEC_SHEET.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project specification (filled at end of Phase 0)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SUBMISSION_AUDIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission audit — claim status ledger</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./NEXT_STEPS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carryforward + future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions registry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions (ADRs)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architecture Decision Records (ADRs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/upstream_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Upstream issues filed during this iteration</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-001-submission-deadline-and-scope-ambition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission deadline 2026-05-18 morning with infra-leveraged Long-scope attempt and fallback ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-002-deliverable-format-pdf-and-repo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — focused PDF plus public GitHub repo as evidence locker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-003-repo-visibility-public.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repository visibility — public from start (kit default ratified)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-004-reviewer-profile-and-hub-and-spoke-writeup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer profile A1+A2 with hub-and-spoke writeup structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-005-methodology-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-level methodology principles — methodology over metrics, honest evaluation preferred, structured limitations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-006-headline-metrics-and-statistical-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Headline metrics, operating-point pinpoints, and statistical apparatus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-007-rung-architecture-and-reference-scorers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology rung architecture — trained backbones, LLM-judge reference rungs, Cohen’s kappa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-008-data-scope-public-only-hybrid-splits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data scope — public-only sources, hybrid splits, NotInject inclusion (brief-level lock)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-009-process-mandates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Process mandates — two-tier reproducibility, marker-based testing, compute disclosure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-010-scope-limits-with-extension-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scope limits with per-bound extension conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-011-methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees — eight banned approaches surfaced as project commitments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-012-soft-signals-and-artifact-engagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Soft-signals naming discipline and external artifact engagement set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-013-kit-ratify-bulk-strictness-intake-notebook-persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kit-ratify bulk — Phase 0 strictness, brief-intake protocol, notebook role and RunPod persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-014-threat-model-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threat-model bundle — attack-class scope, language, length cap, truncation policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-015-rung-architecture-refinement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung architecture refinement — ModernBERT-base only trained slate, supersedes ADR-007</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-016-data-design-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data design bundle — source slate, splits, HF pinning, dedup, ordering, ceilings, ref-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-017-trained-rung-slate-expansion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trained-rung-slate expansion — TF-IDF plus LR classical floor and frozen-probe dual role</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-018-reference-scorer-slate-and-contamination-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference scorer slate and contamination stratification — OpenAI plus Anthropic LLM-judges plus ProtectAI v1 and v2 plus per-axis matched-budget</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-019-lora-and-transformer-training-recipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA and transformer-rung training recipe — hyperparameters, epochs, precision, class weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-020-compute-infrastructure-and-cost-discipline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute infrastructure and cost discipline — runpod-deploy 0.7.7 primitives, GPU failover, adaptive batch sizing, dual-layer cost tracking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-021-eval-slate-aggregation-and-recall-fpr-pinpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eval slate aggregation — pooled headline plus per-slice spoke and recall@FPR pinpoint feasibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-022-statistical-inference-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference apparatus — bootstrap N + stability check, multi-comparison stance, multi-seed protocol, paired-test method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-023-calibration-battery-and-interventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery composition — raw plus temperature plus isotonic interventions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-024-cross-fold-ci-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-fold CI methodology — cv_clt_ci (Bayle 2020) headline plus block-bootstrap-on-folds spoke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-025-dual-policy-threshold-characterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dual-policy threshold characterization at symmetric 1% cost weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-026-module-layout-concern-grouped-subpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module layout — concern-grouped sub-packages under src/</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-027-smoke-vs-canonical-execution-context-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Smoke vs canonical separation — three Makefile targets stratified by execution context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-028-coverage-floor-70pct-with-upstream-issue-filing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test coverage floor — 70% flat with co-locked upstream-issue-filing discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-029-test-marker-strategy-four-marker-ratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test marker strategy — ratify 4-marker stratification (unit / smoke / integration / network)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-030-deliverable-format-quarto-html-site.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — repo-only with Quarto-rendered HTML site via GitHub Actions (supersedes ADR-002)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-031-reviewer-reading-paths-quarto-site-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer reading paths — index.qmd entry-point with Quarto sidebar nav (supersedes ADR-004)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-032-hf-hub-publication-headline-rungs-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HF Hub checkpoint publication — publish primary headline rungs only with model card discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-033-github-release-strategy-rehearsal-plus-submission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitHub release strategy — rehearsal tag plus SemVer submission tag plus post-submission patches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-034-reproducibility-tier-full-ladder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility tier — full ladder T0 (eval-from-hub) plus T1 (smoke) plus T3 (headline-cloud)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-035-secrets-management-three-store-split.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secrets management — three-store split aligned with execution context (.env + RunPod pod-secrets + GH Actions repo Secrets)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-036-library-version-pins-tag-pin-plus-freeze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library version pins — tag pin to latest stable plus freeze for submission window (eval-toolkit v0.31.0 + runpod-deploy v0.7.7 + research_toolkit v1.9.1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-037-python-version-pin-3-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python version pin — ratify requires-python &gt;=3.13 (matches existing .python-version + bc8ce4e commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-038-phase-tailoring-light-roadmap-edits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase tailoring — light ROADMAP edits to Phase 4 close + Phase 5 description (preserves 5-phase structure)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-039-acceptance-criteria-six-gate-integration-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-specific acceptance criteria — 6-gate integration checklist for v1.0.0 submission tag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-040-phase-0-audit-findings-and-assumption-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 0 final audit findings + 7-assumption backfill (A-010 through A-016)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-041-phase-1-data-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 (Data) implementation bundle — manifest schema, SHA pinning, validator placement, loader arch, holdout sourcing, contamination corpus, output materialization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-042-llm-prelabel-dedup-holdout-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-judge pre-label as Q5 holdout-labeling bootstrap with human override</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-043-post-split-cross-source-leakage-cleanup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-split cross-source leakage cleanup — drop train+val rows that exact-match or cosine-near-match test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-044-phase-2-training-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 training implementation bundle — seed slate reconciliation + manifest move + classical-floor location + YAML config schema + trainer split + per-rung orchestration + fixture preflight</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-045-phase-3-evaluation-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 evaluation implementation bundle — scoring-first contract + 6-commit cadence + tiered reference scorers + classical-scaffold + full-pairwise persistence with headline-only WRITEUP + pydantic schema validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-046-phase-4-analysis-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 analysis implementation bundle — 6-commit cadence + scaffold-with-classical + always-emit-both-CIs auto-flag + MDE-on-every-emitted-CI + LLM-rater audit included (user-overridden from defer) + library-first hybrid figures + Phase 5 prep deferred</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-047-phase-1-library-first-carryforward-refactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 library-first carryforward refactor — audit findings + remediation plan (splits + dedup + leakage_report + contamination_scan migration to eval-toolkit primitives; orphaned code removed in-commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-048-llm-rater-reference-scorer-audit-protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-rater reference-scorer audit protocol — disagreement-with-LoRA baseline + stratified (5 OOD slices × 3 contamination_states) sampling + fixed 2-axis rubric + inter-rater gpt-4o-plus-claude-sonnet + dry-run-then-single-approval cost UX</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-049-gpu-order-priority-refresh-a100-80g.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPU failover ladder priority refresh — A100-SXM4-80GB to position 1 + US-WA-1/US-CA-2 datacenter additions + EU-RO-1 drop (frozen-probe + LoRA canonical; full-FT deferred to post-rehearsal)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-050-rung-slate-narrowing-llm-judges-and-full-ft-ood-dropped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung slate narrowing — LLM judges dropped (cost) + full-FT OOD dropped (FUSE EIO crash); narrow supersession of ADR-018 reference slate + ADR-021 OOD comparison scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-051-v1.0.x-carryforward-of-t0-and-invariant-scaffolds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">v1.0.x carryforward of ADR-034 T0 score-match wiring + ADR-039 gate-3 invariant-scaffold unskip; narrow supersession with explicit v1.1.x landing condition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-052-full-ft-ood-drop-methodological-reframing-of-adr-050-r2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full-FT OOD inference drop — methodological reframing; narrow supersession of ADR-050 Revision 2 (FUSE-crash-only framing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-053-reading-guide-governance-and-newcomer-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading-guide governance + newcomer onboarding paths — two entry artifacts + 3 reading paths + Headline-finding-block + interpretation pedagogy + pointer convention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-054-results-page-as-third-entry-artifact-extending-adr-053.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RESULTS.md as third entry artifact — narrow supersession of ADR-053 dimension 1 (two-entry-artifacts); dimensions 2-5 unchanged</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-055-eval-toolkit-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">eval-toolkit installs from PyPI (not git+https) at v0.40.0+ — narrow supersession of ADR-036 “git URL is the only viable spec format”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-056-binary-calibrator-refactor-and-platt-beta-narrow-supersession-of-adr-023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery refactor to eval-toolkit <code>_binary</code> API + Platt + Beta calibrators landed — narrow supersession of ADR-023 “temperature + isotonic only” scope deferral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-057-manifest-schema-v3-backfill-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Per-prediction provenance manifests via scripts/backfill_provenance.py — schema, location, naming, idempotency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-058-eval-from-hub-non-dry-run-body-narrow-supersession-of-adr-051-block-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">scripts/eval_from_hub.py non-dry-run body wired — narrow supersession of ADR-051 Block A (T0 score-match carryforward); Block B (38 invariant scaffolds) remains carryforward</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-059-runpod-deploy-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">runpod-deploy installs from PyPI (not git+https) at v0.8.4+ — narrow supersession of ADR-036 “git URL is the only viable spec format” sub-claim for runpod-deploy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation methodology — chunk-and-average vs head-truncation × 5-slice OOD; infrastructure-only at v1.1.0; execution deferred to v1.1.1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-061-quarto-site-navigation-restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto site navigation restructure — landing-page rebuild + navbar consolidation + sidebar hub-spoke nesting (narrow supersession of ADR-053 navigation contract)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-062-quarto-writeup-clarity-and-canonical-figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto writeup clarity rewrite and canonical reviewer figure slate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation execution (v1.1.2 carryforward; narrow renaming-only supersession of ADR-060 “v1.1.1” body references) — null result, backbone-dominant interpretation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-064-writeup-hiring-manager-clarity-and-consistency-pass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup hiring-manager clarity polish + documentation-wide consistency conventions — additive layer on top of ADR-062</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup accuracy-audit methodology + Quarto callout-note convention + narrative invariants — additive layer on top of ADR-064</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-066-library-first-carryforward-refactor-v1-2-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library-first carryforward refactor v1.2.2 — consume 7 closed eval-toolkit primitives across 6 sites</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for factual-typo fixes in cross-reference slug filenames</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-069-immutability-narrow-relaxation-for-publisher-url-to-doi-canonicalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for academic publisher-URL → DOI canonicalization in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-070-quarto-render-only-markdown-corrections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for render-only Markdown corrections in immutable ADRs</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#results" id="toc-results" class="nav-link active" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#metric-primer" id="toc-metric-primer" class="nav-link" data-scroll-target="#metric-primer">Metric Primer</a></li>
  <li><a href="#direct-prompt-injection-performance" id="toc-direct-prompt-injection-performance" class="nav-link" data-scroll-target="#direct-prompt-injection-performance">Direct Prompt-Injection Performance</a></li>
  <li><a href="#cross-family-ood-table-auprc" id="toc-cross-family-ood-table-auprc" class="nav-link" data-scroll-target="#cross-family-ood-table-auprc">1. Cross-Family OOD Table: AUPRC</a></li>
  <li><a href="#b-ablation-does-a-longer-context-backbone-fix-the-ood-gap" id="toc-b-ablation-does-a-longer-context-backbone-fix-the-ood-gap" class="nav-link" data-scroll-target="#b-ablation-does-a-longer-context-backbone-fix-the-ood-gap">§1B Ablation: does a longer-context backbone fix the OOD gap?</a></li>
  <li><a href="#frozen-probe-vs-lora" id="toc-frozen-probe-vs-lora" class="nav-link" data-scroll-target="#frozen-probe-vs-lora">2. Frozen Probe vs LoRA</a></li>
  <li><a href="#per-slice-view" id="toc-per-slice-view" class="nav-link" data-scroll-target="#per-slice-view">3. Per-Slice View</a></li>
  <li><a href="#threshold-transfer" id="toc-threshold-transfer" class="nav-link" data-scroll-target="#threshold-transfer">4. Threshold Transfer</a></li>
  <li><a href="#calibration" id="toc-calibration" class="nav-link" data-scroll-target="#calibration">5. Calibration</a></li>
  <li><a href="#secondary-table-auroc" id="toc-secondary-table-auroc" class="nav-link" data-scroll-target="#secondary-table-auroc">6. Secondary Table: AUROC</a></li>
  <li><a href="#raw-artifacts" id="toc-raw-artifacts" class="nav-link" data-scroll-target="#raw-artifacts">7. Raw Artifacts</a></li>
  <li><a href="#cross-references" id="toc-cross-references" class="nav-link" data-scroll-target="#cross-references">Cross-References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Entry</a></li><li class="breadcrumb-item"><a href="./RESULTS.html">Results: tables, figures, and source artifacts</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Results: tables, figures, and source artifacts</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>

<div>
  <div class="description">
    Canonical results page for the prompt-injection classifier evaluation.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="results" class="level1">
<h1>Results</h1>
<p>This page is the evidence layer behind the landing page. It gives exact values, five canonical figures, and pointers to the raw artifacts that produced them.</p>
<p><strong>How to read this page:</strong></p>
<ol type="1">
<li>Scan the <strong>Metric Primer</strong> if AUPRC or confidence intervals are new.</li>
<li>Read <strong>Direct Prompt-Injection Performance</strong> and <strong>§1 Cross-Family OOD Table</strong> together. The direct task was learned; cross-family generalization failed.</li>
<li>Use <strong>§1B–§5</strong> for the follow-up findings: DeBERTa ablation, frozen-probe vs LoRA, per-slice behavior, threshold transfer, and calibration.</li>
<li>Use <strong>§6–§7</strong> for AUROC comparison and raw artifact pointers.</li>
</ol>
<section id="metric-primer" class="level2">
<h2 class="anchored" data-anchor-id="metric-primer">Metric Primer</h2>
<ul>
<li><strong>AUPRC</strong> is the primary metric. It measures whether positives are ranked ahead of negatives. On imbalanced data, a random ranking scores the positive rate. For the pooled out-of-distribution (OOD) slice, <code>pooled_ood</code>, that floor is <strong>412 / 1101 = 0.374</strong>.</li>
<li><strong>AUROC</strong> is secondary. Its random floor is always 0.5, but it can make imbalanced tasks look better than they are.</li>
<li><strong>Recall at FPR &lt;= 1%</strong> asks: with at most 1 false alarm allowed per 100 benign examples, how many attacks are caught?</li>
<li><strong>95% CI</strong> shows uncertainty. A narrow interval supports a sharper claim; an interval crossing an important baseline means the claim is weak.</li>
<li><strong>ECE and Brier</strong> are calibration errors. Lower is better.</li>
</ul>
</section>
<section id="direct-prompt-injection-performance" class="level2">
<h2 class="anchored" data-anchor-id="direct-prompt-injection-performance">Direct Prompt-Injection Performance</h2>
<p>The detectors did learn direct prompt-injection patterns. This matters because the OOD result is not a total capability failure: they learned the direct task, then failed to carry that skill cleanly across attack-family shift.</p>
<p><strong>Balanced validation view.</strong> Source: <code>evals/predictions_val/</code>, pooled across trained in-house detectors, folds, and seeds. This split contains direct-injection positives and benign negatives, so AUPRC, AUROC, and recall are all defined.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Detector</th>
<th style="text-align: right;">Direct+benign validation AUPRC</th>
<th style="text-align: right;">AUROC</th>
<th style="text-align: right;">Recall@0.5</th>
<th>Read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT LoRA</td>
<td style="text-align: right;"><strong>0.974</strong></td>
<td style="text-align: right;"><strong>0.993</strong></td>
<td style="text-align: right;"><strong>0.934</strong></td>
<td>strong direct-pattern detection</td>
</tr>
<tr class="even">
<td>TF-IDF + LR</td>
<td style="text-align: right;">0.971</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: right;">0.930</td>
<td>lexical direct baseline is also strong</td>
</tr>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;">0.653</td>
<td style="text-align: right;">0.907</td>
<td style="text-align: right;">0.849</td>
<td>weaker ranking, still discriminative</td>
</tr>
</tbody>
</table>
<p><strong>Held-out direct-source view.</strong> Source: <code>evals/predictions/*__epoch2.parquet</code>, pooled across folds and seeds. This LODO test holds out one direct-injection source at a time. It is all positive by design, so the table reports recall only.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Detector</th>
<th style="text-align: right;">LODO direct-source recall@0.5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;"><strong>0.641</strong></td>
</tr>
<tr class="even">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">0.625</td>
</tr>
<tr class="odd">
<td>ModernBERT full fine-tune</td>
<td style="text-align: right;">0.558</td>
</tr>
</tbody>
</table>
<p><strong>Takeaway:</strong> direct-prompt-injection detection was not the failure mode. The failure is transfer: success on direct examples did not produce robust OOD ranking or stable thresholds when the attack family changed. False positives, AUPRC, and AUROC are omitted from the LODO direct-source table because that test is all-positive.</p>
</section>
<section id="cross-family-ood-table-auprc" class="level2">
<h2 class="anchored" data-anchor-id="cross-family-ood-table-auprc">1. Cross-Family OOD Table: AUPRC</h2>
<p>Source: <code>evals/bootstrap/marginal_cells.parquet</code>, seed=1, BCa bootstrap with 10000 resamples. Single-class slices are omitted from this table because AUPRC requires both positives and negatives.</p>
<p><strong>Reading this table:</strong></p>
<ul>
<li>The headline column is <strong>Pooled OOD AUPRC</strong>, the rightmost column with both positives and negatives.</li>
<li>A random ranking on Pooled OOD scores about <strong>0.374</strong>. Any detector at or below that floor is not clearly better than guessing.</li>
<li>JBB and XSTest show whether a detector is strong on one OOD family but weak on another.</li>
<li>The main checks are magnitude against the random floor, 95% CI width, and cross-detector ordering on pooled OOD.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Detector &nbsp;Slice</th>
<th style="text-align: right;">JBB (100p/100n)</th>
<th style="text-align: right;">XSTest (200p/250n)</th>
<th style="text-align: right;">Pooled OOD (412p/689n)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;">0.552 [0.520, 0.580]</td>
<td style="text-align: right;">0.468 [0.448, 0.486]</td>
<td style="text-align: right;"><strong>0.364 [0.354, 0.375]</strong></td>
</tr>
<tr class="even">
<td>ProtectAI v1</td>
<td style="text-align: right;">0.519 [0.437, 0.597]</td>
<td style="text-align: right;">0.469 [0.415, 0.523]</td>
<td style="text-align: right;">0.361 [0.330, 0.391]</td>
</tr>
<tr class="odd">
<td>ProtectAI v2</td>
<td style="text-align: right;">0.556 [0.453, 0.648]</td>
<td style="text-align: right;">0.382 [0.333, 0.429]</td>
<td style="text-align: right;">0.314 [0.283, 0.345]</td>
</tr>
<tr class="even">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">0.535 [0.504, 0.563]</td>
<td style="text-align: right;">0.467 [0.447, 0.486]</td>
<td style="text-align: right;">0.293 [0.286, 0.301]</td>
</tr>
<tr class="odd">
<td>TF-IDF + LR</td>
<td style="text-align: right;">0.470 [0.443, 0.496]</td>
<td style="text-align: right;">0.395 [0.379, 0.410]</td>
<td style="text-align: right;">0.291 [0.283, 0.298]</td>
</tr>
<tr class="even">
<td>Random floor</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.444</td>
<td style="text-align: right;">0.374</td>
</tr>
</tbody>
</table>
<p><strong>Takeaway:</strong> this is where the direct-trained detectors break. The best pooled OOD AUPRC is the frozen probe at 0.364, but the random floor is 0.374. The honest reading is that none of these detectors clearly learned the cross-family OOD ranking problem.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="docs/plots/F1.svg" class="img-fluid figure-img"></p>
<figcaption>F1: Pooled OOD AUPRC vs random floor</figcaption>
</figure>
</div>
<p><strong>What F1 shows:</strong> exact pooled OOD AUPRC values with 95% CIs and the random floor.</p>
<p><strong>What F1 does not show:</strong> deployment readiness, per-slice behavior, or whether single-class slices were caught at a fixed threshold.</p>
</section>
<section id="b-ablation-does-a-longer-context-backbone-fix-the-ood-gap" class="level2">
<h2 class="anchored" data-anchor-id="b-ablation-does-a-longer-context-backbone-fix-the-ood-gap">§1B Ablation: does a longer-context backbone fix the OOD gap?</h2>
<p>The headline table at §1 shows ModernBERT’s frozen-probe (8192-token native attention window) leading the in-house detectors at pooled OOD AUPRC 0.364 — but still essentially at the random floor (0.374). A natural follow-up question: <em>would a different short-context backbone do better with the right truncation handling, or is the OOD gap really about the architecture itself?</em></p>
<p>The v1.1.2 medium ablation per <a href="./decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html">ADR-060</a> trains DeBERTa-v3-base (184M params; 512-token native attention) twice with 2 truncation strategies, fold 0 / seed 42 only:</p>
<ul>
<li><strong>chunk-and-average</strong>: tokenize the full text; emit 512-token windows with stride 256 (50% overlap); per-window forward pass; average per-window class-1 softmax probabilities → final score.</li>
<li><strong>head-truncation</strong>: tokenize the full text; take the first 512 tokens; standard single-window forward pass.</li>
</ul>
<p>If the ModernBERT advantage at §1 came from its long context window, chunk-and-average (which gives DeBERTa access to the full text) should beat head-truncation by a wide margin. If the advantage is architectural, the two strategies should look similar.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>DeBERTa-v3-base strategy</th>
<th style="text-align: right;">JBB (100p/100n) AUPRC</th>
<th style="text-align: right;">XSTest (200p/250n) AUPRC</th>
<th style="text-align: right;">Pooled OOD (412p/689n) AUPRC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chunk-and-average</td>
<td style="text-align: right;">0.486</td>
<td style="text-align: right;">0.397</td>
<td style="text-align: right;"><strong>0.291</strong></td>
</tr>
<tr class="even">
<td>head-truncation</td>
<td style="text-align: right;">0.489</td>
<td style="text-align: right;">0.391</td>
<td style="text-align: right;"><strong>0.290</strong></td>
</tr>
</tbody>
</table>
<p><strong>What §1B shows:</strong> the two truncation strategies produce essentially identical per-slice metrics across the 5-slice OOD slate. Long context (the chunk-and-average path) provides no measurable benefit over head-truncation on this slate.</p>
<p><strong>What §1B does not show:</strong> DeBERTa-v3-base does not beat ModernBERT’s frozen-probe (0.364 pooled OOD AUPRC) — both DeBERTa strategies score ~20% lower. The headline ladder ordering at §1 is preserved.</p>
<p><strong>Interpretation:</strong> by the ADR-060 confound-control reading, the ModernBERT advantage on the headline ladder is <strong>backbone-dominant</strong>, not context-window-dominant. A bigger context window alone does not close the OOD generalization gap on this slate — it is the architecture (and/or pre-training pretext) that matters. The DeBERTa-vs-ModernBERT residual gap that <em>remains</em> (~0.29 vs 0.36) has its own confounds (backbone size, pre-training data, tokenizer family) that this ablation does not separate; see <a href="./WRITEUP/limitations-and-future-work.html#92-architectures-evaluated-and-dropped">WRITEUP/limitations-and-future-work.md §9.2</a> for the residual-confound discussion. See <a href="./decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html">ADR-063</a> for the execution record + actual GPU spend ($1.34 of the $5-7 envelope).</p>
</section>
<section id="frozen-probe-vs-lora" class="level2">
<h2 class="anchored" data-anchor-id="frozen-probe-vs-lora">2. Frozen Probe vs LoRA</h2>
<p>The frozen probe uses the pretrained ModernBERT backbone without task-specific weight movement. LoRA fine-tunes a small adapter on the direct-injection training pool. If fine-tuning helped OOD, LoRA should beat the frozen probe. It does not.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Slice</th>
<th>Metric</th>
<th style="text-align: right;">LoRA - frozen probe</th>
<th style="text-align: right;">95% CI</th>
<th>Read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LoRA vs frozen probe</td>
<td>JBB</td>
<td>AUPRC</td>
<td style="text-align: right;">-0.016</td>
<td style="text-align: right;">[-0.024, -0.009]</td>
<td>LoRA worse</td>
</tr>
<tr class="even">
<td>LoRA vs frozen probe</td>
<td>XSTest</td>
<td>AUPRC</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">[-0.006, 0.004]</td>
<td>indistinguishable</td>
</tr>
<tr class="odd">
<td>LoRA vs frozen probe</td>
<td>Pooled OOD</td>
<td>AUPRC</td>
<td style="text-align: right;">-0.071</td>
<td style="text-align: right;">see marginal table</td>
<td>LoRA much worse</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="docs/plots/F2.svg" class="img-fluid figure-img"></p>
<figcaption>F2: Frozen probe vs LoRA paired deltas</figcaption>
</figure>
</div>
<p><strong>What F2 shows:</strong> paired-bootstrap AUPRC differences for the comparable both-class slices available in <code>evals/bootstrap/paired_cells.parquet</code>.</p>
<p><strong>What F2 does not show:</strong> a paired pooled OOD CI, because the persisted paired artifact does not include that pooled comparison; the pooled delta above is the difference between marginal point estimates.</p>
</section>
<section id="per-slice-view" class="level2">
<h2 class="anchored" data-anchor-id="per-slice-view">3. Per-Slice View</h2>
<p>The OOD slate is deliberately not one homogeneous test set:</p>
<ul>
<li><strong>JBB</strong>: jailbreak-style harmful elicitation, both classes.</li>
<li><strong>XSTest</strong>: jailbreak-as-question style, both classes.</li>
<li><strong>BIPIA</strong>: indirect injection, all positive.</li>
<li><strong>InjecAgent</strong>: agentic-flow injection, all positive.</li>
<li><strong>NotInject</strong>: benign text that looks injection-shaped, all negative.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="docs/plots/F3.svg" class="img-fluid figure-img"></p>
<figcaption>F3: Per-slice AUPRC grid</figcaption>
</figure>
</div>
<p><strong>What F3 shows:</strong> where AUPRC is defined, the detectors cluster near the random floor on pooled OOD.</p>
<p><strong>What F3 does not show:</strong> AUPRC/AUROC for all-positive or all-negative slices; those metrics are mathematically undefined there. Raw predictions still exist for alternative analyses.</p>
</section>
<section id="threshold-transfer" class="level2">
<h2 class="anchored" data-anchor-id="threshold-transfer">4. Threshold Transfer</h2>
<p>The detection policy tunes a threshold on validation to target <strong>FPR &lt;= 1%</strong>. That target does not reliably transfer to held-out test sources.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Detector</th>
<th style="text-align: right;">Mean threshold</th>
<th style="text-align: right;">Test recall</th>
<th style="text-align: right;">Test FPR</th>
<th>Read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;">0.829</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.010</td>
<td>holds FPR, catches very little</td>
</tr>
<tr class="even">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">0.795</td>
<td style="text-align: right;">0.424</td>
<td style="text-align: right;">0.115</td>
<td>catches more, but far exceeds FPR target</td>
</tr>
<tr class="odd">
<td>TF-IDF + LR</td>
<td style="text-align: right;">0.657</td>
<td style="text-align: right;">0.333</td>
<td style="text-align: right;">0.067</td>
<td>exceeds FPR target</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="docs/plots/F4.svg" class="img-fluid figure-img"></p>
<figcaption>F4: Detection-threshold transfer</figcaption>
</figure>
</div>
<p><strong>What F4 shows:</strong> the validation-tuned 1% FPR policy does not become a robust test-time operating point under source shift.</p>
<p><strong>What F4 does not show:</strong> a recommended production threshold. Deployment is out of scope.</p>
</section>
<section id="calibration" class="level2">
<h2 class="anchored" data-anchor-id="calibration">5. Calibration</h2>
<p>Calibration asks whether scores behave like probabilities. A model that gives 0.90 scores should be correct about 90% of the time in that score region.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Detector</th>
<th style="text-align: right;">Mean ECE</th>
<th style="text-align: right;">Mean Brier</th>
<th>Read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;"><strong>0.144</strong></td>
<td style="text-align: right;"><strong>0.265</strong></td>
<td>best calibrated</td>
</tr>
<tr class="even">
<td>TF-IDF + LR</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;">0.376</td>
<td>weaker but better than LoRA</td>
</tr>
<tr class="odd">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">0.444</td>
<td style="text-align: right;">0.451</td>
<td>fine-tuning worsens calibration</td>
</tr>
<tr class="even">
<td>ProtectAI v1</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.470</td>
<td>poorly calibrated on this slate</td>
</tr>
<tr class="odd">
<td>ProtectAI v2</td>
<td style="text-align: right;">0.460</td>
<td style="text-align: right;">0.471</td>
<td>poorly calibrated on this slate</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="docs/plots/F5.svg" class="img-fluid figure-img"></p>
<figcaption>F5: Calibration comparison</figcaption>
</figure>
</div>
<p><strong>What F5 shows:</strong> frozen probe has the lowest calibration error; LoRA’s scores are much less probability-like on this OOD evaluation.</p>
<p><strong>What F5 does not show:</strong> whether post-hoc calibration would fix the cross-family ranking failure.</p>
</section>
<section id="secondary-table-auroc" class="level2">
<h2 class="anchored" data-anchor-id="secondary-table-auroc">6. Secondary Table: AUROC</h2>
<p>AUROC is reported for comparison with other work, but AUPRC is the headline metric because this task is imbalanced.</p>
<p>Single-class slices are omitted here for the same reason as the AUPRC table: AUROC requires both positives and negatives.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Detector &nbsp;Slice</th>
<th style="text-align: right;">JBB</th>
<th style="text-align: right;">XSTest</th>
<th style="text-align: right;">Pooled OOD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;">0.542 [0.520, 0.565]</td>
<td style="text-align: right;">0.537 [0.522, 0.552]</td>
<td style="text-align: right;"><strong>0.515 [0.505, 0.525]</strong></td>
</tr>
<tr class="even">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">0.528 [0.505, 0.552]</td>
<td style="text-align: right;">0.530 [0.515, 0.546]</td>
<td style="text-align: right;">0.383 [0.374, 0.392]</td>
</tr>
<tr class="odd">
<td>TF-IDF + LR</td>
<td style="text-align: right;">0.445 [0.422, 0.469]</td>
<td style="text-align: right;">0.451 [0.436, 0.466]</td>
<td style="text-align: right;">0.371 [0.362, 0.381]</td>
</tr>
<tr class="even">
<td>ProtectAI v1</td>
<td style="text-align: right;">0.533 [0.464, 0.602]</td>
<td style="text-align: right;">0.544 [0.497, 0.589]</td>
<td style="text-align: right;">0.440 [0.409, 0.469]</td>
</tr>
<tr class="odd">
<td>ProtectAI v2</td>
<td style="text-align: right;">0.594 [0.512, 0.671]</td>
<td style="text-align: right;">0.391 [0.341, 0.442]</td>
<td style="text-align: right;">0.402 [0.369, 0.437]</td>
</tr>
<tr class="even">
<td>Random floor</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.500</td>
</tr>
</tbody>
</table>
</section>
<section id="raw-artifacts" class="level2">
<h2 class="anchored" data-anchor-id="raw-artifacts">7. Raw Artifacts</h2>
<p>The tables and figures above are enough to understand the result. The raw evaluation artifacts are committed under <code>evals/</code> for readers who want to audit the math, re-render figures, or extend the analysis.</p>
<p>All five figures (F1–F5) record their source-artifact paths in the per-figure <code>.meta.json</code> sidecars next to the SVGs in <code>docs/plots/</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Artifact</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>evals/bootstrap/marginal_cells.parquet</code></td>
<td>AUPRC/AUROC point estimates and marginal CIs</td>
</tr>
<tr class="even">
<td><code>evals/bootstrap/paired_cells.parquet</code></td>
<td>paired-bootstrap detector-vs-detector differences</td>
</tr>
<tr class="odd">
<td><code>evals/predictions_val/</code></td>
<td>direct+benign validation predictions used for direct-performance checks</td>
</tr>
<tr class="even">
<td><code>evals/metrics/per_cell.parquet</code></td>
<td>per-detector, per-fold, per-seed metrics including ECE and Brier</td>
</tr>
<tr class="odd">
<td><code>evals/operating_points/dual_policy.parquet</code></td>
<td>validation-fitted detection and verification thresholds</td>
</tr>
<tr class="even">
<td><code>evals/predictions/</code></td>
<td>per-row predictions used by downstream analyses</td>
</tr>
</tbody>
</table>
<p>Each figure sidecar under <code>docs/plots/F*.meta.json</code> records <code>data_mode: canonical</code>, ADR-062, the source artifact path, commit SHA, and generation time.</p>
</section>
<section id="cross-references" class="level2">
<h2 class="anchored" data-anchor-id="cross-references">Cross-References</h2>
<ul>
<li><a href="./EXECUTIVE_SUMMARY.html">Executive summary</a>: one-page version.</li>
<li><a href="./WRITEUP.html">Writeup</a>: methodology narrative.</li>
<li><a href="./WRITEUP/eval-design.html">Evaluation design</a>: detailed metric rationale.</li>
<li><a href="./WRITEUP/threshold-policy.html">Threshold policy</a>: detection and verification operating-point methodology.</li>
<li><a href="./WRITEUP/reference-scorer-audit.html">Reference-scorer audit</a>: ProtectAI contamination caveats.</li>
</ul>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Results: tables, figures, and source artifacts"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Canonical results page for the prompt-injection classifier evaluation."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu"># Results</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>This page is the evidence layer behind the landing page. It gives exact values,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>five canonical figures, and pointers to the raw artifacts that produced them.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>**How to read this page:**</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Scan the **Metric Primer** if AUPRC or confidence intervals are new.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Read **Direct Prompt-Injection Performance** and **§1 Cross-Family OOD</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>   Table** together. The direct task was learned; cross-family generalization</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>   failed.</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Use **§1B–§5** for the follow-up findings: DeBERTa ablation, frozen-probe</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>   vs LoRA, per-slice behavior, threshold transfer, and calibration.</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Use **§6–§7** for AUROC comparison and raw artifact pointers.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">## Metric Primer</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**AUPRC** is the primary metric. It measures whether positives are ranked</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  ahead of negatives. On imbalanced data, a random ranking scores the positive</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  rate. For the pooled out-of-distribution (OOD) slice, <span class="in">`pooled_ood`</span>, that</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  floor is **412 / 1101 = 0.374**.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**AUROC** is secondary. Its random floor is always 0.5, but it can make</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  imbalanced tasks look better than they are.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Recall at FPR &lt;= 1%** asks: with at most 1 false alarm allowed per 100</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  benign examples, how many attacks are caught?</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**95% CI** shows uncertainty. A narrow interval supports a sharper claim; an</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  interval crossing an important baseline means the claim is weak.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**ECE and Brier** are calibration errors. Lower is better.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## Direct Prompt-Injection Performance</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>The detectors did learn direct prompt-injection patterns. This matters because</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>the OOD result is not a total capability failure: they learned the direct task,</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>then failed to carry that skill cleanly across attack-family shift.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>**Balanced validation view.** Source:</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="in">`evals/predictions_val/`</span>, pooled across trained in-house detectors, folds, and</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>seeds. This split contains direct-injection positives and benign negatives, so</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>AUPRC, AUROC, and recall are all defined.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detector <span class="pp">|</span> Direct+benign validation AUPRC <span class="pp">|</span> AUROC <span class="pp">|</span> Recall@0.5 <span class="pp">|</span> Read <span class="pp">|</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---|</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT LoRA <span class="pp">|</span> **0.974** | **0.993** | **0.934** <span class="pp">|</span> strong direct-pattern detection <span class="pp">|</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TF-IDF + LR <span class="pp">|</span> 0.971 <span class="pp">|</span> 0.992 <span class="pp">|</span> 0.930 <span class="pp">|</span> lexical direct baseline is also strong <span class="pp">|</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT frozen probe <span class="pp">|</span> 0.653 <span class="pp">|</span> 0.907 <span class="pp">|</span> 0.849 <span class="pp">|</span> weaker ranking, still discriminative <span class="pp">|</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>**Held-out direct-source view.** Source:</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="in">`evals/predictions/*__epoch2.parquet`</span>, pooled across folds and seeds. This LODO</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>test holds out one direct-injection source at a time. It is all positive by</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>design, so the table reports recall only.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detector <span class="pp">|</span> LODO direct-source recall@0.5 <span class="pp">|</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT frozen probe <span class="pp">|</span> **0.641** <span class="pp">|</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT LoRA <span class="pp">|</span> 0.625 <span class="pp">|</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT full fine-tune <span class="pp">|</span> 0.558 <span class="pp">|</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>**Takeaway:** direct-prompt-injection detection was not the failure mode. The</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>failure is transfer: success on direct examples did not produce robust OOD</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>ranking or stable thresholds when the attack family changed. False positives,</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>AUPRC, and AUROC are omitted from the LODO direct-source table because that</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>test is all-positive.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Cross-Family OOD Table: AUPRC</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>Source: <span class="in">`evals/bootstrap/marginal_cells.parquet`</span>, seed=1, BCa bootstrap with</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>10000 resamples. Single-class slices are omitted from this table because AUPRC</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>requires both positives and negatives.</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>**Reading this table:**</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The headline column is **Pooled OOD AUPRC**, the rightmost column with both</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>  positives and negatives.</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A random ranking on Pooled OOD scores about **0.374**. Any detector at or</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>  below that floor is not clearly better than guessing.</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>JBB and XSTest show whether a detector is strong on one OOD family but weak</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>  on another.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The main checks are magnitude against the random floor, 95% CI width, and</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>  cross-detector ordering on pooled OOD.</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detector \ Slice <span class="pp">|</span> JBB (100p/100n) <span class="pp">|</span> XSTest (200p/250n) <span class="pp">|</span> Pooled OOD (412p/689n) <span class="pp">|</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT frozen probe <span class="pp">|</span> 0.552 <span class="co">[</span><span class="ot">0.520, 0.580</span><span class="co">]</span> <span class="pp">|</span> 0.468 <span class="co">[</span><span class="ot">0.448, 0.486</span><span class="co">]</span> <span class="pp">|</span> **0.364 [0.354, 0.375]** <span class="pp">|</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v1 <span class="pp">|</span> 0.519 <span class="co">[</span><span class="ot">0.437, 0.597</span><span class="co">]</span> <span class="pp">|</span> 0.469 <span class="co">[</span><span class="ot">0.415, 0.523</span><span class="co">]</span> <span class="pp">|</span> 0.361 <span class="co">[</span><span class="ot">0.330, 0.391</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v2 <span class="pp">|</span> 0.556 <span class="co">[</span><span class="ot">0.453, 0.648</span><span class="co">]</span> <span class="pp">|</span> 0.382 <span class="co">[</span><span class="ot">0.333, 0.429</span><span class="co">]</span> <span class="pp">|</span> 0.314 <span class="co">[</span><span class="ot">0.283, 0.345</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT LoRA <span class="pp">|</span> 0.535 <span class="co">[</span><span class="ot">0.504, 0.563</span><span class="co">]</span> <span class="pp">|</span> 0.467 <span class="co">[</span><span class="ot">0.447, 0.486</span><span class="co">]</span> <span class="pp">|</span> 0.293 <span class="co">[</span><span class="ot">0.286, 0.301</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TF-IDF + LR <span class="pp">|</span> 0.470 <span class="co">[</span><span class="ot">0.443, 0.496</span><span class="co">]</span> <span class="pp">|</span> 0.395 <span class="co">[</span><span class="ot">0.379, 0.410</span><span class="co">]</span> <span class="pp">|</span> 0.291 <span class="co">[</span><span class="ot">0.283, 0.298</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Random floor <span class="pp">|</span> 0.500 <span class="pp">|</span> 0.444 <span class="pp">|</span> 0.374 <span class="pp">|</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>**Takeaway:** this is where the direct-trained detectors break. The best pooled</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>OOD AUPRC is the frozen probe at 0.364, but the random floor is 0.374. The</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>honest reading is that none of these detectors clearly learned the cross-family</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>OOD ranking problem.</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="al">![F1: Pooled OOD AUPRC vs random floor](docs/plots/F1.svg)</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>**What F1 shows:** exact pooled OOD AUPRC values with 95% CIs and the random</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>floor.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>**What F1 does not show:** deployment readiness, per-slice behavior, or whether</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>single-class slices were caught at a fixed threshold.</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="fu">## §1B Ablation: does a longer-context backbone fix the OOD gap?</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>The headline table at §1 shows ModernBERT's frozen-probe (8192-token native</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>attention window) leading the in-house detectors at pooled OOD AUPRC 0.364</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>— but still essentially at the random floor (0.374). A natural follow-up</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>question: *would a different short-context backbone do better with the right</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>truncation handling, or is the OOD gap really about the architecture itself?*</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>The v1.1.2 medium ablation per <span class="co">[</span><span class="ot">ADR-060</span><span class="co">](decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.md)</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>trains DeBERTa-v3-base (184M params; 512-token native attention) twice with</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>2 truncation strategies, fold 0 / seed 42 only:</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**chunk-and-average**: tokenize the full text; emit 512-token windows with</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>  stride 256 (50% overlap); per-window forward pass; average per-window</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>  class-1 softmax probabilities → final score.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**head-truncation**: tokenize the full text; take the first 512 tokens; standard</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>  single-window forward pass.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>If the ModernBERT advantage at §1 came from its long context window,</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>chunk-and-average (which gives DeBERTa access to the full text) should beat</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>head-truncation by a wide margin. If the advantage is architectural, the two</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>strategies should look similar.</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DeBERTa-v3-base strategy <span class="pp">|</span> JBB (100p/100n) AUPRC <span class="pp">|</span> XSTest (200p/250n) AUPRC <span class="pp">|</span> Pooled OOD (412p/689n) AUPRC <span class="pp">|</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> chunk-and-average  <span class="pp">|</span> 0.486 <span class="pp">|</span> 0.397 <span class="pp">|</span> **0.291** <span class="pp">|</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> head-truncation    <span class="pp">|</span> 0.489 <span class="pp">|</span> 0.391 <span class="pp">|</span> **0.290** <span class="pp">|</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>**What §1B shows:** the two truncation strategies produce essentially</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>identical per-slice metrics across the 5-slice OOD slate. Long context (the</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>chunk-and-average path) provides no measurable benefit over head-truncation</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>on this slate.</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>**What §1B does not show:** DeBERTa-v3-base does not beat ModernBERT's</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>frozen-probe (0.364 pooled OOD AUPRC) — both DeBERTa strategies score ~20%</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>lower. The headline ladder ordering at §1 is preserved.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>**Interpretation:** by the ADR-060 confound-control reading, the ModernBERT</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>advantage on the headline ladder is **backbone-dominant**, not</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>context-window-dominant. A bigger context window alone does not close the</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>OOD generalization gap on this slate — it is the architecture (and/or</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>pre-training pretext) that matters. The DeBERTa-vs-ModernBERT residual gap</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>that *remains* (~0.29 vs 0.36) has its own confounds (backbone size,</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>pre-training data, tokenizer family) that this ablation does not separate;</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>see <span class="co">[</span><span class="ot">WRITEUP/limitations-and-future-work.md §9.2</span><span class="co">](WRITEUP/limitations-and-future-work.md#92-architectures-evaluated-and-dropped)</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>for the residual-confound discussion. See <span class="co">[</span><span class="ot">ADR-063</span><span class="co">](decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.md)</span></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>for the execution record + actual GPU spend ($1.34 of the $5-7 envelope).</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Frozen Probe vs LoRA</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>The frozen probe uses the pretrained ModernBERT backbone without task-specific</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>weight movement. LoRA fine-tunes a small adapter on the direct-injection</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>training pool. If fine-tuning helped OOD, LoRA should beat the frozen probe.</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>It does not.</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Comparison <span class="pp">|</span> Slice <span class="pp">|</span> Metric <span class="pp">|</span> LoRA - frozen probe <span class="pp">|</span> 95% CI <span class="pp">|</span> Read <span class="pp">|</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---:|---:|---|</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA vs frozen probe <span class="pp">|</span> JBB <span class="pp">|</span> AUPRC <span class="pp">|</span> -0.016 <span class="pp">|</span> <span class="co">[</span><span class="ot">-0.024, -0.009</span><span class="co">]</span> <span class="pp">|</span> LoRA worse <span class="pp">|</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA vs frozen probe <span class="pp">|</span> XSTest <span class="pp">|</span> AUPRC <span class="pp">|</span> -0.001 <span class="pp">|</span> <span class="co">[</span><span class="ot">-0.006, 0.004</span><span class="co">]</span> <span class="pp">|</span> indistinguishable <span class="pp">|</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA vs frozen probe <span class="pp">|</span> Pooled OOD <span class="pp">|</span> AUPRC <span class="pp">|</span> -0.071 <span class="pp">|</span> see marginal table <span class="pp">|</span> LoRA much worse <span class="pp">|</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="al">![F2: Frozen probe vs LoRA paired deltas](docs/plots/F2.svg)</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>**What F2 shows:** paired-bootstrap AUPRC differences for the comparable</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>both-class slices available in <span class="in">`evals/bootstrap/paired_cells.parquet`</span>.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>**What F2 does not show:** a paired pooled OOD CI, because the persisted paired</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>artifact does not include that pooled comparison; the pooled delta above is the</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>difference between marginal point estimates.</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Per-Slice View</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>The OOD slate is deliberately not one homogeneous test set:</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**JBB**: jailbreak-style harmful elicitation, both classes.</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**XSTest**: jailbreak-as-question style, both classes.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**BIPIA**: indirect injection, all positive.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**InjecAgent**: agentic-flow injection, all positive.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**NotInject**: benign text that looks injection-shaped, all negative.</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="al">![F3: Per-slice AUPRC grid](docs/plots/F3.svg)</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>**What F3 shows:** where AUPRC is defined, the detectors cluster near the random</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>floor on pooled OOD.</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>**What F3 does not show:** AUPRC/AUROC for all-positive or all-negative slices;</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>those metrics are mathematically undefined there. Raw predictions still exist</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>for alternative analyses.</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Threshold Transfer</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>The detection policy tunes a threshold on validation to target **FPR &lt;= 1%**.</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>That target does not reliably transfer to held-out test sources.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detector <span class="pp">|</span> Mean threshold <span class="pp">|</span> Test recall <span class="pp">|</span> Test FPR <span class="pp">|</span> Read <span class="pp">|</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---|</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT frozen probe <span class="pp">|</span> 0.829 <span class="pp">|</span> 0.063 <span class="pp">|</span> 0.010 <span class="pp">|</span> holds FPR, catches very little <span class="pp">|</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT LoRA <span class="pp">|</span> 0.795 <span class="pp">|</span> 0.424 <span class="pp">|</span> 0.115 <span class="pp">|</span> catches more, but far exceeds FPR target <span class="pp">|</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TF-IDF + LR <span class="pp">|</span> 0.657 <span class="pp">|</span> 0.333 <span class="pp">|</span> 0.067 <span class="pp">|</span> exceeds FPR target <span class="pp">|</span></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a><span class="al">![F4: Detection-threshold transfer](docs/plots/F4.svg)</span></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>**What F4 shows:** the validation-tuned 1% FPR policy does not become a robust</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>test-time operating point under source shift.</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>**What F4 does not show:** a recommended production threshold. Deployment is out</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>of scope.</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Calibration</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>Calibration asks whether scores behave like probabilities. A model that gives</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>0.90 scores should be correct about 90% of the time in that score region.</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detector <span class="pp">|</span> Mean ECE <span class="pp">|</span> Mean Brier <span class="pp">|</span> Read <span class="pp">|</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---|</span></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT frozen probe <span class="pp">|</span> **0.144** | **0.265** <span class="pp">|</span> best calibrated <span class="pp">|</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TF-IDF + LR <span class="pp">|</span> 0.350 <span class="pp">|</span> 0.376 <span class="pp">|</span> weaker but better than LoRA <span class="pp">|</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT LoRA <span class="pp">|</span> 0.444 <span class="pp">|</span> 0.451 <span class="pp">|</span> fine-tuning worsens calibration <span class="pp">|</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v1 <span class="pp">|</span> 0.452 <span class="pp">|</span> 0.470 <span class="pp">|</span> poorly calibrated on this slate <span class="pp">|</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v2 <span class="pp">|</span> 0.460 <span class="pp">|</span> 0.471 <span class="pp">|</span> poorly calibrated on this slate <span class="pp">|</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="al">![F5: Calibration comparison](docs/plots/F5.svg)</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>**What F5 shows:** frozen probe has the lowest calibration error; LoRA's scores</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>are much less probability-like on this OOD evaluation.</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>**What F5 does not show:** whether post-hoc calibration would fix the</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>cross-family ranking failure.</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6. Secondary Table: AUROC</span></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>AUROC is reported for comparison with other work, but AUPRC is the headline</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>metric because this task is imbalanced.</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>Single-class slices are omitted here for the same reason as the AUPRC table:</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>AUROC requires both positives and negatives.</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detector \ Slice <span class="pp">|</span> JBB <span class="pp">|</span> XSTest <span class="pp">|</span> Pooled OOD <span class="pp">|</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT frozen probe <span class="pp">|</span> 0.542 <span class="co">[</span><span class="ot">0.520, 0.565</span><span class="co">]</span> <span class="pp">|</span> 0.537 <span class="co">[</span><span class="ot">0.522, 0.552</span><span class="co">]</span> <span class="pp">|</span> **0.515 [0.505, 0.525]** <span class="pp">|</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ModernBERT LoRA <span class="pp">|</span> 0.528 <span class="co">[</span><span class="ot">0.505, 0.552</span><span class="co">]</span> <span class="pp">|</span> 0.530 <span class="co">[</span><span class="ot">0.515, 0.546</span><span class="co">]</span> <span class="pp">|</span> 0.383 <span class="co">[</span><span class="ot">0.374, 0.392</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TF-IDF + LR <span class="pp">|</span> 0.445 <span class="co">[</span><span class="ot">0.422, 0.469</span><span class="co">]</span> <span class="pp">|</span> 0.451 <span class="co">[</span><span class="ot">0.436, 0.466</span><span class="co">]</span> <span class="pp">|</span> 0.371 <span class="co">[</span><span class="ot">0.362, 0.381</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v1 <span class="pp">|</span> 0.533 <span class="co">[</span><span class="ot">0.464, 0.602</span><span class="co">]</span> <span class="pp">|</span> 0.544 <span class="co">[</span><span class="ot">0.497, 0.589</span><span class="co">]</span> <span class="pp">|</span> 0.440 <span class="co">[</span><span class="ot">0.409, 0.469</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v2 <span class="pp">|</span> 0.594 <span class="co">[</span><span class="ot">0.512, 0.671</span><span class="co">]</span> <span class="pp">|</span> 0.391 <span class="co">[</span><span class="ot">0.341, 0.442</span><span class="co">]</span> <span class="pp">|</span> 0.402 <span class="co">[</span><span class="ot">0.369, 0.437</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Random floor <span class="pp">|</span> 0.500 <span class="pp">|</span> 0.500 <span class="pp">|</span> 0.500 <span class="pp">|</span></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7. Raw Artifacts</span></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>The tables and figures above are enough to understand the result. The raw</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>evaluation artifacts are committed under <span class="in">`evals/`</span> for readers who want to audit</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>the math, re-render figures, or extend the analysis.</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>All five figures (F1–F5) record their source-artifact paths in the per-figure</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="in">`.meta.json`</span> sidecars next to the SVGs in <span class="in">`docs/plots/`</span>.</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Artifact <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`evals/bootstrap/marginal_cells.parquet`</span> <span class="pp">|</span> AUPRC/AUROC point estimates and marginal CIs <span class="pp">|</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`evals/bootstrap/paired_cells.parquet`</span> <span class="pp">|</span> paired-bootstrap detector-vs-detector differences <span class="pp">|</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`evals/predictions_val/`</span> <span class="pp">|</span> direct+benign validation predictions used for direct-performance checks <span class="pp">|</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`evals/metrics/per_cell.parquet`</span> <span class="pp">|</span> per-detector, per-fold, per-seed metrics including ECE and Brier <span class="pp">|</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`evals/operating_points/dual_policy.parquet`</span> <span class="pp">|</span> validation-fitted detection and verification thresholds <span class="pp">|</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`evals/predictions/`</span> <span class="pp">|</span> per-row predictions used by downstream analyses <span class="pp">|</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>Each figure sidecar under <span class="in">`docs/plots/F*.meta.json`</span> records `data_mode:</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>canonical`, ADR-062, the source artifact path, commit SHA, and generation time.</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cross-References</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Executive summary</span><span class="co">](EXECUTIVE_SUMMARY.md)</span>: one-page version.</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Writeup</span><span class="co">](WRITEUP.md)</span>: methodology narrative.</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Evaluation design</span><span class="co">](WRITEUP/eval-design.md)</span>: detailed metric rationale.</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Threshold policy</span><span class="co">](WRITEUP/threshold-policy.md)</span>: detection and verification</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>  operating-point methodology.</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Reference-scorer audit</span><span class="co">](WRITEUP/reference-scorer-audit.md)</span>: ProtectAI</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>  contamination caveats.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>