<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Academic IMRAD article presenting the project’s methodology and findings.">

<title>Prompt-Injection Classification: Methodology and Capability Characterization (Academic Paper Format) – Prompt-injection classifier evaluation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6417478169390d5200ae675d66b5a4f4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Prompt-injection classifier evaluation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./RESULTS.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="./WRITEUP_PAPER.html">
 <span class="dropdown-text">Academic paper (IMRAD)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP_NARRATIVE.html">
 <span class="dropdown-text">Narrative arc (story)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP.html">
 <span class="dropdown-text">Router (pick a guide)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./READING_GUIDE.html">
 <span class="dropdown-text">Reading guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/data-decisions.html">
 <span class="dropdown-text">Data decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/model-rungs.html">
 <span class="dropdown-text">Model details</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/eval-design.html">
 <span class="dropdown-text">Evaluation design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/threshold-policy.html">
 <span class="dropdown-text">Threshold policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reference-scorer-audit.html">
 <span class="dropdown-text">Reference-scorer audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/methodology-guarantees.html">
 <span class="dropdown-text">Methodology guarantees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/limitations-and-future-work.html">
 <span class="dropdown-text">Limitations and future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reproducibility.html">
 <span class="dropdown-text">Reproducibility — three reproduction tiers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./decisions/README.html"> 
<span class="menu-text">Decisions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reference">    
        <li>
    <a class="dropdown-item" href="./docs/for-hiring-managers.html">
 <span class="dropdown-text">Project at a glance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./docs/site-reader-map.html">
 <span class="dropdown-text">Public site reader map</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EVIDENCE.html">
 <span class="dropdown-text">Evidence ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SPEC_SHEET.html">
 <span class="dropdown-text">Spec lock sheet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SUBMISSION_AUDIT.html">
 <span class="dropdown-text">Submission audit ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NEXT_STEPS.html">
 <span class="dropdown-text">Carryforward + future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions registry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/01_canonical_results.html">
 <span class="dropdown-text">Notebook: canonical results</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/02_frozen_vs_lora.html">
 <span class="dropdown-text">Notebook: frozen vs LoRA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/03_calibration.html">
 <span class="dropdown-text">Notebook: calibration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/04_ood_slate.html">
 <span class="dropdown-text">Notebook: OOD slate</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/brandon-behring/prompt-injection-detection-prototype" target="_blank"> 
<span class="menu-text">Repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./WRITEUP_PAPER.html">Methodology guides (pick a style)</a></li><li class="breadcrumb-item"><a href="./WRITEUP_PAPER.html">Academic paper (IMRAD)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Entry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Landing page (results + meaning)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">README + executive summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RESULTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Results: tables, figures, and source artifacts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology guides (pick a style)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP_PAPER.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Academic paper (IMRAD)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP_NARRATIVE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrative arc (story)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Router (1-page chooser)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./READING_GUIDE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading guide</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Detailed spokes (8 topics)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/data-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/model-rungs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/eval-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/threshold-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threshold policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reference-scorer-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/limitations-and-future-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Limitations and future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility — three reproduction tiers</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/01_canonical_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 — Canonical results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/02_frozen_vs_lora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/03_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 — Calibration battery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/04_ood_slate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 — OOD slate gap visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence + audit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EVIDENCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evidence ledger</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./docs/site-reader-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Public site reader map</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SPEC_SHEET.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spec lock sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SUBMISSION_AUDIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission audit ledger</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./NEXT_STEPS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carryforward + future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions registry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions (ADRs)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architecture Decision Records (ADRs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/upstream_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Upstream issues filed during this iteration</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-001-submission-deadline-and-scope-ambition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission deadline 2026-05-18 morning with infra-leveraged Long-scope attempt and fallback ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-002-deliverable-format-pdf-and-repo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — focused PDF plus public GitHub repo as evidence locker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-003-repo-visibility-public.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repository visibility — public from start (kit default ratified)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-004-reviewer-profile-and-hub-and-spoke-writeup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer profile A1+A2 with hub-and-spoke writeup structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-005-methodology-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-level methodology principles — methodology over metrics, honest evaluation preferred, structured limitations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-006-headline-metrics-and-statistical-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Headline metrics, operating-point pinpoints, and statistical apparatus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-007-rung-architecture-and-reference-scorers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology rung architecture — trained backbones, LLM-judge reference rungs, Cohen’s kappa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-008-data-scope-public-only-hybrid-splits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data scope — public-only sources, hybrid splits, NotInject inclusion (brief-level lock)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-009-process-mandates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Process mandates — two-tier reproducibility, marker-based testing, compute disclosure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-010-scope-limits-with-extension-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scope limits with per-bound extension conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-011-methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees — eight banned approaches surfaced as project commitments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-012-soft-signals-and-artifact-engagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Soft-signals naming discipline and external artifact engagement set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-013-kit-ratify-bulk-strictness-intake-notebook-persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kit-ratify bulk — Phase 0 strictness, brief-intake protocol, notebook role and RunPod persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-014-threat-model-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threat-model bundle — attack-class scope, language, length cap, truncation policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-015-rung-architecture-refinement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung architecture refinement — ModernBERT-base only trained slate, supersedes ADR-007</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-016-data-design-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data design bundle — source slate, splits, HF pinning, dedup, ordering, ceilings, ref-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-017-trained-rung-slate-expansion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trained-rung-slate expansion — TF-IDF plus LR classical floor and frozen-probe dual role</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-018-reference-scorer-slate-and-contamination-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference scorer slate and contamination stratification — OpenAI plus Anthropic LLM-judges plus ProtectAI v1 and v2 plus per-axis matched-budget</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-019-lora-and-transformer-training-recipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA and transformer-rung training recipe — hyperparameters, epochs, precision, class weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-020-compute-infrastructure-and-cost-discipline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute infrastructure and cost discipline — runpod-deploy 0.7.7 primitives, GPU failover, adaptive batch sizing, dual-layer cost tracking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-021-eval-slate-aggregation-and-recall-fpr-pinpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eval slate aggregation — pooled headline plus per-slice spoke and recall@FPR pinpoint feasibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-022-statistical-inference-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference apparatus — bootstrap N + stability check, multi-comparison stance, multi-seed protocol, paired-test method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-023-calibration-battery-and-interventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery composition — raw plus temperature plus isotonic interventions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-024-cross-fold-ci-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-fold CI methodology — cv_clt_ci (Bayle 2020) headline plus block-bootstrap-on-folds spoke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-025-dual-policy-threshold-characterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dual-policy threshold characterization at symmetric 1% cost weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-026-module-layout-concern-grouped-subpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module layout — concern-grouped sub-packages under src/</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-027-smoke-vs-canonical-execution-context-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Smoke vs canonical separation — three Makefile targets stratified by execution context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-028-coverage-floor-70pct-with-upstream-issue-filing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test coverage floor — 70% flat with co-locked upstream-issue-filing discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-029-test-marker-strategy-four-marker-ratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test marker strategy — ratify 4-marker stratification (unit / smoke / integration / network)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-030-deliverable-format-quarto-html-site.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — repo-only with Quarto-rendered HTML site via GitHub Actions (supersedes ADR-002)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-031-reviewer-reading-paths-quarto-site-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer reading paths — index.qmd entry-point with Quarto sidebar nav (supersedes ADR-004)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-032-hf-hub-publication-headline-rungs-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HF Hub checkpoint publication — publish primary headline rungs only with model card discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-033-github-release-strategy-rehearsal-plus-submission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitHub release strategy — rehearsal tag plus SemVer submission tag plus post-submission patches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-034-reproducibility-tier-full-ladder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility tier — full ladder T0 (eval-from-hub) plus T1 (smoke) plus T3 (headline-cloud)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-035-secrets-management-three-store-split.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secrets management — three-store split aligned with execution context (.env + RunPod pod-secrets + GH Actions repo Secrets)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-036-library-version-pins-tag-pin-plus-freeze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library version pins — tag pin to latest stable plus freeze for submission window (eval-toolkit v0.31.0 + runpod-deploy v0.7.7 + research_toolkit v1.9.1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-037-python-version-pin-3-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python version pin — ratify requires-python &gt;=3.13 (matches existing .python-version + bc8ce4e commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-038-phase-tailoring-light-roadmap-edits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase tailoring — light ROADMAP edits to Phase 4 close + Phase 5 description (preserves 5-phase structure)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-039-acceptance-criteria-six-gate-integration-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-specific acceptance criteria — 6-gate integration checklist for v1.0.0 submission tag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-040-phase-0-audit-findings-and-assumption-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 0 final audit findings + 7-assumption backfill (A-010 through A-016)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-041-phase-1-data-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 (Data) implementation bundle — manifest schema, SHA pinning, validator placement, loader arch, holdout sourcing, contamination corpus, output materialization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-042-llm-prelabel-dedup-holdout-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-judge pre-label as Q5 holdout-labeling bootstrap with human override</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-043-post-split-cross-source-leakage-cleanup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-split cross-source leakage cleanup — drop train+val rows that exact-match or cosine-near-match test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-044-phase-2-training-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 training implementation bundle — seed slate reconciliation + manifest move + classical-floor location + YAML config schema + trainer split + per-rung orchestration + fixture preflight</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-045-phase-3-evaluation-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 evaluation implementation bundle — scoring-first contract + 6-commit cadence + tiered reference scorers + classical-scaffold + full-pairwise persistence with headline-only WRITEUP + pydantic schema validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-046-phase-4-analysis-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 analysis implementation bundle — 6-commit cadence + scaffold-with-classical + always-emit-both-CIs auto-flag + MDE-on-every-emitted-CI + LLM-rater audit included (user-overridden from defer) + library-first hybrid figures + Phase 5 prep deferred</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-047-phase-1-library-first-carryforward-refactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 library-first carryforward refactor — audit findings + remediation plan (splits + dedup + leakage_report + contamination_scan migration to eval-toolkit primitives; orphaned code removed in-commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-048-llm-rater-reference-scorer-audit-protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-rater reference-scorer audit protocol — disagreement-with-LoRA baseline + stratified (5 OOD slices × 3 contamination_states) sampling + fixed 2-axis rubric + inter-rater gpt-4o-plus-claude-sonnet + dry-run-then-single-approval cost UX</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-049-gpu-order-priority-refresh-a100-80g.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPU failover ladder priority refresh — A100-SXM4-80GB to position 1 + US-WA-1/US-CA-2 datacenter additions + EU-RO-1 drop (frozen-probe + LoRA canonical; full-FT deferred to post-rehearsal)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-050-rung-slate-narrowing-llm-judges-and-full-ft-ood-dropped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung slate narrowing — LLM judges dropped (cost) + full-FT OOD dropped (FUSE EIO crash); narrow supersession of ADR-018 reference slate + ADR-021 OOD comparison scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-051-v1.0.x-carryforward-of-t0-and-invariant-scaffolds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">v1.0.x carryforward of ADR-034 T0 score-match wiring + ADR-039 gate-3 invariant-scaffold unskip; narrow supersession with explicit v1.1.x landing condition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-052-full-ft-ood-drop-methodological-reframing-of-adr-050-r2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full-FT OOD inference drop — methodological reframing; narrow supersession of ADR-050 Revision 2 (FUSE-crash-only framing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-053-reading-guide-governance-and-newcomer-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading-guide governance + newcomer onboarding paths — two entry artifacts + 3 reading paths + Headline-finding-block + interpretation pedagogy + pointer convention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-054-results-page-as-third-entry-artifact-extending-adr-053.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RESULTS.md as third entry artifact — narrow supersession of ADR-053 dimension 1 (two-entry-artifacts); dimensions 2-5 unchanged</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-055-eval-toolkit-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">eval-toolkit installs from PyPI (not git+https) at v0.40.0+ — narrow supersession of ADR-036 “git URL is the only viable spec format”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-056-binary-calibrator-refactor-and-platt-beta-narrow-supersession-of-adr-023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery refactor to eval-toolkit <code>_binary</code> API + Platt + Beta calibrators landed — narrow supersession of ADR-023 “temperature + isotonic only” scope deferral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-057-manifest-schema-v3-backfill-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Per-prediction provenance manifests via scripts/backfill_provenance.py — schema, location, naming, idempotency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-058-eval-from-hub-non-dry-run-body-narrow-supersession-of-adr-051-block-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">scripts/eval_from_hub.py non-dry-run body wired — narrow supersession of ADR-051 Block A (T0 score-match carryforward); Block B (38 invariant scaffolds) remains carryforward</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-059-runpod-deploy-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">runpod-deploy installs from PyPI (not git+https) at v0.8.4+ — narrow supersession of ADR-036 “git URL is the only viable spec format” sub-claim for runpod-deploy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation methodology — chunk-and-average vs head-truncation × 5-slice OOD; infrastructure-only at v1.1.0; execution deferred to v1.1.1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-061-quarto-site-navigation-restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto site navigation restructure — landing-page rebuild + navbar consolidation + sidebar hub-spoke nesting (narrow supersession of ADR-053 navigation contract)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-062-quarto-writeup-clarity-and-canonical-figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto writeup clarity rewrite and canonical reviewer figure slate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation execution (v1.1.2 carryforward; narrow renaming-only supersession of ADR-060 “v1.1.1” body references) — null result, backbone-dominant interpretation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-064-writeup-hiring-manager-clarity-and-consistency-pass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup hiring-manager clarity polish + documentation-wide consistency conventions — additive layer on top of ADR-062</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup accuracy-audit methodology + Quarto callout-note convention + narrative invariants — additive layer on top of ADR-064</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-066-library-first-carryforward-refactor-v1-2-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library-first carryforward refactor v1.2.2 — consume 7 closed eval-toolkit primitives across 6 sites</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for factual-typo fixes in cross-reference slug filenames</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-069-immutability-narrow-relaxation-for-publisher-url-to-doi-canonicalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for academic publisher-URL → DOI canonicalization in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-070-quarto-render-only-markdown-corrections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for render-only Markdown corrections in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-071-adr-cross-reference-slug-sweep-closure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Execute the slug-sweep authorized by ADR-067 + ADR-068 + ADR-069 that was never actually completed in any prior commit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-072-adr-051-052-frontmatter-and-structural-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill missing frontmatter fields + Alternatives sections + Status headings for ADR-051 + ADR-052 per ADR-067-style narrow-relaxation discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-073-adr-immutability-rule-consolidated-re-statement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collapse the four-ADR narrow-relaxation chain (ADR-067/068/069/070) into a single consolidated immutability rule with four named exception classes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-074-adr-064-self-criticism-quote-redaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Replace verbatim self-criticism quote in ADR-064 frontmatter claim + body context with a neutral paraphrase preserving the decision</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-075-full-ft-ood-drop-rationale-unified-narrative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unify the ADR-050 Revision 2 (FUSE-crash-forced-drop) and ADR-052 (methodology-load-bearing-with-crash-as-trigger) framings into a single account</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-076-superseded-by-and-closing-commit-frontmatter-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill superseded_by on ADR-046 + ADR-054 + ADR-061 (→ ADR-062) + closing_commit on ADR-071-075 per ADR-072 frontmatter-backfill discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-077-supersession-backlink-and-frontmatter-octal-quoting-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill supersession back-links + quote octal-risk YAML integer fields in ADR-007 + ADR-015 + ADR-018 + ADR-021 + ADR-052 frontmatter per ADR-076 frontmatter-backfill discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-078-executive-summary-absorbed-into-readme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Absorb EXECUTIVE_SUMMARY content into README; retire EXECUTIVE_SUMMARY.md as standalone file</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-079-two-guide-reader-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-080-reviewer-url-pin-numeric-correction-adr-078-079.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correct reviewer URL pin numeric defect in ADR-078 + ADR-079 (tree/v1.2.8 → tree/v1.0.0); axis-only supersession on the reviewer-URL-pin axis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-081-frontmatter-status-field-split-narrow-relaxation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authorize frontmatter <code>status:</code> field split (verbose-context → pure-Nygard <code>status:</code> + new <code>lifecycle-note:</code>) as an extension of the ADR-072 / ADR-076 / ADR-077 frontmatter-backfill narrow-relaxation discipline; apply to ADR-060 as the seed case</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#prompt-injection-classification-methodology-and-capability-characterization" id="toc-prompt-injection-classification-methodology-and-capability-characterization" class="nav-link active" data-scroll-target="#prompt-injection-classification-methodology-and-capability-characterization">Prompt-Injection Classification: Methodology and Capability Characterization</a>
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">§0. Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">§1. Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">§2. Background</a>
  <ul class="collapse">
  <li><a href="#prompt-injection-landscape" id="toc-prompt-injection-landscape" class="nav-link" data-scroll-target="#prompt-injection-landscape">§2.1 Prompt-injection landscape</a></li>
  <li><a href="#existing-detectors" id="toc-existing-detectors" class="nav-link" data-scroll-target="#existing-detectors">§2.2 Existing detectors</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">§2.3 Data sources</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">§3. Methods</a>
  <ul class="collapse">
  <li><a href="#data-sources-and-lodo-splits" id="toc-data-sources-and-lodo-splits" class="nav-link" data-scroll-target="#data-sources-and-lodo-splits">§3.1 Data sources and LODO splits</a></li>
  <li><a href="#model-rungs" id="toc-model-rungs" class="nav-link" data-scroll-target="#model-rungs">§3.2 Model rungs</a></li>
  <li><a href="#evaluation-slate" id="toc-evaluation-slate" class="nav-link" data-scroll-target="#evaluation-slate">§3.3 Evaluation slate</a></li>
  <li><a href="#statistical-apparatus" id="toc-statistical-apparatus" class="nav-link" data-scroll-target="#statistical-apparatus">§3.4 Statistical apparatus</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">§4. Results</a>
  <ul class="collapse">
  <li><a href="#direct-prompt-injection-detection-was-learned" id="toc-direct-prompt-injection-detection-was-learned" class="nav-link" data-scroll-target="#direct-prompt-injection-detection-was-learned">§4.1 Direct prompt-injection detection was learned</a></li>
  <li><a href="#the-ood-wall-is-cross-family-not-source-level" id="toc-the-ood-wall-is-cross-family-not-source-level" class="nav-link" data-scroll-target="#the-ood-wall-is-cross-family-not-source-level">§4.2 The OOD wall is cross-family, not source-level</a></li>
  <li><a href="#trained-adapters-anti-correlated-with-cross-family-attack-class" id="toc-trained-adapters-anti-correlated-with-cross-family-attack-class" class="nav-link" data-scroll-target="#trained-adapters-anti-correlated-with-cross-family-attack-class">§4.3 Trained adapters anti-correlated with cross-family attack class</a></li>
  <li><a href="#context-window-ablation-produced-a-null-result" id="toc-context-window-ablation-produced-a-null-result" class="nav-link" data-scroll-target="#context-window-ablation-produced-a-null-result">§4.4 Context-window ablation produced a null result</a></li>
  <li><a href="#published-detector-versions-are-slice-dependent" id="toc-published-detector-versions-are-slice-dependent" class="nav-link" data-scroll-target="#published-detector-versions-are-slice-dependent">§4.5 Published detector versions are slice-dependent</a></li>
  <li><a href="#validation-thresholds-are-fragile-under-cross-family-shift" id="toc-validation-thresholds-are-fragile-under-cross-family-shift" class="nav-link" data-scroll-target="#validation-thresholds-are-fragile-under-cross-family-shift">§4.6 Validation thresholds are fragile under cross-family shift</a></li>
  <li><a href="#calibration-favors-the-frozen-probe" id="toc-calibration-favors-the-frozen-probe" class="nav-link" data-scroll-target="#calibration-favors-the-frozen-probe">§4.7 Calibration favors the frozen probe</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">§5. Discussion</a>
  <ul class="collapse">
  <li><a href="#mechanism-lexical-overfitting-plus-label-relevance-shift" id="toc-mechanism-lexical-overfitting-plus-label-relevance-shift" class="nav-link" data-scroll-target="#mechanism-lexical-overfitting-plus-label-relevance-shift">§5.1 Mechanism: lexical overfitting plus label-relevance shift</a></li>
  <li><a href="#implications-for-direct-detection-deployments" id="toc-implications-for-direct-detection-deployments" class="nav-link" data-scroll-target="#implications-for-direct-detection-deployments">§5.2 Implications for direct-detection deployments</a></li>
  <li><a href="#what-this-study-does-not-establish" id="toc-what-this-study-does-not-establish" class="nav-link" data-scroll-target="#what-this-study-does-not-establish">§5.3 What this study does not establish</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">§6. Limitations</a>
  <ul class="collapse">
  <li><a href="#scope-of-the-classifier" id="toc-scope-of-the-classifier" class="nav-link" data-scroll-target="#scope-of-the-classifier">§6.1 Scope of the classifier</a></li>
  <li><a href="#reference-scorer-contamination" id="toc-reference-scorer-contamination" class="nav-link" data-scroll-target="#reference-scorer-contamination">§6.2 Reference scorer contamination</a></li>
  <li><a href="#full-fine-tune-incomplete-experiment-status" id="toc-full-fine-tune-incomplete-experiment-status" class="nav-link" data-scroll-target="#full-fine-tune-incomplete-experiment-status">§6.3 Full-fine-tune incomplete-experiment status</a></li>
  <li><a href="#single-seed-headline-second-seed-stability-check" id="toc-single-seed-headline-second-seed-stability-check" class="nav-link" data-scroll-target="#single-seed-headline-second-seed-stability-check">§6.4 Single-seed headline + second-seed stability check</a></li>
  <li><a href="#mechanism-interpretation-is-not-empirically-demonstrated" id="toc-mechanism-interpretation-is-not-empirically-demonstrated" class="nav-link" data-scroll-target="#mechanism-interpretation-is-not-empirically-demonstrated">§6.5 Mechanism interpretation is not empirically demonstrated</a></li>
  <li><a href="#threshold-policy-framing" id="toc-threshold-policy-framing" class="nav-link" data-scroll-target="#threshold-policy-framing">§6.6 Threshold policy framing</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">§7. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">§8. References</a>
  <ul class="collapse">
  <li><a href="#decisions-architecture-decision-records" id="toc-decisions-architecture-decision-records" class="nav-link" data-scroll-target="#decisions-architecture-decision-records">Decisions (Architecture Decision Records)</a></li>
  <li><a href="#external-references" id="toc-external-references" class="nav-link" data-scroll-target="#external-references">External references</a></li>
  <li><a href="#project-artifacts" id="toc-project-artifacts" class="nav-link" data-scroll-target="#project-artifacts">Project artifacts</a></li>
  </ul></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary">Glossary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./WRITEUP_PAPER.html">Methodology guides (pick a style)</a></li><li class="breadcrumb-item"><a href="./WRITEUP_PAPER.html">Academic paper (IMRAD)</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Prompt-Injection Classification: Methodology and Capability Characterization (Academic Paper Format)</h1>
</div>

<div>
  <div class="description">
    Academic IMRAD article presenting the project’s methodology and findings.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="prompt-injection-classification-methodology-and-capability-characterization" class="level1">
<h1>Prompt-Injection Classification: Methodology and Capability Characterization</h1>
<p><strong>Author</strong>: Brandon Behring | <strong>Date</strong>: 2026-05-21 | <strong>Status</strong>: live-site current state <code>tree/v1.3.3</code>; original submission tag <code>tree/v1.0.0</code> (2026-05-18) preserved as historical reviewer pin per ADR-033.</p>
<blockquote class="blockquote">
<p><strong>Reader note.</strong> This is the academic paper format of the project writeup. For the same content in a narrative style, see <a href="./WRITEUP_NARRATIVE.html">WRITEUP_NARRATIVE.md</a>. Both guides cover the same evaluation, methodology, findings, and limitations; the register and structure differ. Definitions for all technical terms appear on first use and are cross-referenced to <a href="./docs/GLOSSARY.html">docs/GLOSSARY.md</a>.</p>
</blockquote>
<hr>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">§0. Abstract</h2>
<p>This study evaluates prompt-injection detectors under cross-family distribution shift. <strong>Motivation</strong>: detectors trained on direct prompt-injection examples are routinely benchmarked on similar direct text, leaving open the question of whether they have learned the attack class or memorized the lexical style of the training data. <strong>Approach</strong>: a detector ladder (TF-IDF + logistic regression, ModernBERT frozen probe, ModernBERT LoRA, and ProtectAI v1/v2 references) was evaluated under leave-one-dataset-out (LODO) splits against a held-out out-of-distribution (OOD) slate covering indirect injection (BIPIA), agentic-flow injection (InjecAgent), jailbreak- style questions (JBB-Behaviors, XSTest), and benign-but-injection- shaped text (NotInject). <strong>Finding</strong>: the in-house detectors learn direct prompt-injection detection effectively (LoRA reaches 0.974 AUPRC on balanced direct+benign validation) but generalize poorly to cross-family attacks (best pooled OOD AUPRC is 0.364 against a random floor of 0.374). Trained adapters (LoRA, TF-IDF + LR) score <em>below</em> the 0.5 AUROC random floor on cross-family OOD with confidence intervals that clear 0.5 on the wrong side; only the frozen probe remains above floor. <strong>Mechanism</strong>: the inversion is consistent with lexical overfitting combined with a label-relevance shift on the OOD slate, in which benign text engineered to resemble direct injection (NotInject) scores high and real-but-not-lexically-direct attacks (BIPIA, InjecAgent) score low. <strong>Implication</strong>: direct-pattern learning and cross-family transfer are distinct capabilities; results caution against deploying direct-injection-trained classifiers on mixed-family threat models without slice-specific evaluation. The contribution is the honest evaluation harness plus the negative result on cross-family transfer, not a production-ready detector.</p>
<hr>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">§1. Introduction</h2>
<p>Prompt injection denotes untrusted text intended to override the instructions an LLM-based system is supposed to follow [§GLOSSARY]. Detection of such text is a binary classification problem: given a text span, predict whether it constitutes an injection attempt. The practical difficulty is not the in-distribution case (where direct injection patterns are repetitive and lexically distinctive) but the out-of-distribution case where attack families differ from training. Existing detector evaluations frequently report aggregate metrics on held-out splits of the same training family, leaving the cross-family generalization question unaddressed.</p>
<p>This study addresses that gap. The research question is: &gt; <em>When detectors trained on direct prompt-injection examples are &gt; evaluated against attack families not present in training, does &gt; detection performance generalize?</em></p>
<p>The contribution is the negative answer plus the evaluation harness that produced it. Specifically:</p>
<ol type="1">
<li>A leave-one-dataset-out (LODO) evaluation discipline that prevents source-level leakage between training and evaluation data.</li>
<li>A detector ladder spanning a classical baseline (TF-IDF + logistic regression), a pretrained-backbone probe (ModernBERT frozen), a parameter-efficient fine-tune (ModernBERT LoRA), and reference scorers (ProtectAI v1, v2) with documented contamination status.</li>
<li>An out-of-distribution slate that intentionally varies attack family (indirect injection, agentic-flow injection, jailbreak-style questions, benign-but-injection-shaped text).</li>
<li>Bootstrap-based uncertainty quantification on every reported number, with single-class slice handling.</li>
<li>A mechanistic interpretation of the headline cross-family failure (§5 Discussion).</li>
</ol>
<p>The study is a capability characterization, not a deployment recommendation.</p>
<hr>
</section>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">§2. Background</h2>
<section id="prompt-injection-landscape" class="level3">
<h3 class="anchored" data-anchor-id="prompt-injection-landscape">§2.1 Prompt-injection landscape</h3>
<p>Prompt-injection attacks are diverse. Direct injection (the historically-studied class) embeds an attacker payload directly in the user input. Indirect injection routes the payload through third-party context that the LLM consumes. Agentic-flow injection spreads the payload across tool-use turns. Jailbreak-style questions elicit harmful behavior through framed questions rather than direct override commands. Benign-but-injection-shaped text (false-positive robustness) tests whether detectors over-fire on lexically suspicious benign content.</p>
<p>Public training corpora for prompt-injection detection have historically focused on direct injection; the cross-family generalization question has therefore been understudied.</p>
</section>
<section id="existing-detectors" class="level3">
<h3 class="anchored" data-anchor-id="existing-detectors">§2.2 Existing detectors</h3>
<p>Several published detectors target prompt-injection classification:</p>
<ul>
<li><strong>ProtectAI deberta-v3-base-prompt-injection v1 + v2</strong>: fine-tuned DeBERTa classifiers; trained on direct-injection corpora with documented overlap of the present study’s LODO training pool (see §6 Limitations and EVIDENCE §1-2).</li>
<li><strong>Lakera Guard</strong>: commercial detector; excluded from this study due to terms-of-service and partial-disclosure complexity (per ADR-018).</li>
<li><strong>LLM-judge approaches</strong> (GPT-4 family, Claude family): zero-shot classification via prompted instruction. Out of scope for the trained-detector ladder in this study; would require separate cost-per-call accounting (see ADR-018 + ADR-050).</li>
</ul>
</section>
<section id="data-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-sources">§2.3 Data sources</h3>
<p>The training pool comprises four public direct-prompt-injection corpora: <code>deepset/prompt-injections</code>, <code>Lakera/gandalf_ignore_instructions</code> (Gandalf), <code>Lakera/mosscap_prompt_injection</code> (Mosscap), and HackAPrompt’s 2024 corpus subset. The held-out OOD test slate comprises five sources spanning the four cross-family classes named in §2.1: BIPIA, InjecAgent, JBB-Behaviors, XSTest, NotInject.</p>
<p>Full source-level details, license attribution, and HuggingFace revision SHAs are documented in <a href="./WRITEUP/data-decisions.html">WRITEUP/data-decisions.md</a> and pinned in <code>data/source_manifest.yaml</code>.</p>
<hr>
</section>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">§3. Methods</h2>
<section id="data-sources-and-lodo-splits" class="level3">
<h3 class="anchored" data-anchor-id="data-sources-and-lodo-splits">§3.1 Data sources and LODO splits</h3>
<p>Leave-one-dataset-out (LODO) splits hold one source out of training while training on the remaining sources [§GLOSSARY]. Four LODO folds were generated, corresponding to the four training-pool sources. Each fold produces an independent (train, validation, test) partition where the test slate excludes all examples from one source. Source-disjoint splitting was preferred over row-disjoint splitting because the latter can leak source-level lexical features between train and test (per ADR-016).</p>
<p>Within each LODO fold, training data was deduplicated against the test slate via two-stage similarity matching: exact-hash overlap detection followed by MiniLM-L6-v2 cosine similarity at threshold ≥0.85. Both pipelines reported zero overlaps across all (train, val, test) per-fold-seed pairs (<code>evals/leakage_report.json</code>).</p>
</section>
<section id="model-rungs" class="level3">
<h3 class="anchored" data-anchor-id="model-rungs">§3.2 Model rungs</h3>
<p>The detector ladder comprises five rungs of increasing capability:</p>
<ol type="1">
<li><strong>TF-IDF + logistic regression</strong>: classical lexical baseline with character + word n-grams (per ADR-017). Trains in seconds per fold; serves as the “what does pure surface form get you” anchor.</li>
<li><strong>ModernBERT frozen probe</strong>: a linear classifier over the frozen pretrained ModernBERT-base representation [§GLOSSARY]. Tests what the pretrained backbone already encodes about injection-likely text without any LODO-pool adaptation.</li>
<li><strong>ModernBERT LoRA</strong>: parameter-efficient fine-tune (low-rank adapters at rank 8) [§GLOSSARY], with the backbone frozen and only the adapter weights updated on the LODO training pool.</li>
<li><strong>ModernBERT full fine-tune</strong>: full-parameter fine-tune. <em>LODO direct-source predictions were generated for 24 (fold, seed) cells in Phase 2; pooled OOD inference was not run due to a Phase 5 X11 file-system crash on the cloud GPU pool, documented in <a href="./decisions/ADR-075-full-ft-ood-drop-rationale-unified-narrative.html">ADR-075</a>.</em></li>
<li><strong>ProtectAI v1 + v2</strong> (reference scorers): published deberta-v3-base-prompt-injection classifiers, inference-only, with documented contamination status against the LODO training pool (see §6 Limitations).</li>
</ol>
<p>Reference rungs additionally include LLM-judge candidates (GPT-4 family, Claude family) per ADR-018; these were scoped out at ADR-050 following compute and contamination considerations.</p>
<p>Model details, hyperparameters, training cost, and per-rung recipe are documented in <a href="./WRITEUP/model-rungs.html">WRITEUP/model-rungs.md</a> and <a href="./docs/HYPERPARAMETER_DISCLOSURE.html">docs/HYPERPARAMETER_DISCLOSURE.md</a>.</p>
</section>
<section id="evaluation-slate" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-slate">§3.3 Evaluation slate</h3>
<p>Each LODO fold’s test slate aggregates five OOD slices:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Slice</th>
<th>Source</th>
<th>Composition</th>
<th>Attack class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BIPIA</td>
<td>Bochum-NLP/bipia</td>
<td>n=50 positive (all-positive slice)</td>
<td>indirect injection</td>
</tr>
<tr class="even">
<td>InjecAgent</td>
<td>uiuc-kang-lab/InjecAgent</td>
<td>n=62 positive (all-positive slice)</td>
<td>agentic-flow injection</td>
</tr>
<tr class="odd">
<td>JBB-Behaviors</td>
<td>JailbreakBench/JBB-Behaviors</td>
<td>n=100 positive + 100 negative</td>
<td>jailbreak-style questions</td>
</tr>
<tr class="even">
<td>XSTest</td>
<td>natolambert/xstest</td>
<td>n=200 positive + 250 negative</td>
<td>jailbreak/safe-question discrimination</td>
</tr>
<tr class="odd">
<td>NotInject</td>
<td>dattaroh/NotInject</td>
<td>n=339 negative (all-negative slice)</td>
<td>benign-but-injection-shaped (false-positive test)</td>
</tr>
</tbody>
</table>
<p>The pooled OOD slate concatenates all five slices: n=412 positive + 689 negative = 1101 total. Random AUPRC on the pooled OOD slate is therefore 412/1101 = 0.374.</p>
<p>Single-class slices (BIPIA, InjecAgent, NotInject) have mathematically undefined AUPRC/AUROC; the metrics pipeline filters them at source and reports recall-at-threshold instead. Pooled OOD is the canonical AUPRC reporting target; per-slice AUPRC is reported only on the both-class slices (JBB, XSTest, pooled OOD).</p>
<p>Slate composition, source revisions, and slice-class membership are documented in <a href="./WRITEUP/eval-design.html">WRITEUP/eval-design.md</a>.</p>
</section>
<section id="statistical-apparatus" class="level3">
<h3 class="anchored" data-anchor-id="statistical-apparatus">§3.4 Statistical apparatus</h3>
<p>Primary metric: <strong>AUPRC</strong> (Area Under the Precision-Recall Curve), chosen for its sensitivity to ranking quality on imbalanced data [§GLOSSARY]. On the pooled OOD slate (positive rate 0.374), random AUPRC equals 0.374; AUPRC below 0.374 indicates worse-than-random positive ranking. Secondary metric: <strong>AUROC</strong>; reported with 0.5 random floor.</p>
<p>Confidence intervals: <strong>BCa bootstrap</strong> (Bias-Corrected and Accelerated) with 10000 resamples [§GLOSSARY]. Per-(rung, fold, seed) bootstrap runs are persisted to <code>evals/bootstrap/</code>. Seed-stability check via second seed (seed=2 vs seed=1) per ADR-022.</p>
<p>Paired comparisons: paired-bootstrap-on-folds [§GLOSSARY], comparing two detectors on the same (fold, seed) cells to control for fold-specific variance.</p>
<p>Cross-fold confidence intervals: cv_clt (Bayle 2020 Theorem 3.1) [§GLOSSARY], applied to per-fold metric vectors. Paired with block-bootstrap-on-folds spoke per A-008 (LODO non-exchangeability sensitivity check; auto-flag column when block-bootstrap CI half-width / cv_clt CI half-width &gt; 1.5).</p>
<p>Threshold selection: <strong>detection policy</strong> (FPR ≤ 1% on validation, maximize recall) and <strong>verification policy</strong> (recall ≥ 99% on validation, minimize FPR), both fit per (fold, seed) with two-level paired-bootstrap CIs on test [§GLOSSARY] per ADR-025.</p>
<p>Calibration: ECE (Expected Calibration Error, equal-mass binning, n_bins=15) and Brier score, reported per detector per ADR-023. Reliability diagrams (raw + temperature + isotonic recalibration) are in <a href="./docs/plots/F4.svg">Figure F4</a>.</p>
<p>The evaluation harness uses the <a href="https://github.com/brandon-behring/eval-toolkit">eval-toolkit</a> library (pinned to v0.47.0) for all generic primitives; project- specific orchestrators are in <code>src/eval/</code>.</p>
<hr>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">§4. Results</h2>
<p>The seven numbered results are reported in equal-weight order. Each result is supported by tables and figures in <a href="./RESULTS.html">RESULTS.md</a>; this section presents the result + interpretation; the canonical numerical evidence lives in the appendix.</p>
<section id="direct-prompt-injection-detection-was-learned" class="level3">
<h3 class="anchored" data-anchor-id="direct-prompt-injection-detection-was-learned">§4.1 Direct prompt-injection detection was learned</h3>
<p>On balanced direct+benign validation data, LoRA reaches AUPRC 0.974 [CI 95% omitted on within-pool validation per ADR-021], AUROC 0.993, and recall-at-0.5 of 0.934. TF-IDF + LR reaches 0.971 / 0.992 / 0.930. The frozen probe is weaker at 0.653 / 0.907 / 0.849 but still discriminative.</p>
<p>On the LODO held-out direct-source test (all-positive by design), recall-at-0.5 is 0.641 (frozen probe), 0.625 (LoRA), and 0.558 (full fine-tune). Because no negatives are present in this slice, AUPRC, AUROC, and FPR are mathematically undefined and are not reported.</p>
<p>The detector pipeline can learn direct prompt-injection patterns; this establishes the in-distribution baseline against which §4.2-4.7 contrast.</p>
</section>
<section id="the-ood-wall-is-cross-family-not-source-level" class="level3">
<h3 class="anchored" data-anchor-id="the-ood-wall-is-cross-family-not-source-level">§4.2 The OOD wall is cross-family, not source-level</h3>
<p>The OOD test slate intentionally varies attack family rather than source identity within the same family. BIPIA exemplifies indirect injection; InjecAgent exemplifies agentic-flow injection; JBB- Behaviors and XSTest exemplify jailbreak-style questions; NotInject exemplifies benign-but-injection-shaped text. The training pool is direct-injection-heavy and includes none of these families.</p>
<p>The result is that direct-injection training does not transfer cleanly to these cross-family slices. Per-slice AUPRC (where defined, i.e., the both-class slices JBB and XSTest) is reported in <a href="./RESULTS.html#per-slice-view">RESULTS.md §3 Per-Slice View</a>.</p>
</section>
<section id="trained-adapters-anti-correlated-with-cross-family-attack-class" class="level3">
<h3 class="anchored" data-anchor-id="trained-adapters-anti-correlated-with-cross-family-attack-class">§4.3 Trained adapters anti-correlated with cross-family attack class</h3>
<p>LoRA scored 0.293 AUPRC on pooled OOD [CI 0.286, 0.301] versus 0.364 [0.354, 0.375] for the frozen probe and 0.291 [0.283, 0.298] for TF-IDF + LR. The pooled OOD AUPRC random floor is 0.374; all four detectors land at or below floor.</p>
<p>The sharper result is under AUROC: LoRA’s pooled OOD AUROC is 0.383 [0.374, 0.392] and TF-IDF + LR’s is 0.371 [0.362, 0.381], both with confidence intervals that clear the 0.5 AUROC random floor <em>on the wrong side</em>. The frozen probe alone stays above the AUROC floor at 0.515 [0.505, 0.525]. The in-pool to cross-family generalization gap for the trained detectors is approximately 0.6 AUROC (in-pool 0.99 → cross-family 0.38), the largest possible gap with statistical confidence.</p>
<p>The mechanism is interpreted in §5 Discussion.</p>
</section>
<section id="context-window-ablation-produced-a-null-result" class="level3">
<h3 class="anchored" data-anchor-id="context-window-ablation-produced-a-null-result">§4.4 Context-window ablation produced a null result</h3>
<p>A controlled ablation per ADR-060 trained DeBERTa-v3-base (512-token native context window) against ModernBERT (8192-token native window) under two truncation strategies: chunk-and-average (compute the classifier output on overlapping 512-token windows and average) and head-truncation (use only the first 512 tokens).</p>
<p>Result: DeBERTa-v3-base with chunk-and-average scored 0.291 pooled OOD AUPRC; head-truncation scored 0.290. Neither significantly differs from each other or from the ModernBERT-LoRA result (0.293). The ModernBERT advantage observed in §4.1 is therefore best interpreted as backbone-dominant, not context-window-dominant.</p>
<p>Details in <a href="./WRITEUP/model-rungs.html">WRITEUP/model-rungs.md §4</a> and <a href="./decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html">ADR-063</a>.</p>
</section>
<section id="published-detector-versions-are-slice-dependent" class="level3">
<h3 class="anchored" data-anchor-id="published-detector-versions-are-slice-dependent">§4.5 Published detector versions are slice-dependent</h3>
<p>ProtectAI v2 improves over v1 on JBB-Behaviors (AUPRC 0.556 vs 0.519) but regresses on XSTest (0.382 vs 0.469) and on pooled OOD overall (0.314 vs 0.361). The “newer is better” assumption does not hold across the full slate.</p>
<p>Practical implication: detector updates should be evaluated against the actual slice mix that matters for the deployment, not on a single aggregate metric.</p>
<p>Cross-version comparisons in <a href="./RESULTS.html#secondary-table-auroc">RESULTS.md §6 Secondary Table: AUROC</a>.</p>
</section>
<section id="validation-thresholds-are-fragile-under-cross-family-shift" class="level3">
<h3 class="anchored" data-anchor-id="validation-thresholds-are-fragile-under-cross-family-shift">§4.6 Validation thresholds are fragile under cross-family shift</h3>
<p>The detection policy (FPR ≤ 1% on validation, maximize recall) was fit per (fold, seed) on validation data and applied to held-out test data. Mean test FPR by detector:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Detector</th>
<th style="text-align: right;">Mean test FPR</th>
<th style="text-align: right;">Mean test recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TF-IDF + LR</td>
<td style="text-align: right;">6.7%</td>
<td style="text-align: right;">33.3%</td>
</tr>
<tr class="even">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">11.5%</td>
<td style="text-align: right;">42.4%</td>
</tr>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;">1.0%</td>
<td style="text-align: right;">6.3%</td>
</tr>
</tbody>
</table>
<p>The 1% FPR validation target holds only for the frozen probe (1.0% on test, within sampling noise of the 1% target). The trained detectors significantly exceed it (LoRA 11.5%, TF-IDF + LR 6.7% against a 1% target). The frozen probe holds the FPR target but catches only 6.3% of positives, indicating a non-deployable operating point under this policy framing. All numbers verified by re-derivation from <code>evals/operating_points/dual_policy.parquet</code> via <code>scripts/audit_numbers.py</code>.</p>
<p>Threshold-transfer behavior in <a href="./WRITEUP/threshold-policy.html">WRITEUP/threshold-policy.md</a>.</p>
</section>
<section id="calibration-favors-the-frozen-probe" class="level3">
<h3 class="anchored" data-anchor-id="calibration-favors-the-frozen-probe">§4.7 Calibration favors the frozen probe</h3>
<p>Among the four detectors with both-class OOD scores, the frozen probe has the lowest expected calibration error (ECE) and lowest Brier score on the pooled OOD slate. Mean ECE: 0.144 (frozen probe), higher for LoRA and TF-IDF + LR. Mean Brier: 0.265 (frozen probe).</p>
<p>LoRA worsens calibration relative to the frozen probe while simultaneously fitting the direct training pool, reinforcing the §4.1-§4.3 conclusion that direct-pattern learning and cross-family score behavior are distinct capabilities.</p>
<p>Full calibration battery in <a href="./RESULTS.html#calibration">RESULTS.md §5 Calibration</a> and <a href="./docs/plots/F5.svg">Figure F5 calibration comparison</a>.</p>
<hr>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">§5. Discussion</h2>
<section id="mechanism-lexical-overfitting-plus-label-relevance-shift" class="level3">
<h3 class="anchored" data-anchor-id="mechanism-lexical-overfitting-plus-label-relevance-shift">§5.1 Mechanism: lexical overfitting plus label-relevance shift</h3>
<p>A pooled OOD AUROC below 0.5 with confidence intervals that clear 0.5 on the wrong side is not consistent with pure overfitting [§GLOSSARY]. Pure overfitting predicts collapse <em>toward</em> random performance, not past it. The observed below-floor performance requires a more specific mechanism.</p>
<p>The interpretation consistent with the slate composition is <strong>lexical overfitting combined with a label-relevance shift on the OOD slate</strong>. Both LoRA and TF-IDF + LR appear to learn lexical signatures of direct prompt injection (“ignore previous instructions”, imperative override commands, role-redirection phrases). On the OOD slate, this lexical signal is <em>anti-correlated</em> with the true attack class:</p>
<ul>
<li><strong>NotInject</strong> (n=339, all negative): benign text engineered to resemble direct injection. Detectors score these HIGH (false positives), inverting the negative class.</li>
<li><strong>BIPIA and InjecAgent</strong> (indirect + agentic, n=112 positive): real attacks that do not use direct-injection lexical patterns. Detectors score these LOW (false negatives), inverting the positive class.</li>
</ul>
<p>The lexical signal is real and internally consistent within itself — it just stops tracking attack class on cross-family slices where the lexical similarity to direct injection and the actual attack class point in opposite directions. The frozen probe (zero LODO-pool adaptation) preserves generic linguistic features that are less aligned with the direct-injection lexical distribution and therefore stay closer to random performance on the cross-family slate.</p>
<p>The in-pool → cross-family generalization gap is approximately 0.6 AUROC for the trained detectors (in-pool 0.99 → cross-family 0.38) versus approximately 0.4 for the frozen probe (in-pool 0.91 → cross-family 0.515). The more training adapted to the LODO pool, the sharper the cross-family fall.</p>
</section>
<section id="implications-for-direct-detection-deployments" class="level3">
<h3 class="anchored" data-anchor-id="implications-for-direct-detection-deployments">§5.2 Implications for direct-detection deployments</h3>
<p>The result cautions against deploying classifiers trained on direct-injection corpora as general-purpose prompt-injection detectors in mixed-family threat models. Specifically:</p>
<ul>
<li>Direct-detection accuracy on in-pool data does not predict cross-family generalization.</li>
<li>AUROC below 0.5 is an active failure mode (mis-ranking) rather than a benign degradation toward random.</li>
<li>False-positive rates measured on validation data do not hold on held-out test sources (§4.6).</li>
<li>“Newer version is better” does not hold across mixed slates (§4.5).</li>
</ul>
<p>Deployment-context evaluations should test the specific slice mix that matters for the production threat model, not aggregate direct-injection metrics.</p>
</section>
<section id="what-this-study-does-not-establish" class="level3">
<h3 class="anchored" data-anchor-id="what-this-study-does-not-establish">§5.3 What this study does not establish</h3>
<p>The negative result on cross-family transfer does not establish that:</p>
<ul>
<li>A different training pool (with cross-family coverage) would fail similarly.</li>
<li>A larger or different backbone would fail similarly.</li>
<li>The cross-family failure is fundamental rather than addressable with OOD-aware training.</li>
</ul>
<p>Specifically, this study did not test: cross-family training data, non-Transformer architectures, ensemble methods, threshold-policy adaptations to held-out source FPR statistics, or multi-detector voting. Several of these are documented in §6 Limitations as future work directions.</p>
<hr>
</section>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">§6. Limitations</h2>
<section id="scope-of-the-classifier" class="level3">
<h3 class="anchored" data-anchor-id="scope-of-the-classifier">§6.1 Scope of the classifier</h3>
<p>The evaluated classifier is single-turn English text classification. Out of scope (per ADR-014): - Multilingual attacks - Encoded payloads (base64, leetspeak, Unicode confusables) - Paraphrase robustness - Adversarial perturbations - Full multi-turn system behavior - Deployment threshold recommendations</p>
<p>The InjecAgent slice is included in the OOD slate to quantify the gap for agentic-flow attacks, not to claim that a single-turn classifier should solve that problem.</p>
</section>
<section id="reference-scorer-contamination" class="level3">
<h3 class="anchored" data-anchor-id="reference-scorer-contamination">§6.2 Reference scorer contamination</h3>
<p>ProtectAI v1 and v2 are trained on at least 2 of 4 LODO training-pool sources (deepset/prompt-injections, Lakera/gandalf_ignore_instructions) per EVIDENCE §1-2. Their pooled OOD scores on slices that overlap with their training pool are not clean OOD baselines and are reported with <code>suspected_contamination</code> annotations per ADR-005 three-state contamination taxonomy. ProtectAI scores serve as diagnostic references with documented caveats, not as competitive benchmarks.</p>
</section>
<section id="full-fine-tune-incomplete-experiment-status" class="level3">
<h3 class="anchored" data-anchor-id="full-fine-tune-incomplete-experiment-status">§6.3 Full-fine-tune incomplete-experiment status</h3>
<p>ModernBERT full fine-tune was trained for LODO direct-source inference (24 Phase 2 prediction parquets persisted) but pooled OOD inference was not run due to a Phase 5 X11 file-system crash on the RunPod /workspace FUSE mount. The methodological framing of this forced drop is documented in ADR-052 and ADR-075. The full-FT row appears in the LODO direct-source recall table (§4.1) but is absent from the pooled OOD AUPRC table; this is explicit and asterisk-marked on all reporting surfaces. Re-running the full-FT pooled OOD inference on a fresh DC is documented in NEXT_STEPS §2.2 as future work.</p>
</section>
<section id="single-seed-headline-second-seed-stability-check" class="level3">
<h3 class="anchored" data-anchor-id="single-seed-headline-second-seed-stability-check">§6.4 Single-seed headline + second-seed stability check</h3>
<p>Headline metrics are reported at seed=1. A seed=2 stability check is run on the same evaluation slate; results agree within the reported confidence intervals. A larger multi-seed × multi-fold replication study is documented in NEXT_STEPS §2.1 as future work (estimated ~$10-50 GPU spend; portfolio-repo scope per [[portfolio_plan_approved]]).</p>
</section>
<section id="mechanism-interpretation-is-not-empirically-demonstrated" class="level3">
<h3 class="anchored" data-anchor-id="mechanism-interpretation-is-not-empirically-demonstrated">§6.5 Mechanism interpretation is not empirically demonstrated</h3>
<p>The §5.1 mechanism interpretation (lexical overfitting + label- relevance shift) is consistent with the aggregate AUROC and slate composition but is not directly demonstrated in this artifact. A per-prediction analysis comparing detector scores on lexically-direct vs lexically-indirect OOD examples would empirically test the hypothesis. The per-row prediction parquets at <code>evals/predictions/&lt;rung&gt;__fold&lt;F&gt;__seed&lt;S&gt;__&lt;source&gt;.parquet</code> support this analysis; it is documented in NEXT_STEPS §3 as future work (portfolio-repo scope).</p>
</section>
<section id="threshold-policy-framing" class="level3">
<h3 class="anchored" data-anchor-id="threshold-policy-framing">§6.6 Threshold policy framing</h3>
<p>The detection policy (FPR ≤ 1%, maximize recall) was chosen as a methodological policy for evaluation characterization, not as a deployment recommendation. Production deployment thresholds depend on the deployment cost ratio and operating environment, which this study does not address. The verification policy (recall ≥ 99%, minimize FPR) similarly serves characterization purposes only.</p>
<p>Full limitations narrative in <a href="./WRITEUP/limitations-and-future-work.html">WRITEUP/limitations-and-future-work.md</a>.</p>
<hr>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">§7. Conclusion</h2>
<p>This study evaluated a detector ladder for prompt-injection classification under cross-family distribution shift, finding that direct-prompt-injection detection is learnable cheaply (TF-IDF + LR reaches 0.974 AUPRC on direct+benign validation) but does not generalize to cross-family attacks (best pooled OOD AUPRC is 0.364 against a random floor of 0.374; trained adapters score below the 0.5 AUROC floor with confidence intervals that clear 0.5 on the wrong side). The cross-family failure is interpreted as lexical overfitting combined with a label-relevance shift on the OOD slate.</p>
<p>The contribution is the negative result on cross-family transfer plus the honest evaluation harness that produced it, not a deployment-ready classifier. Future work directions include OOD-aware training data, stronger backbone comparisons under matched training budgets, threshold-policy adaptations to held-out FPR statistics, and per-prediction empirical validation of the proposed mechanism.</p>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">§8. References</h2>
<section id="decisions-architecture-decision-records" class="level3">
<h3 class="anchored" data-anchor-id="decisions-architecture-decision-records">Decisions (Architecture Decision Records)</h3>
<p>Selected key ADRs cited in this paper; full list at <a href="./decisions/">decisions/</a>:</p>
<ul>
<li><strong>ADR-005</strong> — Methodology principles (incl.&nbsp;three-state contamination taxonomy)</li>
<li><strong>ADR-014</strong> — Threat model bundle (out-of-scope enumeration)</li>
<li><strong>ADR-016</strong> — Data design bundle (LODO splits + deduplication)</li>
<li><strong>ADR-017</strong> — Trained rung slate expansion (TF-IDF + LR baseline)</li>
<li><strong>ADR-018</strong> — Reference-scorer slate + contamination stratification</li>
<li><strong>ADR-019</strong> — LoRA + Transformer training recipe</li>
<li><strong>ADR-021</strong> — Eval-slate aggregation + recall@FPR pinpoints</li>
<li><strong>ADR-022</strong> — Statistical inference apparatus (bootstrap + paired-comparison protocols)</li>
<li><strong>ADR-023</strong> — Calibration battery (ECE, Brier, reliability)</li>
<li><strong>ADR-024</strong> — Cross-fold CI methodology (Bayle 2020)</li>
<li><strong>ADR-025</strong> — Dual-policy threshold characterization</li>
<li><strong>ADR-050</strong> — Rung-slate narrowing + LLM-judge cost-drop + full-FT OOD forced-drop (Revision 1 + Revision 2)</li>
<li><strong>ADR-052</strong> — Full-FT OOD drop methodological reframing of ADR-050 R2</li>
<li><strong>ADR-060</strong> — DeBERTa-v3-base long-context ablation methodology</li>
<li><strong>ADR-063</strong> — DeBERTa ablation v1.1.2 execution + slot shift</li>
<li><strong>ADR-075</strong> — Full-FT OOD drop rationale unified narrative</li>
</ul>
</section>
<section id="external-references" class="level3">
<h3 class="anchored" data-anchor-id="external-references">External references</h3>
<ul>
<li><strong>ModernBERT</strong>: Warner et al.&nbsp;2024, <a href="https://arxiv.org/abs/2412.13663">arXiv:2412.13663</a>.</li>
<li><strong>LoRA</strong>: Hu et al.&nbsp;2021, <a href="https://arxiv.org/abs/2106.09685">arXiv:2106.09685</a>.</li>
<li><strong>BIPIA</strong> (indirect prompt injection benchmark): Wang et al.&nbsp;2023, <a href="https://huggingface.co/datasets/Bochum-NLP/bipia">Hugging Face: Bochum-NLP/bipia</a>.</li>
<li><strong>InjecAgent</strong> (agentic-flow prompt injection): Yu et al.&nbsp;2024, <a href="https://arxiv.org/abs/2403.02691">arXiv:2403.02691</a>.</li>
<li><strong>JBB-Behaviors</strong> (JailbreakBench): Chao et al.&nbsp;2024, <a href="https://huggingface.co/datasets/JailbreakBench/JBB-Behaviors">Hugging Face: JailbreakBench/JBB-Behaviors</a>.</li>
<li><strong>XSTest</strong> (jailbreak-safe-question discrimination): Röttger et al. 2024, <a href="https://arxiv.org/abs/2308.01263">arXiv:2308.01263</a>.</li>
<li><strong>NotInject</strong> (false-positive robustness): Datta et al.&nbsp;2024, <a href="https://huggingface.co/datasets/dattaroh/NotInject">Hugging Face: dattaroh/NotInject</a>.</li>
<li><strong>HackAPrompt</strong> corpus: Schulhoff et al.&nbsp;2023, <a href="https://arxiv.org/abs/2311.16119">arXiv:2311.16119</a>.</li>
<li><strong>Bayle 2020</strong> (cross-fold CI methodology): Bayle et al.&nbsp;2020, <a href="https://arxiv.org/abs/2007.02780">arXiv:2007.02780</a>.</li>
<li><strong>BCa bootstrap</strong>: Efron 1987, <a href="https://doi.org/10.2307/2289144">doi:10.2307/2289144</a>.</li>
</ul>
</section>
<section id="project-artifacts" class="level3">
<h3 class="anchored" data-anchor-id="project-artifacts">Project artifacts</h3>
<ul>
<li><strong>Source code</strong>: <a href="https://github.com/brandon-behring/prompt-injection-detection-prototype">github.com/brandon-behring/prompt-injection-detection-prototype</a></li>
<li><strong>HF Hub checkpoints</strong>: <a href="https://huggingface.co/BBehring/prompt-injection-frozen-probe">BBehring/prompt-injection-frozen-probe</a>, <a href="https://huggingface.co/BBehring/prompt-injection-lora">BBehring/prompt-injection-lora</a></li>
<li><strong>Evaluation library</strong>: <a href="https://github.com/brandon-behring/eval-toolkit">eval-toolkit</a> (v0.47.0 pinned)</li>
<li><strong>Cloud orchestration</strong>: <a href="https://github.com/brandon-behring/runpod-deploy">runpod-deploy</a> (v0.8.4 pinned)</li>
<li><strong>Live rendered site</strong>: <a href="https://brandon-behring.github.io/prompt-injection-detection-prototype/">brandon-behring.github.io/prompt-injection-detection-prototype/</a></li>
</ul>
<hr>
</section>
</section>
<section id="glossary" class="level2">
<h2 class="anchored" data-anchor-id="glossary">Glossary</h2>
<p>Definitions for technical terms used in this paper. Full glossary at <a href="./docs/GLOSSARY.html">docs/GLOSSARY.md</a>.</p>
<ul>
<li><strong>AUPRC</strong> — Area Under the Precision-Recall Curve. Primary ranking metric for imbalanced binary classification; random floor equals the positive rate.</li>
<li><strong>AUROC</strong> — Area Under the Receiver Operating Characteristic curve. Secondary diagnostic metric with 0.5 random floor; less informative than AUPRC under imbalance.</li>
<li><strong>BCa bootstrap</strong> — Bias-Corrected and Accelerated bootstrap; produces confidence intervals robust to skewness and bias in the resampling distribution.</li>
<li><strong>Block-bootstrap-on-folds</strong> — bootstrap that resamples entire folds rather than individual rows; respects fold-level exchangeability assumptions.</li>
<li><strong>cv_clt</strong> — Cross-validation Central Limit Theorem confidence interval per Bayle 2020 Theorem 3.1; suitable for per-fold metric vectors under exchangeability.</li>
<li><strong>ECE</strong> — Expected Calibration Error; lower is better.</li>
<li><strong>Frozen probe</strong> — linear classifier on top of a frozen pretrained backbone representation; tests what the backbone already encodes without LODO-pool adaptation.</li>
<li><strong>LODO</strong> — Leave-One-Dataset-Out splitting discipline; holds one source out of training while training on the remainder.</li>
<li><strong>LoRA</strong> — Low-Rank Adapters; parameter-efficient fine-tuning method that updates only a small set of adapter weights.</li>
<li><strong>OOD</strong> — Out-of-distribution. In this study specifically means cross-family, not source-level.</li>
<li><strong>Overfitting (vs label-relevance shift)</strong> — pure overfitting predicts collapse toward random performance. Below-floor performance indicates an additional mechanism: a label-relevance shift in which the learned signal is anti-correlated with the true label on the OOD slate.</li>
<li><strong>Paired-bootstrap-on-folds</strong> — bootstrap-based paired comparison of two detectors evaluated on the same (fold, seed) cells.</li>
</ul>
<hr>
<p><em>End of paper. For the same content in narrative form, see <a href="./WRITEUP_NARRATIVE.html">WRITEUP_NARRATIVE.md</a>.</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>