<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Plain-English story-arc article presenting the project’s methodology and findings.">

<title>Prompt-Injection Classification: Methodology and Capability Characterization (Narrative Format) – Prompt-injection classifier evaluation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6417478169390d5200ae675d66b5a4f4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Prompt-injection classifier evaluation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./RESULTS.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="./WRITEUP_PAPER.html">
 <span class="dropdown-text">Academic paper (IMRAD)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP_NARRATIVE.html">
 <span class="dropdown-text">Narrative arc (story)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP.html">
 <span class="dropdown-text">Router (pick a guide)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./READING_GUIDE.html">
 <span class="dropdown-text">Reading guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/data-decisions.html">
 <span class="dropdown-text">Data decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/model-rungs.html">
 <span class="dropdown-text">Model details</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/eval-design.html">
 <span class="dropdown-text">Evaluation design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/threshold-policy.html">
 <span class="dropdown-text">Threshold policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reference-scorer-audit.html">
 <span class="dropdown-text">Reference-scorer audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/methodology-guarantees.html">
 <span class="dropdown-text">Methodology guarantees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/limitations-and-future-work.html">
 <span class="dropdown-text">Limitations and future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reproducibility.html">
 <span class="dropdown-text">Reproducibility — three reproduction tiers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./decisions/README.html"> 
<span class="menu-text">Decisions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reference">    
        <li>
    <a class="dropdown-item" href="./docs/for-hiring-managers.html">
 <span class="dropdown-text">Project at a glance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./docs/site-reader-map.html">
 <span class="dropdown-text">Public site reader map</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EVIDENCE.html">
 <span class="dropdown-text">Evidence ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SPEC_SHEET.html">
 <span class="dropdown-text">Spec lock sheet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SUBMISSION_AUDIT.html">
 <span class="dropdown-text">Submission audit ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NEXT_STEPS.html">
 <span class="dropdown-text">Carryforward + future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions registry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/01_canonical_results.html">
 <span class="dropdown-text">Notebook: canonical results</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/02_frozen_vs_lora.html">
 <span class="dropdown-text">Notebook: frozen vs LoRA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/03_calibration.html">
 <span class="dropdown-text">Notebook: calibration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./notebooks/04_ood_slate.html">
 <span class="dropdown-text">Notebook: OOD slate</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/brandon-behring/prompt-injection-detection-prototype" target="_blank"> 
<span class="menu-text">Repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./WRITEUP_PAPER.html">Methodology guides (pick a style)</a></li><li class="breadcrumb-item"><a href="./WRITEUP_NARRATIVE.html">Narrative arc (story)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Entry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Landing page (results + meaning)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">README + executive summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RESULTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Results: tables, figures, and source artifacts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology guides (pick a style)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP_PAPER.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Academic paper (IMRAD)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP_NARRATIVE.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Narrative arc (story)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Router (1-page chooser)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./READING_GUIDE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading guide</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Detailed spokes (8 topics)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/data-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/model-rungs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/eval-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/threshold-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threshold policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reference-scorer-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/limitations-and-future-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Limitations and future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility — three reproduction tiers</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/01_canonical_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 — Canonical results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/02_frozen_vs_lora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/03_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 — Calibration battery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notebooks/04_ood_slate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 — OOD slate gap visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence + audit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EVIDENCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evidence ledger</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./docs/site-reader-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Public site reader map</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SPEC_SHEET.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spec lock sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SUBMISSION_AUDIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission audit ledger</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./NEXT_STEPS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carryforward + future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions registry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions (ADRs)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architecture Decision Records (ADRs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/upstream_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Upstream issues filed during this iteration</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-001-submission-deadline-and-scope-ambition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission deadline 2026-05-18 morning with infra-leveraged Long-scope attempt and fallback ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-002-deliverable-format-pdf-and-repo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — focused PDF plus public GitHub repo as evidence locker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-003-repo-visibility-public.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repository visibility — public from start (kit default ratified)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-004-reviewer-profile-and-hub-and-spoke-writeup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer profile A1+A2 with hub-and-spoke writeup structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-005-methodology-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-level methodology principles — methodology over metrics, honest evaluation preferred, structured limitations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-006-headline-metrics-and-statistical-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Headline metrics, operating-point pinpoints, and statistical apparatus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-007-rung-architecture-and-reference-scorers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology rung architecture — trained backbones, LLM-judge reference rungs, Cohen’s kappa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-008-data-scope-public-only-hybrid-splits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data scope — public-only sources, hybrid splits, NotInject inclusion (brief-level lock)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-009-process-mandates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Process mandates — two-tier reproducibility, marker-based testing, compute disclosure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-010-scope-limits-with-extension-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scope limits with per-bound extension conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-011-methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees — eight banned approaches surfaced as project commitments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-012-soft-signals-and-artifact-engagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Soft-signals naming discipline and external artifact engagement set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-013-kit-ratify-bulk-strictness-intake-notebook-persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kit-ratify bulk — Phase 0 strictness, brief-intake protocol, notebook role and RunPod persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-014-threat-model-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threat-model bundle — attack-class scope, language, length cap, truncation policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-015-rung-architecture-refinement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung architecture refinement — ModernBERT-base only trained slate, supersedes ADR-007</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-016-data-design-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data design bundle — source slate, splits, HF pinning, dedup, ordering, ceilings, ref-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-017-trained-rung-slate-expansion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trained-rung-slate expansion — TF-IDF plus LR classical floor and frozen-probe dual role</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-018-reference-scorer-slate-and-contamination-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference scorer slate and contamination stratification — OpenAI plus Anthropic LLM-judges plus ProtectAI v1 and v2 plus per-axis matched-budget</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-019-lora-and-transformer-training-recipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA and transformer-rung training recipe — hyperparameters, epochs, precision, class weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-020-compute-infrastructure-and-cost-discipline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute infrastructure and cost discipline — runpod-deploy 0.7.7 primitives, GPU failover, adaptive batch sizing, dual-layer cost tracking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-021-eval-slate-aggregation-and-recall-fpr-pinpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eval slate aggregation — pooled headline plus per-slice spoke and recall@FPR pinpoint feasibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-022-statistical-inference-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference apparatus — bootstrap N + stability check, multi-comparison stance, multi-seed protocol, paired-test method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-023-calibration-battery-and-interventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery composition — raw plus temperature plus isotonic interventions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-024-cross-fold-ci-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-fold CI methodology — cv_clt_ci (Bayle 2020) headline plus block-bootstrap-on-folds spoke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-025-dual-policy-threshold-characterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dual-policy threshold characterization at symmetric 1% cost weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-026-module-layout-concern-grouped-subpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module layout — concern-grouped sub-packages under src/</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-027-smoke-vs-canonical-execution-context-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Smoke vs canonical separation — three Makefile targets stratified by execution context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-028-coverage-floor-70pct-with-upstream-issue-filing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test coverage floor — 70% flat with co-locked upstream-issue-filing discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-029-test-marker-strategy-four-marker-ratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test marker strategy — ratify 4-marker stratification (unit / smoke / integration / network)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-030-deliverable-format-quarto-html-site.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — repo-only with Quarto-rendered HTML site via GitHub Actions (supersedes ADR-002)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-031-reviewer-reading-paths-quarto-site-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer reading paths — index.qmd entry-point with Quarto sidebar nav (supersedes ADR-004)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-032-hf-hub-publication-headline-rungs-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HF Hub checkpoint publication — publish primary headline rungs only with model card discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-033-github-release-strategy-rehearsal-plus-submission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitHub release strategy — rehearsal tag plus SemVer submission tag plus post-submission patches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-034-reproducibility-tier-full-ladder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility tier — full ladder T0 (eval-from-hub) plus T1 (smoke) plus T3 (headline-cloud)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-035-secrets-management-three-store-split.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secrets management — three-store split aligned with execution context (.env + RunPod pod-secrets + GH Actions repo Secrets)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-036-library-version-pins-tag-pin-plus-freeze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library version pins — tag pin to latest stable plus freeze for submission window (eval-toolkit v0.31.0 + runpod-deploy v0.7.7 + research_toolkit v1.9.1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-037-python-version-pin-3-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python version pin — ratify requires-python &gt;=3.13 (matches existing .python-version + bc8ce4e commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-038-phase-tailoring-light-roadmap-edits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase tailoring — light ROADMAP edits to Phase 4 close + Phase 5 description (preserves 5-phase structure)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-039-acceptance-criteria-six-gate-integration-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-specific acceptance criteria — 6-gate integration checklist for v1.0.0 submission tag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-040-phase-0-audit-findings-and-assumption-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 0 final audit findings + 7-assumption backfill (A-010 through A-016)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-041-phase-1-data-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 (Data) implementation bundle — manifest schema, SHA pinning, validator placement, loader arch, holdout sourcing, contamination corpus, output materialization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-042-llm-prelabel-dedup-holdout-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-judge pre-label as Q5 holdout-labeling bootstrap with human override</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-043-post-split-cross-source-leakage-cleanup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-split cross-source leakage cleanup — drop train+val rows that exact-match or cosine-near-match test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-044-phase-2-training-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 training implementation bundle — seed slate reconciliation + manifest move + classical-floor location + YAML config schema + trainer split + per-rung orchestration + fixture preflight</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-045-phase-3-evaluation-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 evaluation implementation bundle — scoring-first contract + 6-commit cadence + tiered reference scorers + classical-scaffold + full-pairwise persistence with headline-only WRITEUP + pydantic schema validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-046-phase-4-analysis-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 analysis implementation bundle — 6-commit cadence + scaffold-with-classical + always-emit-both-CIs auto-flag + MDE-on-every-emitted-CI + LLM-rater audit included (user-overridden from defer) + library-first hybrid figures + Phase 5 prep deferred</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-047-phase-1-library-first-carryforward-refactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 library-first carryforward refactor — audit findings + remediation plan (splits + dedup + leakage_report + contamination_scan migration to eval-toolkit primitives; orphaned code removed in-commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-048-llm-rater-reference-scorer-audit-protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-rater reference-scorer audit protocol — disagreement-with-LoRA baseline + stratified (5 OOD slices × 3 contamination_states) sampling + fixed 2-axis rubric + inter-rater gpt-4o-plus-claude-sonnet + dry-run-then-single-approval cost UX</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-049-gpu-order-priority-refresh-a100-80g.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPU failover ladder priority refresh — A100-SXM4-80GB to position 1 + US-WA-1/US-CA-2 datacenter additions + EU-RO-1 drop (frozen-probe + LoRA canonical; full-FT deferred to post-rehearsal)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-050-rung-slate-narrowing-llm-judges-and-full-ft-ood-dropped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung slate narrowing — LLM judges dropped (cost) + full-FT OOD dropped (FUSE EIO crash); narrow supersession of ADR-018 reference slate + ADR-021 OOD comparison scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-051-v1.0.x-carryforward-of-t0-and-invariant-scaffolds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">v1.0.x carryforward of ADR-034 T0 score-match wiring + ADR-039 gate-3 invariant-scaffold unskip; narrow supersession with explicit v1.1.x landing condition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-052-full-ft-ood-drop-methodological-reframing-of-adr-050-r2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full-FT OOD inference drop — methodological reframing; narrow supersession of ADR-050 Revision 2 (FUSE-crash-only framing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-053-reading-guide-governance-and-newcomer-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading-guide governance + newcomer onboarding paths — two entry artifacts + 3 reading paths + Headline-finding-block + interpretation pedagogy + pointer convention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-054-results-page-as-third-entry-artifact-extending-adr-053.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RESULTS.md as third entry artifact — narrow supersession of ADR-053 dimension 1 (two-entry-artifacts); dimensions 2-5 unchanged</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-055-eval-toolkit-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">eval-toolkit installs from PyPI (not git+https) at v0.40.0+ — narrow supersession of ADR-036 “git URL is the only viable spec format”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-056-binary-calibrator-refactor-and-platt-beta-narrow-supersession-of-adr-023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery refactor to eval-toolkit <code>_binary</code> API + Platt + Beta calibrators landed — narrow supersession of ADR-023 “temperature + isotonic only” scope deferral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-057-manifest-schema-v3-backfill-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Per-prediction provenance manifests via scripts/backfill_provenance.py — schema, location, naming, idempotency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-058-eval-from-hub-non-dry-run-body-narrow-supersession-of-adr-051-block-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">scripts/eval_from_hub.py non-dry-run body wired — narrow supersession of ADR-051 Block A (T0 score-match carryforward); Block B (38 invariant scaffolds) remains carryforward</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-059-runpod-deploy-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">runpod-deploy installs from PyPI (not git+https) at v0.8.4+ — narrow supersession of ADR-036 “git URL is the only viable spec format” sub-claim for runpod-deploy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation methodology — chunk-and-average vs head-truncation × 5-slice OOD; infrastructure-only at v1.1.0; execution deferred to v1.1.1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-061-quarto-site-navigation-restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto site navigation restructure — landing-page rebuild + navbar consolidation + sidebar hub-spoke nesting (narrow supersession of ADR-053 navigation contract)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-062-quarto-writeup-clarity-and-canonical-figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto writeup clarity rewrite and canonical reviewer figure slate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation execution (v1.1.2 carryforward; narrow renaming-only supersession of ADR-060 “v1.1.1” body references) — null result, backbone-dominant interpretation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-064-writeup-hiring-manager-clarity-and-consistency-pass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup hiring-manager clarity polish + documentation-wide consistency conventions — additive layer on top of ADR-062</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup accuracy-audit methodology + Quarto callout-note convention + narrative invariants — additive layer on top of ADR-064</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-066-library-first-carryforward-refactor-v1-2-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library-first carryforward refactor v1.2.2 — consume 7 closed eval-toolkit primitives across 6 sites</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for factual-typo fixes in cross-reference slug filenames</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-069-immutability-narrow-relaxation-for-publisher-url-to-doi-canonicalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for academic publisher-URL → DOI canonicalization in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-070-quarto-render-only-markdown-corrections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for render-only Markdown corrections in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-071-adr-cross-reference-slug-sweep-closure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Execute the slug-sweep authorized by ADR-067 + ADR-068 + ADR-069 that was never actually completed in any prior commit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-072-adr-051-052-frontmatter-and-structural-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill missing frontmatter fields + Alternatives sections + Status headings for ADR-051 + ADR-052 per ADR-067-style narrow-relaxation discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-073-adr-immutability-rule-consolidated-re-statement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collapse the four-ADR narrow-relaxation chain (ADR-067/068/069/070) into a single consolidated immutability rule with four named exception classes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-074-adr-064-self-criticism-quote-redaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Replace verbatim self-criticism quote in ADR-064 frontmatter claim + body context with a neutral paraphrase preserving the decision</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-075-full-ft-ood-drop-rationale-unified-narrative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unify the ADR-050 Revision 2 (FUSE-crash-forced-drop) and ADR-052 (methodology-load-bearing-with-crash-as-trigger) framings into a single account</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-076-superseded-by-and-closing-commit-frontmatter-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill superseded_by on ADR-046 + ADR-054 + ADR-061 (→ ADR-062) + closing_commit on ADR-071-075 per ADR-072 frontmatter-backfill discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-077-supersession-backlink-and-frontmatter-octal-quoting-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill supersession back-links + quote octal-risk YAML integer fields in ADR-007 + ADR-015 + ADR-018 + ADR-021 + ADR-052 frontmatter per ADR-076 frontmatter-backfill discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-078-executive-summary-absorbed-into-readme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Absorb EXECUTIVE_SUMMARY content into README; retire EXECUTIVE_SUMMARY.md as standalone file</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-079-two-guide-reader-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-080-reviewer-url-pin-numeric-correction-adr-078-079.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correct reviewer URL pin numeric defect in ADR-078 + ADR-079 (tree/v1.2.8 → tree/v1.0.0); axis-only supersession on the reviewer-URL-pin axis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-081-frontmatter-status-field-split-narrow-relaxation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authorize frontmatter <code>status:</code> field split (verbose-context → pure-Nygard <code>status:</code> + new <code>lifecycle-note:</code>) as an extension of the ADR-072 / ADR-076 / ADR-077 frontmatter-backfill narrow-relaxation discipline; apply to ADR-060 as the seed case</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#act-0-hook" id="toc-act-0-hook" class="nav-link active" data-scroll-target="#act-0-hook">Act 0 — Hook</a></li>
  <li><a href="#act-1-setup" id="toc-act-1-setup" class="nav-link" data-scroll-target="#act-1-setup">Act 1 — Setup</a>
  <ul class="collapse">
  <li><a href="#the-question" id="toc-the-question" class="nav-link" data-scroll-target="#the-question">The question</a></li>
  <li><a href="#the-threat-model-context" id="toc-the-threat-model-context" class="nav-link" data-scroll-target="#the-threat-model-context">The threat-model context</a></li>
  <li><a href="#what-we-did-not-try-to-do" id="toc-what-we-did-not-try-to-do" class="nav-link" data-scroll-target="#what-we-did-not-try-to-do">What we did not try to do</a></li>
  </ul></li>
  <li><a href="#act-2-investigation" id="toc-act-2-investigation" class="nav-link" data-scroll-target="#act-2-investigation">Act 2 — Investigation</a>
  <ul class="collapse">
  <li><a href="#building-the-evaluation-harness" id="toc-building-the-evaluation-harness" class="nav-link" data-scroll-target="#building-the-evaluation-harness">Building the evaluation harness</a></li>
  <li><a href="#the-detector-ladder" id="toc-the-detector-ladder" class="nav-link" data-scroll-target="#the-detector-ladder">The detector ladder</a></li>
  <li><a href="#statistical-discipline" id="toc-statistical-discipline" class="nav-link" data-scroll-target="#statistical-discipline">Statistical discipline</a></li>
  </ul></li>
  <li><a href="#act-3-revelation" id="toc-act-3-revelation" class="nav-link" data-scroll-target="#act-3-revelation">Act 3 — Revelation</a>
  <ul class="collapse">
  <li><a href="#finding-1-direct-detection-was-learned" id="toc-finding-1-direct-detection-was-learned" class="nav-link" data-scroll-target="#finding-1-direct-detection-was-learned">Finding 1 — Direct detection was learned</a></li>
  <li><a href="#finding-2-the-ood-wall-is-cross-family-not-source-level" id="toc-finding-2-the-ood-wall-is-cross-family-not-source-level" class="nav-link" data-scroll-target="#finding-2-the-ood-wall-is-cross-family-not-source-level">Finding 2 — The OOD wall is cross-family, not source-level</a></li>
  <li><a href="#finding-3-the-headline-anti-correlation" id="toc-finding-3-the-headline-anti-correlation" class="nav-link" data-scroll-target="#finding-3-the-headline-anti-correlation">Finding 3 — The headline anti-correlation</a></li>
  <li><a href="#finding-3-sharper-form-anti-correlation-under-auroc" id="toc-finding-3-sharper-form-anti-correlation-under-auroc" class="nav-link" data-scroll-target="#finding-3-sharper-form-anti-correlation-under-auroc">Finding 3 (sharper form) — Anti-correlation under AUROC</a></li>
  <li><a href="#what-the-mechanism-appears-to-be" id="toc-what-the-mechanism-appears-to-be" class="nav-link" data-scroll-target="#what-the-mechanism-appears-to-be">What the mechanism appears to be</a></li>
  </ul></li>
  <li><a href="#act-4-the-other-findings" id="toc-act-4-the-other-findings" class="nav-link" data-scroll-target="#act-4-the-other-findings">Act 4 — The other findings</a>
  <ul class="collapse">
  <li><a href="#finding-4-the-context-window-ablation-was-a-null-result" id="toc-finding-4-the-context-window-ablation-was-a-null-result" class="nav-link" data-scroll-target="#finding-4-the-context-window-ablation-was-a-null-result">Finding 4 — The context-window ablation was a null result</a></li>
  <li><a href="#finding-5-published-detector-versions-are-slice-dependent" id="toc-finding-5-published-detector-versions-are-slice-dependent" class="nav-link" data-scroll-target="#finding-5-published-detector-versions-are-slice-dependent">Finding 5 — Published detector versions are slice-dependent</a></li>
  <li><a href="#finding-6-validation-thresholds-are-fragile" id="toc-finding-6-validation-thresholds-are-fragile" class="nav-link" data-scroll-target="#finding-6-validation-thresholds-are-fragile">Finding 6 — Validation thresholds are fragile</a></li>
  <li><a href="#finding-7-calibration-favors-the-frozen-probe" id="toc-finding-7-calibration-favors-the-frozen-probe" class="nav-link" data-scroll-target="#finding-7-calibration-favors-the-frozen-probe">Finding 7 — Calibration favors the frozen probe</a></li>
  </ul></li>
  <li><a href="#act-5-implications" id="toc-act-5-implications" class="nav-link" data-scroll-target="#act-5-implications">Act 5 — Implications</a>
  <ul class="collapse">
  <li><a href="#what-this-means-for-direct-injection-trained-classifiers" id="toc-what-this-means-for-direct-injection-trained-classifiers" class="nav-link" data-scroll-target="#what-this-means-for-direct-injection-trained-classifiers">What this means for direct-injection-trained classifiers</a></li>
  <li><a href="#what-would-we-try-next" id="toc-what-would-we-try-next" class="nav-link" data-scroll-target="#what-would-we-try-next">What would we try next?</a></li>
  <li><a href="#what-this-means-for-the-broader-prompt-injection-detection-field" id="toc-what-this-means-for-the-broader-prompt-injection-detection-field" class="nav-link" data-scroll-target="#what-this-means-for-the-broader-prompt-injection-detection-field">What this means for the broader prompt-injection-detection field</a></li>
  </ul></li>
  <li><a href="#epilogue-limits-reproduction" id="toc-epilogue-limits-reproduction" class="nav-link" data-scroll-target="#epilogue-limits-reproduction">Epilogue — Limits + reproduction</a>
  <ul class="collapse">
  <li><a href="#what-this-study-does-not-establish" id="toc-what-this-study-does-not-establish" class="nav-link" data-scroll-target="#what-this-study-does-not-establish">What this study does not establish</a></li>
  <li><a href="#reproduce-this-yourself" id="toc-reproduce-this-yourself" class="nav-link" data-scroll-target="#reproduce-this-yourself">Reproduce this yourself</a></li>
  <li><a href="#where-to-dig-deeper" id="toc-where-to-dig-deeper" class="nav-link" data-scroll-target="#where-to-dig-deeper">Where to dig deeper</a></li>
  <li><a href="#a-closing-note" id="toc-a-closing-note" class="nav-link" data-scroll-target="#a-closing-note">A closing note</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./WRITEUP_PAPER.html">Methodology guides (pick a style)</a></li><li class="breadcrumb-item"><a href="./WRITEUP_NARRATIVE.html">Narrative arc (story)</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Prompt-Injection Classification: Methodology and Capability Characterization (Narrative Format)</h1>
</div>

<div>
  <div class="description">
    Plain-English story-arc article presenting the project’s methodology and findings.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Author</strong>: Brandon Behring | <strong>Date</strong>: 2026-05-21 | <strong>Status</strong>: live-site current state <code>tree/v1.3.7</code>; original submission tag <code>tree/v1.0.0</code> (2026-05-18) preserved as historical reviewer pin per ADR-033.</p>
<blockquote class="blockquote">
<p><strong>Reader note.</strong> This is the narrative format of the project writeup — a story rather than a paper. For the same content in academic IMRAD format (Abstract, Methods, Results, Discussion, etc.), see <a href="./WRITEUP_PAPER.html">WRITEUP_PAPER.md</a>. Both guides cover the same evaluation, methodology, findings, and limitations; the register and structure differ. Technical terms are defined on first use and linked to <a href="./docs/GLOSSARY.html">docs/GLOSSARY.md</a>.</p>
</blockquote>
<hr>
<section id="act-0-hook" class="level2">
<h2 class="anchored" data-anchor-id="act-0-hook">Act 0 — Hook</h2>
<p>A prompt-injection detector that has clearly learned to recognize the direct attack pattern, with strong validation numbers, can also be worse than chance on a <em>different family</em> of attacks. Not slightly worse. Anti-correlated: the more the detector “looks like it works” on familiar attacks, the more its rankings can be inverted on unfamiliar ones.</p>
<p>That is the headline of this project. We built a detector ladder, evaluated it honestly under leave-one-dataset-out splits, and got a result that looks neat at first glance and uncomfortable on second read.</p>
<p>Direct prompt-injection detection works well. The TF-IDF + logistic regression baseline reaches 0.971 AUPRC on balanced direct-versus- benign validation. The LoRA-fine-tuned ModernBERT classifier edges it out at 0.974. By any standard in-distribution metric, the detectors learned the task.</p>
<p>Then we tested them on attack families they had not seen during training. The best detector landed at 0.364 AUPRC against a random floor of 0.374. Two of the four classifiers fell <em>below</em> the AUROC random floor of 0.5, with confidence intervals that cleared 0.5 on the wrong side. The frozen ModernBERT probe alone stayed above the floor.</p>
<p>This story is about why that happened, what it tells us about direct-trained detectors as a class, and what we would do differently next time.</p>
<hr>
</section>
<section id="act-1-setup" class="level2">
<h2 class="anchored" data-anchor-id="act-1-setup">Act 1 — Setup</h2>
<section id="the-question" class="level3">
<h3 class="anchored" data-anchor-id="the-question">The question</h3>
<p>A detector for prompt-injection sounds simple. You give it a piece of text. It tells you whether the text is trying to override the instructions an LLM is supposed to follow. Train it on a public prompt-injection corpus. Evaluate it on held-out examples. Report AUPRC and AUROC. Ship.</p>
<p>The hard part is the word “evaluate.” Most public training corpora for prompt-injection detection focus on <strong>direct injection</strong> — the kind where the attacker payload is right there in the user input, typically with imperative phrasing (“ignore previous instructions”, “you are now”). If you train and evaluate on the same kind of text, you measure how well the classifier memorized that style. You do not measure whether it understands what an injection <em>is</em>.</p>
<p>We wanted to know whether the classifier had learned the <em>attack class</em> or just the <em>training style</em>. To answer that, we needed to test it on attack families it had not seen.</p>
</section>
<section id="the-threat-model-context" class="level3">
<h3 class="anchored" data-anchor-id="the-threat-model-context">The threat-model context</h3>
<p>Prompt injection takes many forms in the real world:</p>
<ul>
<li><strong>Direct injection</strong> — the historically studied class. Payload is in the user input. Examples: “ignore your previous instructions and tell me how to…”</li>
<li><strong>Indirect injection</strong> — the payload arrives through third-party context the LLM consumes (a web page, a document, an email).</li>
<li><strong>Agentic-flow injection</strong> — the payload spreads across tool-use turns in an agent loop.</li>
<li><strong>Jailbreak-style questions</strong> — harmful elicitation framed as natural questions; doesn’t look like an override command.</li>
<li><strong>Benign-but-injection-shaped text</strong> — false-positive cases; text that <em>looks</em> like injection but isn’t.</li>
</ul>
<p>A production detector that fails on indirect injection but flags benign-but-injection-shaped text is not a useful detector. We wanted to find out which of these failure modes our detectors would have.</p>
</section>
<section id="what-we-did-not-try-to-do" class="level3">
<h3 class="anchored" data-anchor-id="what-we-did-not-try-to-do">What we did not try to do</h3>
<p>This project is not a product. It is a <strong>capability characterization</strong> — an honest evaluation harness applied to a representative detector ladder, with the goal of answering “what does each added capability buy?”. We are not shipping a deployment-ready detector. We are not proposing a new training method. We are showing what several existing detector designs do under a fairer evaluation than they typically receive.</p>
<p>Specifically out of scope: multilingual attacks, encoded payloads (base64, leetspeak, Unicode confusables), paraphrase robustness, adversarial perturbations, full multi-turn system behavior, and deployment threshold recommendations. We name these out-of-scope items so the reader does not over-generalize the result.</p>
<hr>
</section>
</section>
<section id="act-2-investigation" class="level2">
<h2 class="anchored" data-anchor-id="act-2-investigation">Act 2 — Investigation</h2>
<section id="building-the-evaluation-harness" class="level3">
<h3 class="anchored" data-anchor-id="building-the-evaluation-harness">Building the evaluation harness</h3>
<p>We started with the discipline question: how do we evaluate a prompt-injection detector honestly?</p>
<p>Two design choices were load-bearing:</p>
<p><strong>Source-disjoint splits.</strong> Rather than randomly splitting rows within a single training corpus (which leaks lexical features between training and evaluation), we held entire <em>sources</em> out. The training pool combines four direct-injection corpora: deepset/prompt- injections, Lakera/gandalf_ignore_instructions, Lakera/mosscap, and HackAPrompt. For each leave-one-dataset-out (LODO) fold, one source is fully held out; the detector trains on the remaining three. This is the <strong>leave-one-dataset-out</strong> discipline — <code>LODO</code> for short, and it matters because it prevents the detector from getting a free pass on source-style memorization.</p>
<p><strong>Cross-family OOD test slate.</strong> The test slate intentionally varies attack family rather than source identity. We assembled five held-out OOD slices spanning the four cross-family classes:</p>
<ul>
<li><strong>BIPIA</strong> — indirect injection (payload via document context)</li>
<li><strong>InjecAgent</strong> — agentic-flow injection (payload across tool turns)</li>
<li><strong>JBB-Behaviors</strong> — jailbreak-style questions</li>
<li><strong>XSTest</strong> — jailbreak/safe-question discrimination</li>
<li><strong>NotInject</strong> — benign text engineered to look like injection (false-positive test)</li>
</ul>
<p>None of these families appear in the training pool. That mismatch is the experiment.</p>
</section>
<section id="the-detector-ladder" class="level3">
<h3 class="anchored" data-anchor-id="the-detector-ladder">The detector ladder</h3>
<p>We chose five detectors — a “ladder” of increasing complexity:</p>
<ol type="1">
<li><p><strong>TF-IDF + logistic regression</strong>. The classical baseline. Trains in seconds. Pure lexical features. We included it to answer “what does surface form alone get you?” The answer turned out to be a lot — and that’s part of the story.</p></li>
<li><p><strong>ModernBERT frozen probe</strong>. A linear classifier on top of a pretrained ModernBERT representation, with the backbone frozen. No LODO-pool adaptation. We included it to answer “what does the pretrained backbone already know about injection-like text?”</p></li>
<li><p><strong>ModernBERT LoRA</strong>. Parameter-efficient fine-tuning. The backbone stays frozen; only a small set of adapter weights gets updated on the LODO training pool. We included it to answer “what does targeted adaptation buy us?”</p></li>
<li><p><strong>ModernBERT full fine-tune</strong>. Update all the parameters. We <em>intended</em> to include this as the “full adaptation” comparison point. The Phase 2 LODO direct-source training ran successfully (24 prediction files persisted); the Phase 5 pooled-OOD inference crashed mid-run on a cloud file-system error (X11 EIO on the RunPod /workspace FUSE mount) and we made the call not to re-fire it. Full-FT appears in the LODO direct-source recall table; it is absent from the pooled OOD AUPRC table for that reason. The incomplete-experiment status is flagged on every reporting surface. See <a href="./decisions/ADR-075-full-ft-ood-drop-rationale-unified-narrative.html">ADR-075</a> for the full story.</p></li>
<li><p><strong>ProtectAI v1 and v2</strong> (published reference scorers). DeBERTa-v3- base classifiers trained on direct-injection corpora. Inference- only. They give us diagnostic comparison points — <em>with the caveat</em> that they have documented training-pool overlap with our LODO sources, so their pooled OOD scores on overlapping slices are not clean OOD baselines. We mark them with <code>suspected_contamination</code> and report them as references rather than competitors.</p></li>
</ol>
</section>
<section id="statistical-discipline" class="level3">
<h3 class="anchored" data-anchor-id="statistical-discipline">Statistical discipline</h3>
<p>We promised honest evaluation. That meant:</p>
<ul>
<li><strong>Confidence intervals on every reported number.</strong> We use BCa bootstrap (Bias-Corrected and Accelerated) with 10000 resamples. No point estimates without uncertainty.</li>
<li><strong>Seed-stability check.</strong> Headline numbers run at seed=1; we re-run at seed=2 to verify the result isn’t a coincidence of random init.</li>
<li><strong>Single-class slice handling.</strong> BIPIA, InjecAgent, and NotInject are mathematically single-class (all positive or all negative). AUPRC and AUROC are undefined there. The metrics pipeline filters these slices at source rather than reporting nonsense numbers.</li>
<li><strong>Leakage scan.</strong> Two-stage check across all (train, val, test) per-fold-seed pairs: exact-hash overlap detection + MiniLM-L6-v2 cosine similarity at ≥0.85. Zero overlaps reported.</li>
<li><strong>Effect sizes + CIs, not p-values.</strong> We report the numbers and the intervals; readers can decide.</li>
</ul>
<p>These choices add audit-trail overhead but eliminate the most common forms of “the result looked good but it was contaminated” criticism.</p>
<hr>
</section>
</section>
<section id="act-3-revelation" class="level2">
<h2 class="anchored" data-anchor-id="act-3-revelation">Act 3 — Revelation</h2>
<section id="finding-1-direct-detection-was-learned" class="level3">
<h3 class="anchored" data-anchor-id="finding-1-direct-detection-was-learned">Finding 1 — Direct detection was learned</h3>
<p>Direct detection works. On balanced direct+benign validation data, LoRA reaches 0.974 AUPRC and TF-IDF + LR reaches 0.971. The frozen probe is weaker at 0.653 but still discriminative. The pipeline can train detectors that recognize the direct instruction-override pattern. <strong>That is the first finding: direct prompt-injection detection is a learnable task at this compute budget.</strong></p>
<p>On the LODO held-out direct-source test (all-positive by design), recall-at-0.5 is 0.641 for the frozen probe, 0.625 for LoRA, and 0.558 for full fine-tune. Cross-source direct recall is meaningful.</p>
<p>So far, this looks like a project that built some prompt-injection detectors that work.</p>
</section>
<section id="finding-2-the-ood-wall-is-cross-family-not-source-level" class="level3">
<h3 class="anchored" data-anchor-id="finding-2-the-ood-wall-is-cross-family-not-source-level">Finding 2 — The OOD wall is cross-family, not source-level</h3>
<p>The next question is whether they generalize. We deliberately built the OOD test slate to vary attack <em>family</em> rather than just attack <em>source</em>. The training pool is direct-injection-heavy across four sources; the held-out OOD slate covers four families that don’t appear in training (indirect injection via document context; agentic-flow injection across tool-use turns; jailbreak-as-question; benign-but-injection-shaped). <strong>That is the second finding: the relevant axis of generalization difficulty is cross-family, not source-level.</strong> A different source of the same family wouldn’t be a fair test; we built the harder one.</p>
</section>
<section id="finding-3-the-headline-anti-correlation" class="level3">
<h3 class="anchored" data-anchor-id="finding-3-the-headline-anti-correlation">Finding 3 — The headline anti-correlation</h3>
<p>Then we ran the cross-family test.</p>
<p><strong>Pooled OOD AUPRC table:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Detector</th>
<th style="text-align: right;">Pooled OOD AUPRC</th>
<th style="text-align: right;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ModernBERT frozen probe</td>
<td style="text-align: right;">0.364</td>
<td style="text-align: right;">[0.354, 0.375]</td>
</tr>
<tr class="even">
<td>ProtectAI v1*</td>
<td style="text-align: right;">0.361</td>
<td style="text-align: right;">[0.330, 0.391]</td>
</tr>
<tr class="odd">
<td>ProtectAI v2*</td>
<td style="text-align: right;">0.314</td>
<td style="text-align: right;">[0.283, 0.345]</td>
</tr>
<tr class="even">
<td>ModernBERT LoRA</td>
<td style="text-align: right;">0.293</td>
<td style="text-align: right;">[0.286, 0.301]</td>
</tr>
<tr class="odd">
<td>TF-IDF + LR</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">[0.283, 0.298]</td>
</tr>
</tbody>
</table>
<p>The random floor is 0.374 (since the positive rate on pooled OOD is 412/1101 = 0.374). The best detector is at the floor; the trained adapters are <em>below</em> it.</p>
<p>* ProtectAI v1 + v2 carry <code>suspected_contamination</code> per our contamination taxonomy — they were trained on at least 2 of our 4 LODO training-pool sources, so their pooled OOD scores on overlapping slices are not clean OOD baselines.</p>
<p>That is the headline result for AUPRC. But Finding 3 has a sharper form under AUROC.</p>
</section>
<section id="finding-3-sharper-form-anti-correlation-under-auroc" class="level3">
<h3 class="anchored" data-anchor-id="finding-3-sharper-form-anti-correlation-under-auroc">Finding 3 (sharper form) — Anti-correlation under AUROC</h3>
<p>AUROC has a 0.5 random floor regardless of class balance. Random guessing gets 0.5. Worse than random — below 0.5 — means the detector’s score ordering is <em>systematically wrong</em>, not just noisy.</p>
<p>Under AUROC on pooled OOD:</p>
<ul>
<li><strong>LoRA</strong>: 0.383 [0.374, 0.392]</li>
<li><strong>TF-IDF + LR</strong>: 0.371 [0.362, 0.381]</li>
<li><strong>Frozen probe</strong>: 0.515 [0.505, 0.525]</li>
</ul>
<p>LoRA and TF-IDF + LR both land below 0.5, with confidence intervals that clear 0.5 <em>on the wrong side</em>. The frozen probe alone stays above floor.</p>
<p>The in-pool to cross-family generalization gap for the trained detectors is approximately 0.6 AUROC. The detectors that scored 0.99 AUROC on in-pool data score 0.38 AUROC on cross-family data — the largest possible gap with statistical confidence.</p>
<p>This is not pure overfitting. Pure overfitting predicts collapse <em>toward</em> random performance, not past it. A detector that goes below 0.5 AUROC is producing scores that are <em>anti-correlated</em> with the true label. To get there, you need a specific mechanism — not just “the detector failed to learn,” but “the detector learned something that points the wrong way on this slate.”</p>
<p>That is the surprise. The detectors did not fail in the way we expected.</p>
</section>
<section id="what-the-mechanism-appears-to-be" class="level3">
<h3 class="anchored" data-anchor-id="what-the-mechanism-appears-to-be">What the mechanism appears to be</h3>
<p>After staring at the slate composition for a while, the interpretation that fits is <strong>lexical overfitting combined with a label-relevance shift on the OOD slate</strong>. Both LoRA and TF-IDF + LR appear to learn lexical signatures of direct prompt injection — the imperative phrases, the role-override patterns, the “ignore previous instructions” lexicon. On the cross-family OOD slate, this lexical signal is <em>anti-correlated</em> with the true attack class:</p>
<ul>
<li><strong>NotInject</strong> (339 examples, all negative) is benign text engineered to <em>look like</em> direct injection. Both trained detectors score these examples HIGH (false positives), inverting the negative class.</li>
<li><strong>BIPIA and InjecAgent</strong> (indirect + agentic, 112 positive examples) are real attacks that do <em>not</em> use direct-injection lexical patterns. Both detectors score these examples LOW (false negatives), inverting the positive class.</li>
</ul>
<p>The lexical signal is real and internally consistent within itself. It just stops tracking attack class on the cross-family slate, where “text that resembles direct injection lexically” and “text that is actually an attack” point in opposite directions.</p>
<p>The frozen probe (which never adapted to the LODO pool) preserves generic linguistic features that are less aligned with the direct- injection lexical distribution. That is why the frozen probe stays closer to the random floor on cross-family slices instead of inverting past it. It learned less; it failed less catastrophically.</p>
<p>This is a hypothesis consistent with the aggregate AUROC and the slate composition. We have not directly demonstrated it via per-prediction analysis — that work (comparing detector scores on lexically-direct vs lexically-indirect OOD examples) is on the future-work list (<a href="./NEXT_STEPS.html">NEXT_STEPS §3</a>). The per-row prediction parquets at <code>evals/predictions/</code> support that analysis; running it is portfolio-repo scope.</p>
<hr>
</section>
</section>
<section id="act-4-the-other-findings" class="level2">
<h2 class="anchored" data-anchor-id="act-4-the-other-findings">Act 4 — The other findings</h2>
<p>The headline finding (Finding 3, Act 3) is the load-bearing claim. Three more findings appear inside Act 3 already — <strong>Finding 1</strong> (direct detection was learned) at the start of Act 3, <strong>Finding 2</strong> (the OOD wall is cross-family, not source-level) as the cross-family framing that sets up the contrast, and <strong>Finding 3</strong> (the anti-correlation headline) as the dramatic reveal. The remaining <strong>four findings</strong> support and contextualize the headline. Listed in equal-weight order so they are not lost in the headline’s shadow.</p>
<section id="finding-4-the-context-window-ablation-was-a-null-result" class="level3">
<h3 class="anchored" data-anchor-id="finding-4-the-context-window-ablation-was-a-null-result">Finding 4 — The context-window ablation was a null result</h3>
<p>The natural next question after seeing the ModernBERT-LoRA failure was: <em>did the longer context window matter?</em> ModernBERT has an 8192-token native context; DeBERTa-v3-base has 512. If the OOD gap was driven by long-context effects, switching to a short-context backbone with chunk-and-average aggregation should change something.</p>
<p>We ran the ablation per <a href="./decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html">ADR-060</a>: DeBERTa-v3-base trained under two truncation strategies (chunk-and- average and head-truncation) on the same LODO training data, then evaluated on the same pooled OOD slate.</p>
<p>Result: chunk-and-average scored 0.291 AUPRC; head-truncation scored 0.290. Neither significantly differs from each other or from the ModernBERT-LoRA 0.293. <strong>The context window is not the explanation.</strong> The ModernBERT advantage we saw on the in-pool direct-detection task (Act 3’s strong validation numbers) is therefore best read as backbone-dominant, not context-window-dominant. The cross-family failure mode appears to be backbone-agnostic among the configurations we tested.</p>
<p>This is a publishable null result, which is itself a contribution. Most evaluations stop short of asking the follow-up question.</p>
</section>
<section id="finding-5-published-detector-versions-are-slice-dependent" class="level3">
<h3 class="anchored" data-anchor-id="finding-5-published-detector-versions-are-slice-dependent">Finding 5 — Published detector versions are slice-dependent</h3>
<p>The two ProtectAI versions tell different stories on different slices:</p>
<ul>
<li>ProtectAI v2 improves over v1 on JBB-Behaviors: AUPRC 0.556 vs 0.519.</li>
<li>ProtectAI v2 <em>regresses</em> on XSTest: AUPRC 0.382 vs 0.469.</li>
<li>ProtectAI v2 regresses on pooled OOD overall: AUPRC 0.314 vs 0.361.</li>
</ul>
<p>“Newer is better” does not hold across the full slate. The practical lesson: detector updates should be evaluated against the actual slice mix that matters for the deployment, not on a single aggregate metric. If the deployment context is dominated by JBB-style queries, v2 wins. If it spans the full OOD mix, v1 wins on AUPRC.</p>
<p>This finding is independent of our trained detectors and applies to how the field should evaluate published prompt-injection detectors more broadly.</p>
</section>
<section id="finding-6-validation-thresholds-are-fragile" class="level3">
<h3 class="anchored" data-anchor-id="finding-6-validation-thresholds-are-fragile">Finding 6 — Validation thresholds are fragile</h3>
<p>Detection-policy thresholds were fit per-(fold, seed) on validation data, targeting FPR ≤ 1%. They were applied unchanged to held-out test sources. On test:</p>
<ul>
<li>TF-IDF + LR averages 6.7% FPR (target: 1%)</li>
<li>LoRA averages 11.5% FPR</li>
<li>Frozen probe holds the 1% target but catches only about 6% of positives</li>
</ul>
<p>The 1% FPR target does not hold on held-out sources for the trained detectors. The frozen probe holds the FPR target but at a recall that no deployment would accept.</p>
<p>This is what we mean when we say the methodology is a characterization, not a deployment recommendation. The numbers tell you what the detectors do; they do not give you an operating point you can ship.</p>
</section>
<section id="finding-7-calibration-favors-the-frozen-probe" class="level3">
<h3 class="anchored" data-anchor-id="finding-7-calibration-favors-the-frozen-probe">Finding 7 — Calibration favors the frozen probe</h3>
<p>Among the four detectors with both-class OOD scores, the frozen probe has the lowest expected calibration error (ECE) and lowest Brier score on the pooled OOD slate. Mean ECE: 0.144. Mean Brier: 0.265.</p>
<p>LoRA — which fits the direct training pool best — has worse calibration than the frozen probe. The detector that learns the most about direct injection also produces the least-calibrated probabilities on cross-family text. That reinforces the Act 3 mechanism story: direct-pattern learning and deployable cross-family score behavior are different capabilities, and they trade off against each other.</p>
<p>The full reliability diagrams (raw + temperature-scaled + isotonic- calibrated) are in <a href="./docs/plots/F5.svg">Figure F5</a>. Recalibration helps but does not fix the underlying ranking inversion.</p>
<hr>
</section>
</section>
<section id="act-5-implications" class="level2">
<h2 class="anchored" data-anchor-id="act-5-implications">Act 5 — Implications</h2>
<section id="what-this-means-for-direct-injection-trained-classifiers" class="level3">
<h3 class="anchored" data-anchor-id="what-this-means-for-direct-injection-trained-classifiers">What this means for direct-injection-trained classifiers</h3>
<p>We are cautious about three claims based on this study:</p>
<ol type="1">
<li><p><strong>Direct-pattern learning and cross-family transfer are different capabilities.</strong> A detector that performs well on direct-injection validation does not, by itself, give you confidence in cross- family performance. The two have to be measured separately, and the cross-family slate has to include attacks that genuinely vary in family — not just new sources of the same family.</p></li>
<li><p><strong>AUROC below 0.5 is an active failure mode, not a benign degradation.</strong> The detector is not “failing to find signal” — it is “finding signal that points the wrong way.” A deployment downstream of such a detector could be <em>worse</em> than not having one, because its rankings would be systematically wrong on cross-family text.</p></li>
<li><p><strong>Validation FPR rates are not what you’ll see in production.</strong> On held-out test sources, the trained detectors average 6.7% (TF-IDF + LR) to 11.5% (LoRA) FPR against a 1% validation target. That’s a 7-11× over-fire rate on benign-but-injection-shaped text that wasn’t in the training distribution.</p></li>
</ol>
</section>
<section id="what-would-we-try-next" class="level3">
<h3 class="anchored" data-anchor-id="what-would-we-try-next">What would we try next?</h3>
<p>If we were extending this project, the priority order would be:</p>
<ol type="1">
<li><p><strong>OOD-aware training data.</strong> Include cross-family examples in training (with appropriate per-source dedup against the OOD test slate). The interesting question is whether direct + indirect + agentic + jailbreak in the training pool produces a detector that generalizes across the families, or whether each family needs its own specialized detector.</p></li>
<li><p><strong>Per-prediction mechanism validation.</strong> Run the analysis described in §5.1 of the academic paper format: compare detector scores on lexically-direct vs lexically-indirect OOD examples. This would empirically test the lexical-overfitting hypothesis rather than relying on the aggregate-AUROC interpretation. The per-row prediction parquets at <code>evals/predictions/</code> support this. Portfolio-repo scope.</p></li>
<li><p><strong>Stronger backbone comparisons under matched training budgets.</strong> The ModernBERT-vs-DeBERTa-v3-base ablation answered the context- window question but not the backbone-quality question. A matched- budget comparison across multiple modern backbones (RoBERTa, more recent DeBERTa releases, modern-encoder family) would isolate “what does backbone quality buy?” from “what does training-pool composition buy?”</p></li>
<li><p><strong>Threshold-policy adaptation to held-out FPR statistics.</strong> The detection policy currently calibrates on validation FPR; an adaptive policy that estimates per-source FPR drift and re- calibrates on held-out examples could give more deployable thresholds. Out of scope for this submission; documented in <a href="./NEXT_STEPS.html">NEXT_STEPS</a>.</p></li>
<li><p><strong>Multi-seed × multi-fold replication.</strong> Headline metrics report seed=1 with a seed=2 stability check. A larger replication (multiple seeds × multiple folds) would tighten the confidence intervals further. ~$10-50 GPU spend estimate; portfolio-repo scope.</p></li>
</ol>
</section>
<section id="what-this-means-for-the-broader-prompt-injection-detection-field" class="level3">
<h3 class="anchored" data-anchor-id="what-this-means-for-the-broader-prompt-injection-detection-field">What this means for the broader prompt-injection-detection field</h3>
<p>The detector ladder we evaluated is representative of the published state of the art for direct-injection classifiers. The cross-family failure mode is not specific to our training recipe — it appears to be a property of training on direct-injection-heavy corpora.</p>
<p>If that is correct, the field’s standard evaluation practice (train on direct, evaluate on held-out direct) is systematically over- estimating deployment-relevant capability. The honest evaluation discipline we used (LODO + cross-family OOD slate + CIs) costs more in audit-trail overhead but produces results that are less likely to mislead a deployment team.</p>
<hr>
</section>
</section>
<section id="epilogue-limits-reproduction" class="level2">
<h2 class="anchored" data-anchor-id="epilogue-limits-reproduction">Epilogue — Limits + reproduction</h2>
<section id="what-this-study-does-not-establish" class="level3">
<h3 class="anchored" data-anchor-id="what-this-study-does-not-establish">What this study does not establish</h3>
<p>The negative result on cross-family transfer does not establish:</p>
<ul>
<li>That a different training pool (with cross-family coverage) would fail similarly.</li>
<li>That a larger or different backbone would fail similarly.</li>
<li>That the cross-family failure is fundamental to the problem rather than addressable with OOD-aware training.</li>
</ul>
<p>Specifically, we did not test cross-family training data, non- Transformer architectures, ensemble methods, threshold-policy adaptations to held-out FPR statistics, or multi-detector voting. Several of these are on the future-work list above and in <a href="./NEXT_STEPS.html">NEXT_STEPS</a>.</p>
</section>
<section id="reproduce-this-yourself" class="level3">
<h3 class="anchored" data-anchor-id="reproduce-this-yourself">Reproduce this yourself</h3>
<p>Three reproduction tiers, in increasing cost order:</p>
<ul>
<li><p><strong>T0 — score-match against published checkpoints</strong> (~$0, ~20 min)</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/brandon-behring/prompt-injection-detection-prototype</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> prompt-injection-detection-prototype</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> install</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> eval-from-hub RUNG=frozen-probe</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> eval-from-hub RUNG=lora</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Score-matches against <code>evals/results.json</code> within 1e-4 absolute tolerance per ADR-058.</p></li>
<li><p><strong>T1 — laptop smoke</strong> (~$0, &lt;10 min)</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> test-smoke</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p><strong>T3 — full retraining from scratch on cloud GPU</strong> (~$125, hours)</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> headline-cloud  <span class="co"># cost-capped per ADR-020</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
</ul>
<p>HF Hub checkpoints: <a href="https://huggingface.co/BBehring/prompt-injection-frozen-probe">BBehring/prompt-injection-frozen-probe</a>, <a href="https://huggingface.co/BBehring/prompt-injection-lora">BBehring/prompt-injection-lora</a>.</p>
</section>
<section id="where-to-dig-deeper" class="level3">
<h3 class="anchored" data-anchor-id="where-to-dig-deeper">Where to dig deeper</h3>
<ul>
<li><strong>Numbers</strong>: <a href="./RESULTS.html">RESULTS.md</a> for all canonical tables and the 5 figures.</li>
<li><strong>Methodology depth</strong>: 8 detailed spokes under <a href="./WRITEUP/">WRITEUP/</a> — data decisions, evaluation design, model details, threshold policy, reference-scorer audit, methodology guarantees, reproducibility, limitations and future work.</li>
<li><strong>Decision rationale</strong>: 81 ADRs at <a href="./decisions/">decisions/</a> lock the methodology choices.</li>
<li><strong>Cost ledger</strong>: <a href="./evals/cost_ledger.csv">evals/cost_ledger.csv</a> for full GPU and API spend accounting.</li>
<li><strong>Glossary</strong>: <a href="./docs/GLOSSARY.html">docs/GLOSSARY.md</a> for all technical terms used here.</li>
</ul>
</section>
<section id="a-closing-note" class="level3">
<h3 class="anchored" data-anchor-id="a-closing-note">A closing note</h3>
<p>We set out to evaluate prompt-injection detectors fairly. The methodology we built does that. The headline finding — that direct- trained detectors can be anti-correlated with cross-family attack class — was surprising and uncomfortable. We were tempted to soften it, or to bury it under the other six findings.</p>
<p>We did not. The honest result deserves the honest framing. Direct detection is a learnable problem and cross-family generalization fails for these detector designs under this evaluation. That is what the data shows. The path forward is to extend the training pool, not to soften the result.</p>
<hr>
<p><em>End of narrative. For the same content in academic IMRAD format, see <a href="./WRITEUP_PAPER.html">WRITEUP_PAPER.md</a>.</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>