<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>writeup – Prompt-injection classifier — methodology submission</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6417478169390d5200ae675d66b5a4f4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Prompt-injection classifier — methodology submission</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./EXECUTIVE_SUMMARY.html" aria-current="page"> 
<span class="menu-text">Executive summary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Reading guide</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./WRITEUP.html"> 
<span class="menu-text">Methodology (TOC)</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-spokes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Spokes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-spokes">    
        <li>
    <a class="dropdown-item" href="./WRITEUP/data-decisions.html">
 <span class="dropdown-text">Data decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/model-rungs.html">
 <span class="dropdown-text">Model rungs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/eval-design.html">
 <span class="dropdown-text">Evaluation design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/threshold-policy.html">
 <span class="dropdown-text">Threshold policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reference-scorer-audit.html">
 <span class="dropdown-text">Reference-scorer audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/methodology-guarantees.html">
 <span class="dropdown-text">Methodology guarantees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/limitations-and-future-work.html">
 <span class="dropdown-text">Limitations and future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./WRITEUP/reproducibility.html">
 <span class="dropdown-text">Reproducibility — three reproduction tiers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./EVIDENCE.html"> 
<span class="menu-text">Evidence</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reference">    
        <li>
    <a class="dropdown-item" href="./SPEC_SHEET.html">
 <span class="dropdown-text">Project specification (filled at end of Phase 0)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./SUBMISSION_AUDIT.html">
 <span class="dropdown-text">Submission audit — claim status ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./NEXT_STEPS.html">
 <span class="dropdown-text">Next steps</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assumptions.html">
 <span class="dropdown-text">Assumptions registry</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./decisions/README.html"> 
<span class="menu-text">Decisions (ADRs)</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./WRITEUP.html">Methodology</a></li><li class="breadcrumb-item"><a href="./WRITEUP.html">Prompt-injection classification — methodology + capability characterisation</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Reading guide</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EXECUTIVE_SUMMARY.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Executive summary — 1-page decision-maker layer over WRITEUP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prompt-injection classifier — reviewer reading guide</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Prompt-injection classification — methodology + capability characterisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/data-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/model-rungs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model rungs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/eval-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/threshold-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threshold policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reference-scorer-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/limitations-and-future-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Limitations and future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./WRITEUP/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility — three reproduction tiers</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence + audit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EVIDENCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evidence — audit trail</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SPEC_SHEET.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project specification (filled at end of Phase 0)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SUBMISSION_AUDIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission audit — claim status ledger</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./NEXT_STEPS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Next steps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions registry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions (ADRs)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architecture Decision Records (ADRs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/upstream_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Upstream issues filed during this iteration</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Decisions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-001-submission-deadline-and-scope-ambition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission deadline 2026-05-18 morning with infra-leveraged Long-scope attempt and fallback ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-002-deliverable-format-pdf-and-repo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — focused PDF plus public GitHub repo as evidence locker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-003-repo-visibility-public.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repository visibility — public from start (kit default ratified)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-004-reviewer-profile-and-hub-and-spoke-writeup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer profile A1+A2 with hub-and-spoke writeup structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-005-methodology-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-level methodology principles — methodology over metrics, honest evaluation preferred, structured limitations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-006-headline-metrics-and-statistical-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Headline metrics, operating-point pinpoints, and statistical apparatus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-007-rung-architecture-and-reference-scorers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology rung architecture — trained backbones, LLM-judge reference rungs, Cohen’s kappa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-008-data-scope-public-only-hybrid-splits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data scope — public-only sources, hybrid splits, NotInject inclusion (brief-level lock)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-009-process-mandates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Process mandates — two-tier reproducibility, marker-based testing, compute disclosure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-010-scope-limits-with-extension-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scope limits with per-bound extension conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-011-methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees — eight banned approaches surfaced as project commitments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-012-soft-signals-and-artifact-engagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Soft-signals naming discipline and external artifact engagement set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-013-kit-ratify-bulk-strictness-intake-notebook-persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kit-ratify bulk — Phase 0 strictness, brief-intake protocol, notebook role and RunPod persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-014-threat-model-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threat-model bundle — attack-class scope, language, length cap, truncation policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-015-rung-architecture-refinement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung architecture refinement — ModernBERT-base only trained slate, supersedes ADR-007</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-016-data-design-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data design bundle — source slate, splits, HF pinning, dedup, ordering, ceilings, ref-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-017-trained-rung-slate-expansion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trained-rung-slate expansion — TF-IDF plus LR classical floor and frozen-probe dual role</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-018-reference-scorer-slate-and-contamination-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference scorer slate and contamination stratification — OpenAI plus Anthropic LLM-judges plus ProtectAI v1 and v2 plus per-axis matched-budget</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-019-lora-and-transformer-training-recipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA and transformer-rung training recipe — hyperparameters, epochs, precision, class weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-020-compute-infrastructure-and-cost-discipline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute infrastructure and cost discipline — runpod-deploy 0.7.7 primitives, GPU failover, adaptive batch sizing, dual-layer cost tracking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-021-eval-slate-aggregation-and-recall-fpr-pinpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eval slate aggregation — pooled headline plus per-slice spoke and recall@FPR pinpoint feasibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-022-statistical-inference-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference apparatus — bootstrap N + stability check, multi-comparison stance, multi-seed protocol, paired-test method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-023-calibration-battery-and-interventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery composition — raw plus temperature plus isotonic interventions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-024-cross-fold-ci-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-fold CI methodology — cv_clt_ci (Bayle 2020) headline plus block-bootstrap-on-folds spoke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-025-dual-policy-threshold-characterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dual-policy threshold characterization at symmetric 1% cost weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-026-module-layout-concern-grouped-subpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module layout — concern-grouped sub-packages under src/</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-027-smoke-vs-canonical-execution-context-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Smoke vs canonical separation — three Makefile targets stratified by execution context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-028-coverage-floor-70pct-with-upstream-issue-filing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test coverage floor — 70% flat with co-locked upstream-issue-filing discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-029-test-marker-strategy-four-marker-ratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test marker strategy — ratify 4-marker stratification (unit / smoke / integration / network)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-030-deliverable-format-quarto-html-site.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — repo-only with Quarto-rendered HTML site via GitHub Actions (supersedes ADR-002)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-031-reviewer-reading-paths-quarto-site-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer reading paths — index.qmd entry-point with Quarto sidebar nav (supersedes ADR-004)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-032-hf-hub-publication-headline-rungs-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HF Hub checkpoint publication — publish primary headline rungs only with model card discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-033-github-release-strategy-rehearsal-plus-submission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitHub release strategy — rehearsal tag plus SemVer submission tag plus post-submission patches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-034-reproducibility-tier-full-ladder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility tier — full ladder T0 (eval-from-hub) plus T1 (smoke) plus T3 (headline-cloud)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-035-secrets-management-three-store-split.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secrets management — three-store split aligned with execution context (.env + RunPod pod-secrets + GH Actions repo Secrets)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-036-library-version-pins-tag-pin-plus-freeze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library version pins — tag pin to latest stable plus freeze for submission window (eval-toolkit v0.31.0 + runpod-deploy v0.7.7 + research_toolkit v1.9.1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-037-python-version-pin-3-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python version pin — ratify requires-python &gt;=3.13 (matches existing .python-version + bc8ce4e commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-038-phase-tailoring-light-roadmap-edits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase tailoring — light ROADMAP edits to Phase 4 close + Phase 5 description (preserves 5-phase structure)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-039-acceptance-criteria-six-gate-integration-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-specific acceptance criteria — 6-gate integration checklist for v1.0.0 submission tag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-040-phase-0-audit-findings-and-assumption-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 0 final audit findings + 7-assumption backfill (A-010 through A-016)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-041-phase-1-data-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 (Data) implementation bundle — manifest schema, SHA pinning, validator placement, loader arch, holdout sourcing, contamination corpus, output materialization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-042-llm-prelabel-dedup-holdout-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-judge pre-label as Q5 holdout-labeling bootstrap with human override</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-043-post-split-cross-source-leakage-cleanup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-split cross-source leakage cleanup — drop train+val rows that exact-match or cosine-near-match test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-044-phase-2-training-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 training implementation bundle — seed slate reconciliation + manifest move + classical-floor location + YAML config schema + trainer split + per-rung orchestration + fixture preflight</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-045-phase-3-evaluation-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 evaluation implementation bundle — scoring-first contract + 6-commit cadence + tiered reference scorers + classical-scaffold + full-pairwise persistence with headline-only WRITEUP + pydantic schema validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-046-phase-4-analysis-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 analysis implementation bundle — 6-commit cadence + scaffold-with-classical + always-emit-both-CIs auto-flag + MDE-on-every-emitted-CI + LLM-rater audit included (user-overridden from defer) + library-first hybrid figures + Phase 5 prep deferred</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-047-phase-1-library-first-carryforward-refactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 library-first carryforward refactor — audit findings + remediation plan (splits + dedup + leakage_report + contamination_scan migration to eval-toolkit primitives; orphaned code removed in-commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-048-llm-rater-reference-scorer-audit-protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-rater reference-scorer audit protocol — disagreement-with-LoRA baseline + stratified (5 OOD slices × 3 contamination_states) sampling + fixed 2-axis rubric + inter-rater gpt-4o-plus-claude-sonnet + dry-run-then-single-approval cost UX</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-049-gpu-order-priority-refresh-a100-80g.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPU failover ladder priority refresh — A100-SXM4-80GB to position 1 + US-WA-1/US-CA-2 datacenter additions + EU-RO-1 drop (frozen-probe + LoRA canonical; full-FT deferred to post-rehearsal)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-050-rung-slate-narrowing-llm-judges-and-full-ft-ood-dropped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung slate narrowing — LLM judges dropped (cost) + full-FT OOD dropped (FUSE EIO crash); narrow supersession of ADR-018 reference slate + ADR-021 OOD comparison scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-051-v1.0.x-carryforward-of-t0-and-invariant-scaffolds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">v1.0.x carryforward of ADR-034 T0 score-match wiring + ADR-039 gate-3 invariant-scaffold unskip; narrow supersession with explicit v1.1.x landing condition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-052-full-ft-ood-drop-methodological-reframing-of-adr-050-r2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full-FT OOD inference drop — methodological reframing; narrow supersession of ADR-050 Revision 2 (FUSE-crash-only framing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisions/ADR-053-reading-guide-governance-and-newcomer-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading-guide governance + newcomer onboarding paths — two entry artifacts + 3 reading paths + Headline-finding-block + interpretation pedagogy + pointer convention</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#prompt-injection-classification-methodology-capability-characterisation" id="toc-prompt-injection-classification-methodology-capability-characterisation" class="nav-link active" data-scroll-target="#prompt-injection-classification-methodology-capability-characterisation">Prompt-injection classification — methodology + capability characterisation</a>
  <ul class="collapse">
  <li><a href="#reading-guide" id="toc-reading-guide" class="nav-link" data-scroll-target="#reading-guide">Reading guide</a></li>
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">1. Motivation</a>
  <ul class="collapse">
  <li><a href="#scope-single-turn-english-text-classifier" id="toc-scope-single-turn-english-text-classifier" class="nav-link" data-scroll-target="#scope-single-turn-english-text-classifier">Scope (single-turn English text classifier)</a></li>
  </ul></li>
  <li><a href="#attack-type-taxonomy-traintest-composition" id="toc-attack-type-taxonomy-traintest-composition" class="nav-link" data-scroll-target="#attack-type-taxonomy-traintest-composition">1.5 Attack-type taxonomy + train/test composition</a></li>
  <li><a href="#approach-overview" id="toc-approach-overview" class="nav-link" data-scroll-target="#approach-overview">2. Approach overview</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#the-iid-vs-ood-gap-primary-narrative" id="toc-the-iid-vs-ood-gap-primary-narrative" class="nav-link" data-scroll-target="#the-iid-vs-ood-gap-primary-narrative">The IID-vs-OOD gap (primary narrative)</a></li>
  <li><a href="#which-capabilities-help-ood-vs-only-help-iid" id="toc-which-capabilities-help-ood-vs-only-help-iid" class="nav-link" data-scroll-target="#which-capabilities-help-ood-vs-only-help-iid">Which capabilities help OOD vs only help IID</a></li>
  <li><a href="#score-behaviour-at-the-two-operating-points" id="toc-score-behaviour-at-the-two-operating-points" class="nav-link" data-scroll-target="#score-behaviour-at-the-two-operating-points">Score-behaviour at the two operating points</a></li>
  <li><a href="#calibration-findings" id="toc-calibration-findings" class="nav-link" data-scroll-target="#calibration-findings">Calibration findings</a></li>
  <li><a href="#frozen-probe-vs-adapter-fine-tuned-paired-bootstrap" id="toc-frozen-probe-vs-adapter-fine-tuned-paired-bootstrap" class="nav-link" data-scroll-target="#frozen-probe-vs-adapter-fine-tuned-paired-bootstrap">Frozen probe vs adapter fine-tuned (paired bootstrap)</a></li>
  <li><a href="#the-headline-characterisation-claims" id="toc-the-headline-characterisation-claims" class="nav-link" data-scroll-target="#the-headline-characterisation-claims">The headline characterisation claims</a></li>
  <li><a href="#takeaways-for-the-intro-only-reader" id="toc-takeaways-for-the-intro-only-reader" class="nav-link" data-scroll-target="#takeaways-for-the-intro-only-reader">Takeaways (for the intro-only reader)</a></li>
  </ul></li>
  <li><a href="#lessons-brief" id="toc-lessons-brief" class="nav-link" data-scroll-target="#lessons-brief">Lessons (brief)</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">12. Appendix</a>
  <ul class="collapse">
  <li><a href="#a.-glossary" id="toc-a.-glossary" class="nav-link" data-scroll-target="#a.-glossary">A. Glossary</a></li>
  <li><a href="#b.-adr-index" id="toc-b.-adr-index" class="nav-link" data-scroll-target="#b.-adr-index">B. ADR index</a></li>
  <li><a href="#c.-assumption-ledger" id="toc-c.-assumption-ledger" class="nav-link" data-scroll-target="#c.-assumption-ledger">C. Assumption ledger</a></li>
  <li><a href="#d.-audit-trail" id="toc-d.-audit-trail" class="nav-link" data-scroll-target="#d.-audit-trail">D. Audit trail</a></li>
  <li><a href="#e.-linked-claude-transcripts" id="toc-e.-linked-claude-transcripts" class="nav-link" data-scroll-target="#e.-linked-claude-transcripts">E. Linked Claude transcripts</a></li>
  <li><a href="#f.-eval-toolkit-methodology-curriculum" id="toc-f.-eval-toolkit-methodology-curriculum" class="nav-link" data-scroll-target="#f.-eval-toolkit-methodology-curriculum">F. eval-toolkit methodology curriculum</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./WRITEUP.html">Methodology</a></li><li class="breadcrumb-item"><a href="./WRITEUP.html">Prompt-injection classification — methodology + capability characterisation</a></li></ol></nav><h1 class="title display-7"></h1></header><div class="quarto-title-block"><div class="quarto-title-tools-only"><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>




<section id="prompt-injection-classification-methodology-capability-characterisation" class="level1">
<h1>Prompt-injection classification — methodology + capability characterisation</h1>
<p><strong>Author</strong>: Brandon Behring · <strong>Date</strong>: 2026-05-18 · <strong>Status</strong>: <code>v1.0.0</code> submission tag (Phase 5 close)</p>
<p>This document is the <strong>TOC + landing page</strong>: the cover narrative (§1 Motivation, §2 Approach overview, §Results, §Lessons, §Appendix) lives here; the detailed sections live as spokes under <a href="./WRITEUP/"><code>WRITEUP/</code></a> (linked below).</p>
<section id="reading-guide" class="level2">
<h2 class="anchored" data-anchor-id="reading-guide">Reading guide</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Spoke</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./WRITEUP/data-decisions.html"><code>WRITEUP/data-decisions.md</code></a></td>
<td>§3 Data design — source slate selection + dedup + leakage + LODO splits</td>
</tr>
<tr class="even">
<td><a href="./WRITEUP/model-rungs.html"><code>WRITEUP/model-rungs.md</code></a></td>
<td>§4 Rung ladder — classical floor + ModernBERT × {frozen-probe, LoRA, full-FT} + ProtectAI v1/v2</td>
</tr>
<tr class="odd">
<td><a href="./WRITEUP/eval-design.html"><code>WRITEUP/eval-design.md</code></a></td>
<td>§5.1, §5.2, §5.4, §5.5 — metric battery + paired-bootstrap + MDE + calibration + OOD slate composition</td>
</tr>
<tr class="even">
<td><a href="./WRITEUP/threshold-policy.html"><code>WRITEUP/threshold-policy.md</code></a></td>
<td>§5.3 — dual-policy detection + verification operating points + val→test reachability</td>
</tr>
<tr class="odd">
<td><a href="./WRITEUP/reference-scorer-audit.html"><code>WRITEUP/reference-scorer-audit.md</code></a></td>
<td>§3.3 + §5.6 + §7.2/3 — ADR-005 contamination taxonomy applied to reference scorers + adversarial-robustness scope</td>
</tr>
<tr class="even">
<td><a href="./WRITEUP/methodology-guarantees.html"><code>WRITEUP/methodology-guarantees.md</code></a></td>
<td>§6 Tooling — eval-toolkit + runpod-deploy + SDD process + library-first invariant</td>
</tr>
<tr class="odd">
<td><a href="./WRITEUP/limitations-and-future-work.html"><code>WRITEUP/limitations-and-future-work.md</code></a></td>
<td>§8 scope deferrals + §8.2 methodology caveats + §9 negative results + §11 lessons</td>
</tr>
<tr class="even">
<td><a href="./WRITEUP/reproducibility.html"><code>WRITEUP/reproducibility.md</code></a></td>
<td>§10 T0 + T1 + T3 reproduction tiers</td>
</tr>
</tbody>
</table>
<p>For the audit trail of external-evidence claims, see <a href="./EVIDENCE.html"><code>EVIDENCE.md</code></a>. For the per-decision ADR record, see <a href="./decisions/"><code>decisions/</code></a> + <a href="./SUBMISSION_AUDIT.html"><code>SUBMISSION_AUDIT.md</code></a>.</p>
<hr>
</section>
<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">1. Motivation</h2>
<blockquote class="blockquote">
<p>My main concern after reading the literature: most prompt-injection detectors are evaluated on data that leaks into training, so their reported OOD numbers don’t tell you much. A classifier that cross-validates on a single direct-prompt-injection dataset is trivial to build, but it gives a poor read on OOD performance and raises real leakage concerns. This project is my attempt to build a fairer evaluation harness around that — not to find the best model, but to lay the groundwork for fairer evaluation and to identify weaknesses of our model and of some existing reference scorers.</p>
</blockquote>
<p>Prompt-injection — text designed to override or subvert the instructions an LLM-based system is operating under — is one of the load-bearing failure modes for any system that exposes an LLM to untrusted input. Ciphero’s verification-layer thesis is that we cannot govern what we cannot verify; one primitive in that stack is a classifier that scores whether a span of text is an injection attempt.</p>
<p>The same scores serve two operational contexts:</p>
<ul>
<li><strong>Detection</strong> — <em>catch injections coming in</em>. Tolerates false positives more than false negatives (an alert costs less than a missed attack at the input boundary).</li>
<li><strong>Verification</strong> — <em>confirm clean text actually is clean</em>. Tolerates false negatives more than false positives (a confidently-clean assertion is the dangerous one).</li>
</ul>
<p>These are not two classifiers; they are two threshold policies on the same scores, with different cost weights. See <a href="./WRITEUP/threshold-policy.html"><code>WRITEUP/threshold-policy.md</code></a> for how the same primitive is configured to characterise both.</p>
<p>This writeup characterises a 5-rung ladder of prompt-injection classifiers — TF-IDF+LR classical floor + ModernBERT-base × {frozen-probe, LoRA, full-FT} + ProtectAI v1 + ProtectAI v2 reference scorers (locked at Phase 0-03 per ADR-015 + ADR-017 + ADR-018 + ADR-050 + ADR-052) — across an OOD slate, with the question: <em>what does each capability layer add, and where does the IID/OOD gap fall?</em> The work is <strong>methodology + capability characterisation braided</strong>: the ladder is the instrument; the eval methodology rigor is what makes the characterisation defensible; the brief’s two asks (models of increasing complexity + OOD coverage) are the targets.</p>
<p><strong>Honest-OOD thesis</strong>: IID numbers are the easy part. The interesting question for any classifier that might one day touch a deployment surface is <em>which capabilities help when the distribution shifts, and which ones only inflate the IID number</em>. That question — not “what’s the best PR-AUC” — drives this document’s structure.</p>
<p><strong>Deployment is not on the roadmap.</strong> This is characterisation, not recommendation. No rung is promoted as the deployment choice; each rung’s trade-offs are reported and the reader is left to draw their own deployment conclusions if they have one to make.</p>
<p><strong>Linked ADRs</strong>: ADR-001 (brief alignment), ADR-013 (deliverable scope + WRITEUP shape), ADR-017 (rung-slate expansion).</p>
<section id="scope-single-turn-english-text-classifier" class="level3">
<h3 class="anchored" data-anchor-id="scope-single-turn-english-text-classifier">Scope (single-turn English text classifier)</h3>
<p>This submission characterises a <em>prompt-injection text classifier</em> on an English-only fixed slate (4 LODO training sources + 5 OOD test slices). What is <strong>deliberately out of scope</strong> (per ADR-014 + <a href="./WRITEUP/limitations-and-future-work.html"><code>WRITEUP/limitations-and-future-work.md</code></a> §8.1; named explicitly so a reviewer reading only this section knows what the numbers do <em>not</em> cover):</p>
<ul>
<li><strong>Multi-turn / agentic-flow injection</strong> — payload split across multiple conversation turns or tool-use steps. <em>Named in the test slate via InjecAgent to quantify the gap; not detected by the single-turn classifier scope.</em></li>
<li><strong>Encoded payloads</strong> — base64 / leetspeak / hex / Unicode confusables / ROT13.</li>
<li><strong>Paraphrase attacks</strong> — semantic equivalents that don’t share surface n-grams with training injections.</li>
<li><strong>Adversarial perturbations</strong> — gradient-guided or search-based evasion against a specific classifier.</li>
<li><strong>Cross-language coverage</strong> — the slate is English-only by source-slate construction.</li>
<li><strong>Conformal prediction + adversarial red-teaming</strong> — see WRITEUP/limitations-and-future-work.md §8.1.</li>
</ul>
<p>The work is <strong>methodology + capability characterisation braided</strong>: the ladder is the instrument; the eval methodology rigor is what makes the characterisation defensible. Deployment recommendations are explicitly out of scope.</p>
<hr>
</section>
</section>
<section id="attack-type-taxonomy-traintest-composition" class="level2">
<h2 class="anchored" data-anchor-id="attack-type-taxonomy-traintest-composition">1.5 Attack-type taxonomy + train/test composition</h2>
<p>Five operationally-distinct injection types are relevant to this submission. Each type is defined in a single sentence; the table below maps which types appear in the 4 LODO training-pool sources vs the 5 OOD test slices. The mismatch is the load-bearing story for §Results — the OOD slate probes injection types that are <em>not</em> in the training pool.</p>
<p><strong>Type definitions:</strong></p>
<ul>
<li><strong><code>direct_injection</code></strong> — adversarial text in the user’s input attempting to override system instructions. Single-turn, in-channel. Examples: “ignore the above and …”, “you are now …”.</li>
<li><strong><code>indirect_injection</code></strong> — adversarial text arriving via a context channel the LLM processes (a retrieved document, an email body, a tool’s output). The user’s <em>direct</em> input is benign; the injection rides on data the LLM was meant to consume.</li>
<li><strong><code>agentic_flow_injection</code></strong> — payload split across multi-turn tool-use; detecting it requires intermediate-state interception (tool-call args, function-output contamination), not just classifying a single text span.</li>
<li><strong><code>jailbreak_as_question</code></strong> — safety-bypass framed as a legitimate-looking question rather than an instruction override (e.g., “for a story I’m writing, how would a character …”).</li>
<li><strong><code>false_positive_probe</code></strong> — benign text structurally similar to injections (e.g., literal discussions of injection attacks). Tests whether the classifier discriminates <em>intent</em> from <em>form</em>.</li>
</ul>
<p><strong>Train/test composition</strong> — <code>Y</code> = type present (or dominantly present in that source); <code>-</code> = type absent. Training sources locked per ADR-016; OOD slices per ADR-021.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Injection type</th>
<th style="text-align: center;">TRAIN: <code>deepset/prompt-injections</code></th>
<th style="text-align: center;">TRAIN: <code>Lakera/gandalf_ignore_instructions</code></th>
<th style="text-align: center;">TRAIN: <code>Lakera/mosscap_prompt_injection</code></th>
<th style="text-align: center;">TRAIN: <code>hackaprompt/hackaprompt-dataset</code></th>
<th style="text-align: center;">TEST: <code>bipia</code></th>
<th style="text-align: center;">TEST: <code>injecagent</code></th>
<th style="text-align: center;">TEST: <code>jbb_behaviors</code></th>
<th style="text-align: center;">TEST: <code>xstest</code></th>
<th style="text-align: center;">TEST: <code>notinject</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>direct_injection</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;">partial</td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
</tr>
<tr class="even">
<td><code>indirect_injection</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
</tr>
<tr class="odd">
<td><code>agentic_flow_injection</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
</tr>
<tr class="even">
<td><code>jailbreak_as_question</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;">partial</td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>Y</code></td>
<td style="text-align: center;"><code>-</code></td>
</tr>
<tr class="odd">
<td><code>false_positive_probe</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: center;"><code>Y</code></td>
</tr>
</tbody>
</table>
<p><strong>Key reads from the table:</strong></p>
<ul>
<li>The 4 LODO training sources are <strong>direct-injection-heavy</strong>. The training pool teaches the classifier to recognise instruction-override style attacks in user input.</li>
<li>BIPIA (test) is the <strong>only indirect-injection slate</strong>; <em>zero</em> indirect-injection coverage in training. This is a structural train/test mismatch by design — the OOD wall on BIPIA quantifies it.</li>
<li>InjecAgent (test) is the <strong>only agentic-flow slate</strong>; <em>zero</em> agentic-flow coverage in training. Agentic flow is also out-of-scope for the single-turn classifier per §Scope above — InjecAgent is included in the test set to quantify the gap, not because we expect the classifier to do well.</li>
<li>NotInject (test) is a <strong>pure false-positive probe</strong>; no counterpart in training. Tests intent-vs-form discrimination.</li>
<li>JBB-Behaviors + XSTest (test) carry jailbreak-as-question style attacks. HackAPrompt partially covers this; the other 3 training sources do not.</li>
</ul>
<p>The §Results section reads against this table — performance per OOD slice tracks whether that slice’s injection type is represented in the training pool.</p>
<p><strong>Note on what “OOD” means here.</strong> “In-domain test” is still a direct-injection attack — just an unseen source held out by LODO. The 5-slice “OOD” slate is something else entirely: <strong>indirect injection via email-body context (BIPIA), multi-turn agentic-flow attacks (InjecAgent), jailbreaks (JBB-Behaviors), and benign-but-injection-shaped texts that test false-positive robustness (NotInject, XSTest).</strong> The OOD wall in §Results is <strong>cross-family</strong>, not cross-source: the trained rungs are tested on attack types absent from their training pool. Direct prompt-injection training and evaluation performance alone do not translate into these other attack families — that is the load-bearing finding of this submission.</p>
<hr>
</section>
<section id="approach-overview" class="level2">
<h2 class="anchored" data-anchor-id="approach-overview">2. Approach overview</h2>
<p>The brief asked for two things: <em>models of increasing complexity</em> and <em>the right amount of OOD coverage</em>. The rung ladder satisfies the first ask and is the <strong>instrument</strong> for the second: when a rung helps IID but not OOD, that tells us its added capability is data-pattern-fitting rather than generalisation; when a rung helps both, the added capability is more durable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Role</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rung ladder (locked Phase 0-03 per ADR-015 + ADR-017 + ADR-050)</td>
<td>Instrument</td>
<td>Each step’s lift over the previous decomposes <em>which capability</em> matters.</td>
</tr>
<tr class="even">
<td>OOD slate (5 slices locked Phase 0-04 per ADR-016 + ADR-021)</td>
<td>Measurement</td>
<td>Quantifies what each capability adds when the distribution shifts.</td>
</tr>
<tr class="odd">
<td>Dual cost-weight thresholds</td>
<td>Score-behaviour characterisation</td>
<td>Shows what the same scores deliver under two different operational cost regimes.</td>
</tr>
<tr class="even">
<td>Statistical rigor (CIs + paired comparisons + MDE)</td>
<td>Defensibility</td>
<td>Lets us claim differences honestly and quantify when we lack the power to claim anything.</td>
</tr>
</tbody>
</table>
<p>We do <strong>not</strong> pick a deployment leader. The intent is to demonstrate what each rung delivers and where it breaks; readers with a specific deployment context can map our characterisation onto their cost constraints.</p>
<p><strong>Linked ADRs</strong>: ADR-002 (approach scaffold), ADR-014 (single-backbone slate framing), ADR-017 (rung-slate expansion), ADR-021 (slice aggregation + headline-metric protocol).</p>
<p><strong>Known gaps</strong>: this approach evaluates EACH rung against the same slate; cross-rung-ensemble strategies (e.g., LoRA-with-frozen-probe-temperature) are out of scope per the project compute budget.</p>
<hr>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p><strong>The negative result IS the result.</strong> None of the rungs decisively beats the classical TF-IDF+LR floor on the 5-slice OOD slate, and the OOD wall is <strong>cross-family</strong> (read against the §1.5 train/test table): training pool is 4 direct-injection sources; OOD slate probes indirect injection via email-body context (BIPIA), multi-turn agentic-flow (InjecAgent), jailbreaks (JBB-Behaviors), and benign-but-injection-shaped texts that test false-positive robustness (NotInject, XSTest) — attack types absent from training. Direct prompt-injection training and evaluation performance alone do not translate into these other attack families. That finding is the argument for a fairer evaluation framework, which is what this project is.</p>
<p>Specifically: across the rung ladder + two reference scorers, <strong>none of the rungs clears the <code>pooled_ood</code> positive-class prevalence baseline (0.374) under AUPRC</strong> (range 0.291–0.364; even frozen-probe at 0.364 lands just under prevalence). The trained transformer rungs (frozen-probe + LoRA) and the ProtectAI reference scorers cluster within a band that is statistically distinguishable on the in-distribution-like slices (jbb_behaviors, xstest) but compresses to at-or-below the prevalence baseline on pooled_ood. The story is not “the ladder works” — it is <em>the ladder works on IID-shaped attacks and fails to generalize to genuinely OOD distributions</em>, and the numbers below back that up.</p>
<p><strong>Metric note.</strong> Headline metric is <strong>AUPRC</strong> per WRITEUP/eval-design.md §5.1 (“the most relevant ranking metric for class-imbalanced tasks where precision and recall both matter”). Random-predictor AUPRC equals the positive-class prevalence on each slice. AUROC (chance baseline 0.5, prior-independent) is reported as a secondary diagnostic for cross-paper comparison.</p>
<p>Source data: <code>evals/metrics/per_cell.parquet</code> (per-cell, post-Item-4 single-class filter), <code>evals/bootstrap/marginal_cells.parquet</code> (BCa CI per ADR-022), <code>evals/bootstrap/paired_cells.parquet</code> + <code>paired_cells_seed2.parquet</code> (paired-Δ CI per ADR-022), <code>evals/audit/mde_per_cell.parquet</code>, <code>evals/operating_points/dual_policy.parquet</code> (72 op-points).</p>
<section id="the-iid-vs-ood-gap-primary-narrative" class="level3">
<h3 class="anchored" data-anchor-id="the-iid-vs-ood-gap-primary-narrative">The IID-vs-OOD gap (primary narrative)</h3>
<p>Per-rung marginal AUPRC + BCa 95 % CI (seed=1 headline; seed=2 stability check 0/40 cells flagged at 5 pct threshold per ADR-022 + A-008):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Rung</th>
<th>jbb_behaviors AUPRC</th>
<th>xstest AUPRC</th>
<th>pooled_ood AUPRC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TF-IDF + LR (classical floor)</td>
<td>0.470 [0.443, 0.496]</td>
<td>0.395 [0.379, 0.410]</td>
<td>0.291 [0.283, 0.298]</td>
</tr>
<tr class="even">
<td>frozen-probe</td>
<td>0.552 [0.520, 0.580]</td>
<td>0.468 [0.448, 0.486]</td>
<td>0.364 [0.354, 0.375]</td>
</tr>
<tr class="odd">
<td>LoRA</td>
<td>0.535 [0.504, 0.563]</td>
<td>0.467 [0.447, 0.486]</td>
<td>0.293 [0.286, 0.301]</td>
</tr>
<tr class="even">
<td>ProtectAI v1</td>
<td>0.519 [0.437, 0.597]</td>
<td>0.469 [0.415, 0.523]</td>
<td>0.361 [0.330, 0.391]</td>
</tr>
<tr class="odd">
<td>ProtectAI v2</td>
<td>0.556 [0.453, 0.648]</td>
<td>0.382 [0.333, 0.429]</td>
<td>0.314 [0.283, 0.345]</td>
</tr>
</tbody>
</table>
<p>Pooled_ood positive-class prevalence: <strong>0.374</strong> (15 656 positives / 41 838 rows). Random-predictor AUPRC on <code>pooled_ood</code> equals 0.374.</p>
<p>The gap pattern:</p>
<ul>
<li><strong>frozen-probe</strong> is the strongest on <code>pooled_ood</code> (0.364 [0.354, 0.375]) — but lands ~0.01 below the prevalence baseline (0.374). The CI upper bound (0.375) just barely touches the baseline. Even the best trained rung does not lift above what a positive-class-prior predictor would produce by AUPRC.</li>
<li><strong>LoRA’s <code>pooled_ood</code> AUPRC (0.293)</strong> is essentially tied with the classical floor (0.291; within CI overlap) and far below frozen-probe (-0.071 AUPRC; paired-bootstrap CI does not include zero on this comparison). <strong>LoRA fine-tuning hurts OOD generalization</strong> relative to the frozen probe — a known phenomenon when the fine-tuning distribution mismatch is large.</li>
<li><strong>TF-IDF + LR</strong> is competitive on <code>pooled_ood</code> (0.291) and only modestly below the trained rungs on jbb_behaviors / xstest. The classical floor is hard to beat without much stronger inductive biases.</li>
<li><strong>ProtectAI v2</strong> beats ProtectAI v1 on jbb_behaviors (0.556 vs 0.519) but loses on xstest (0.382 vs 0.469) — version-to-version updates do not monotonically improve across distributions.</li>
</ul>
<p><strong>AUROC secondary view</strong> (chance baseline 0.5, prior-independent): <code>pooled_ood</code> AUROC range is 0.371–0.515; only frozen-probe at 0.515 [0.505, 0.525] clears chance with margin. The relative ordering reads identically to the AUPRC narrative; AUPRC is reported in the headline because it accounts for the class prior (per WRITEUP/eval-design.md §5.1).</p>
<p>Per-scorer contamination findings (ProtectAI v1 + v2) detail lives in <a href="./WRITEUP/reference-scorer-audit.html"><code>WRITEUP/reference-scorer-audit.md</code></a> and <a href="./EVIDENCE.html"><code>EVIDENCE.md</code></a> §1-2.</p>
</section>
<section id="which-capabilities-help-ood-vs-only-help-iid" class="level3">
<h3 class="anchored" data-anchor-id="which-capabilities-help-ood-vs-only-help-iid">Which capabilities help OOD vs only help IID</h3>
<p>Rung-by-rung lift over the classical floor (delta AUPRC, <code>pooled_ood</code>):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Rung vs floor</th>
<th>delta AUPRC (pooled_ood)</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frozen-probe vs tfidf-lr</td>
<td>+0.073</td>
<td>Pretrained ModernBERT embeddings DO help OOD — modest lift</td>
</tr>
<tr class="even">
<td>LoRA vs tfidf-lr</td>
<td>+0.002</td>
<td>Adapter fine-tuning collapses the frozen-probe advantage on OOD; essentially indistinguishable from classical floor</td>
</tr>
<tr class="odd">
<td>LoRA vs frozen-probe</td>
<td>-0.071</td>
<td>LoRA hurts; the adapter weights specialise to training distribution</td>
</tr>
<tr class="even">
<td>ProtectAI v1 vs tfidf-lr</td>
<td>+0.070</td>
<td>Off-the-shelf injection detector adds modest signal — comparable to frozen-probe lift</td>
</tr>
<tr class="odd">
<td>ProtectAI v2 vs tfidf-lr</td>
<td>+0.023</td>
<td>v2 update does not propagate to our OOD slate</td>
</tr>
</tbody>
</table>
<p>(AUROC equivalents for cross-paper comparison: frozen-probe +0.144; LoRA +0.012; LoRA vs frozen-probe -0.132; ProtectAI v1 +0.069; ProtectAI v2 +0.031. Same direction; AUROC magnitudes differ because AUROC is prior-independent while AUPRC weights by positive-class prevalence.)</p>
<p><strong>Implication</strong>: the pretrained backbone (ModernBERT) provides the bulk of the OOD generalization budget. Fine-tuning (LoRA) on the in-distribution training pool causes generalization-tax: the rung does better on the training-distribution-shaped jbb_behaviors / xstest slices, but loses on <code>pooled_ood</code>. This is the canonical fine-tuning-overfit signature.</p>
</section>
<section id="score-behaviour-at-the-two-operating-points" class="level3">
<h3 class="anchored" data-anchor-id="score-behaviour-at-the-two-operating-points">Score-behaviour at the two operating points</h3>
<p>Dual-policy thresholds fit on val per ADR-025 + ADR-050 (full-FT excluded; 3 trained rungs only). Mean per-cell achieved metrics on test (LODO held-out attack source):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rung</th>
<th>Policy</th>
<th style="text-align: right;">Mean threshold</th>
<th style="text-align: right;">Mean test recall</th>
<th style="text-align: right;">Mean test FPR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tfidf-lr</td>
<td>detection (FPR ≤ 1 %)</td>
<td style="text-align: right;">0.657</td>
<td style="text-align: right;">0.333</td>
<td style="text-align: right;">0.067</td>
</tr>
<tr class="even">
<td>tfidf-lr</td>
<td>verification (recall ≥ 99 %)</td>
<td style="text-align: right;">0.162</td>
<td style="text-align: right;">0.674</td>
<td style="text-align: right;">0.508</td>
</tr>
<tr class="odd">
<td>frozen-probe</td>
<td>detection</td>
<td style="text-align: right;">0.829</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="even">
<td>frozen-probe</td>
<td>verification</td>
<td style="text-align: right;">0.215</td>
<td style="text-align: right;">0.957</td>
<td style="text-align: right;">0.891</td>
</tr>
<tr class="odd">
<td>LoRA</td>
<td>detection</td>
<td style="text-align: right;">0.795</td>
<td style="text-align: right;">0.424</td>
<td style="text-align: right;">0.115</td>
</tr>
<tr class="even">
<td>LoRA</td>
<td>verification</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.724</td>
<td style="text-align: right;">0.411</td>
</tr>
</tbody>
</table>
<p>Two findings:</p>
<ol type="1">
<li><strong>All targets reachable on val</strong> (target_reachable=True for all 72 op-points), but <strong>the val→test transfer is large</strong>: detection-policy FPR creeps above target on every rung; verification-policy recall drops well below target on tfidf-lr + LoRA. The frozen-probe verification policy holds (mean test recall 0.957, close to 0.99 target) — but at catastrophic FPR (0.891).</li>
<li><strong>The verification regime is fundamentally limited on LODO</strong>: held-out attack sources produce test distributions different enough from val that any “guarantee recall ≥ 99 %” threshold has either tiny test recall (LoRA: 0.724) or near-100 % test FPR (frozen-probe: 0.891).</li>
</ol>
<p>For the full narrative + reachability-audit detail see <a href="./WRITEUP/threshold-policy.html"><code>WRITEUP/threshold-policy.md</code></a>.</p>
</section>
<section id="calibration-findings" class="level3">
<h3 class="anchored" data-anchor-id="calibration-findings">Calibration findings</h3>
<p>Per-rung mean across both-class slices:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rung</th>
<th style="text-align: right;">Mean ECE (equal-mass)</th>
<th style="text-align: right;">Mean Brier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frozen-probe</td>
<td style="text-align: right;">0.144</td>
<td style="text-align: right;">0.265</td>
</tr>
<tr class="even">
<td>tfidf-lr</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;">0.376</td>
</tr>
<tr class="odd">
<td>LoRA</td>
<td style="text-align: right;">0.444</td>
<td style="text-align: right;">0.451</td>
</tr>
<tr class="even">
<td>ProtectAI v1</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.470</td>
</tr>
<tr class="odd">
<td>ProtectAI v2</td>
<td style="text-align: right;">0.460</td>
<td style="text-align: right;">0.471</td>
</tr>
</tbody>
</table>
<p><strong>Finding</strong>: frozen-probe has the BEST calibration on both-class OOD slices (ECE 0.144; Brier 0.265). LoRA fine-tuning DEGRADES calibration substantially (ECE 0.444 — 3× worse than frozen-probe). This is consistent with the per-row finding that LoRA over-confidently mis-classifies OOD examples; both the discrimination AND the calibration of the head distribution shift away from honest probabilistic estimates after fine-tuning. ProtectAI v1/v2 both show high ECE (~0.45+) which is consistent with their out-of-distribution scoring against our slate.</p>
</section>
<section id="frozen-probe-vs-adapter-fine-tuned-paired-bootstrap" class="level3">
<h3 class="anchored" data-anchor-id="frozen-probe-vs-adapter-fine-tuned-paired-bootstrap">Frozen probe vs adapter fine-tuned (paired bootstrap)</h3>
<p>Per ADR-022 paired-bootstrap (percentile-method, 10K resamples × 2 seeds; 0/40 stability flags at 5 pct threshold):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Slice</th>
<th>Metric</th>
<th style="text-align: right;">delta (b − a)</th>
<th style="text-align: right;">95 % CI</th>
<th>Conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frozen-probe vs LoRA</td>
<td>jbb_behaviors</td>
<td>AUPRC</td>
<td style="text-align: right;">−0.016</td>
<td style="text-align: right;">[−0.024, −0.009]</td>
<td>LoRA worse; CI clears zero</td>
</tr>
<tr class="even">
<td>frozen-probe vs LoRA</td>
<td>jbb_behaviors</td>
<td>AUROC</td>
<td style="text-align: right;">−0.014</td>
<td style="text-align: right;">[−0.021, −0.006]</td>
<td>LoRA worse; CI clears zero</td>
</tr>
<tr class="odd">
<td>frozen-probe vs LoRA</td>
<td>xstest</td>
<td>AUPRC</td>
<td style="text-align: right;">−0.001</td>
<td style="text-align: right;">[−0.006, +0.004]</td>
<td>Indistinguishable; CI crosses zero</td>
</tr>
<tr class="even">
<td>frozen-probe vs LoRA</td>
<td>xstest</td>
<td>AUROC</td>
<td style="text-align: right;">−0.007</td>
<td style="text-align: right;">[−0.013, −0.002]</td>
<td>LoRA marginally worse; CI clears zero</td>
</tr>
</tbody>
</table>
<p><strong>Headline</strong>: LoRA fine-tuning is <em>not</em> a free lunch on this task. On 3 of 4 slice × metric comparisons against frozen-probe, LoRA is significantly worse at the 95 % level. The adapter weights specialise to the training distribution, costing the model the OOD generalization that the pretrained backbone alone provided.</p>
</section>
<section id="the-headline-characterisation-claims" class="level3">
<h3 class="anchored" data-anchor-id="the-headline-characterisation-claims">The headline characterisation claims</h3>
<p>Distilled summary:</p>
<ul>
<li><strong>Claim 1</strong>: No rung in the trained-or-reference slate clears the <code>pooled_ood</code> positive-class prevalence baseline (0.374) under AUPRC. The best rung (frozen-probe AUPRC 0.364 [0.354, 0.375]) lands ~0.01 below the prevalence baseline; the CI upper bound just barely touches it. By AUROC (chance baseline 0.5), only frozen-probe at 0.515 [0.505, 0.525] clears chance with margin. The case-study lesson: “honest OOD generalization for prompt-injection classifiers is harder than the in-distribution numbers suggest” — not “look at this great classifier”.</li>
<li><strong>Claim 2</strong>: LoRA fine-tuning <em>hurts</em> OOD generalization relative to the frozen probe. Paired bootstrap on jbb_behaviors AUPRC delta = −0.016 [−0.024, −0.009]; <code>pooled_ood</code> AUPRC delta = −0.071 (AUROC equivalent: −0.014 jbb_behaviors; −0.132 <code>pooled_ood</code> — same direction). The adapter weights specialise to the training distribution. Pretrained backbone embeddings carry the OOD generalization budget; fine-tuning consumes it.</li>
<li><strong>Claim 3</strong>: ProtectAI v1 → v2 is <em>not</em> a monotone improvement across the OOD slate: v2 beats v1 on jbb_behaviors (+0.037 AUPRC; +0.06 AUROC) and loses on xstest (-0.087 AUPRC; -0.15 AUROC). Off-the-shelf detector updates can regress on specific OOD distributions; downstream consumers should not assume v2 dominates v1 universally.</li>
<li><strong>Claim 4</strong>: Dual-policy thresholds fit on val do not transfer to LODO test. Detection-policy FPR creeps 1-12 % on test vs 1 % val target across all 3 trained rungs; verification-policy recall drops well below target on 2 of 3 rungs. The val→LODO gap is the dominant calibration story; per-rung temperature scaling would not fix it without OOD-aware threshold selection.</li>
</ul>
<p>Each claim is supported by a specific row × CI above, not a hand-wave.</p>
<p><strong>Linked ADRs</strong>: ADR-018 (reference slate; partially superseded by ADR-050), ADR-019 (transformer training recipe), ADR-021 (slice aggregation), ADR-022 (statistical inference apparatus), ADR-024 (cross-fold CI), ADR-025 (dual-policy operating points), ADR-046 (Phase 4 analysis bundle), ADR-050 (rung-slate narrowing — LLM judges + full-FT OOD drops).</p>
<p><strong>Known gaps</strong>: per-fold calibration-battery + temperature/isotonic fitting outputs not exercised this Phase 5; per-row predictions for full-FT OOD ABSENT (FUSE EIO crash per ADR-050). Canonical-data wire-up of figures F1–F7 pending upstream eval-toolkit issues #14–#16 + #22.</p>
</section>
<section id="takeaways-for-the-intro-only-reader" class="level3">
<h3 class="anchored" data-anchor-id="takeaways-for-the-intro-only-reader">Takeaways (for the intro-only reader)</h3>
<p>Three takeaways for the reviewer who reads only §1 + §1.5 + §2 + §Results.</p>
<ol type="1">
<li><p><strong>What was characterised.</strong> A 5-rung ladder (TF-IDF+LR classical floor + ModernBERT-base frozen-probe + ModernBERT-base LoRA + ProtectAI v1 + ProtectAI v2) on 5 OOD slices spanning the five injection types in §1.5: <code>direct_injection</code>, <code>indirect_injection</code>, <code>agentic_flow_injection</code>, <code>jailbreak_as_question</code>, <code>false_positive_probe</code>. <strong>Single-turn English text classification only</strong>, with bootstrap CIs + paired-bootstrap rung-vs-rung + calibration battery + dual-policy thresholds per ADR-022 / ADR-023 / ADR-025.</p></li>
<li><p><strong>What the OOD wall reveals — read against the §1.5 train/test table.</strong> The OOD slate is hardest on the injection types <em>not</em> in the training pool. BIPIA (the only <code>indirect_injection</code> slate) and InjecAgent (the only <code>agentic_flow_injection</code> slate) both have zero counterparts in the 4 LODO training sources. The trained transformer rungs land at or below the <code>pooled_ood</code> positive-class prevalence baseline of 0.374 under AUPRC (frozen-probe 0.364; LoRA 0.293; classical floor 0.291). <strong>LoRA’s <code>pooled_ood</code> AUPRC is essentially tied with the classical floor and -0.071 below frozen-probe</strong> — fine-tuning the head onto direct-injection training data DECREASES OOD generalization vs leaving the pretrained backbone embeddings intact. <strong>The pretrained backbone — not the LODO training pool — carries what little OOD generalization budget exists</strong>, and even that doesn’t lift above the prevalence baseline in absolute terms. On the injection types that <em>are</em> in training (<code>direct_injection</code> via jbb_behaviors partial; <code>jailbreak_as_question</code> via XSTest), the trained rungs do modestly better but still cluster in a tight band around 0.47–0.55 AUPRC. By AUROC (chance baseline 0.5), only frozen-probe at 0.515 [0.505, 0.525] clears chance with margin; LoRA at 0.383 falls below. <em>In short: the rung ladder is doing approximately as well as could be expected given what it was shown, and the OOD gap quantifies what training data alone cannot fix.</em></p></li>
<li><p><strong>What’s deferred, what to take away.</strong> Multi-turn agentic flows, encoded payloads, paraphrase attacks, and adversarial perturbations are NOT tested (per §Scope above). A deployment context that includes those attack classes cannot rely on these numbers; <a href="./WRITEUP/limitations-and-future-work.html"><code>WRITEUP/limitations-and-future-work.md</code></a> §9.4 names what would need to land to extend coverage (OOD-aware training data, backbone scaling, OOD-aware threshold selection). <strong>The honest reading</strong>: this is a methodology + capability <em>characterisation</em>, not a leaderboard claim. The headline finding — <em>fine-tuning consumes the OOD generalization budget the pretrained backbone provides</em> — is methodologically richer than a “great classifier” framing would have allowed.</p></li>
</ol>
<hr>
</section>
</section>
<section id="lessons-brief" class="level2">
<h2 class="anchored" data-anchor-id="lessons-brief">Lessons (brief)</h2>
<p>Long form in <a href="./WRITEUP/limitations-and-future-work.html"><code>WRITEUP/limitations-and-future-work.md</code></a> §11. Punch lines:</p>
<ul>
<li>The OOD generalization wall is the dominant signal; honest framing surfaces it where a “great classifier” framing would have hidden it.</li>
<li>The SDD process bought reproducibility + audit trail at the cost of a ~50-decision Phase 0 interview flow. ADR-050 (rung-slate narrowing) is the supersession-on-supersession proof point — when reality forced a methodology drift, the discipline ate it cleanly.</li>
<li>The library-first invariant retrofit (ADR-047) was a discipline lapse caught at Phase 4 entry and recovered in one carryforward refactor. The cost-overrun on LLM judges (ADR-050 driver 1) was a similar lapse — original estimate didn’t account for actual token volume.</li>
<li>FUSE-on-RunPod is a non-deterministic bug class; ~50 % of cumulative spend ($15.74) was FUSE-recovery overhead. Filed upstream issues + PRs at brandon-behring/runpod-deploy.</li>
<li>Per-step commits + 2-checkpoint push cadence survived multi-day context auto-compaction.</li>
</ul>
<hr>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">12. Appendix</h2>
<section id="a.-glossary" class="level3">
<h3 class="anchored" data-anchor-id="a.-glossary">A. Glossary</h3>
<ul>
<li><strong>Detection policy</strong> — threshold selection targeting FPR ≤ 1 % on validation; characterises high-recall-low-FP behaviour.</li>
<li><strong>Verification policy</strong> — threshold selection targeting FNR ≤ 1 % on validation; characterises high-precision-on-clean behaviour.</li>
<li><strong>LODO</strong> — leave-one-dataset-out cross-validation; source-disjoint k-fold where each fold holds out an entire dataset source.</li>
<li><strong>LoRA</strong> — Low-Rank Adaptation; parameter-efficient fine-tuning method.</li>
<li><strong>PR-AUC</strong> — area under the precision-recall curve; threshold-free ranking metric for class-imbalanced tasks.</li>
<li><strong>ECE</strong> — expected calibration error; mean absolute gap between predicted-probability bins and observed frequencies.</li>
<li><strong>MDE</strong> — minimum detectable effect; the smallest difference your sample size can reliably detect at a given power.</li>
<li><strong>IID</strong> — independent and identically distributed; evaluation on data drawn from the same source/distribution as training.</li>
<li><strong>OOD</strong> — out-of-distribution; evaluation on data deliberately drawn from a different source or distribution.</li>
<li><strong>Rung ladder</strong> — a sequence of classifiers of increasing complexity, designed so each step’s lift decomposes which capability is responsible.</li>
</ul>
</section>
<section id="b.-adr-index" class="level3">
<h3 class="anchored" data-anchor-id="b.-adr-index">B. ADR index</h3>
<p><a href="./decisions/README.html"><code>decisions/README.md</code></a> — single version-neutral sequence; ADRs supersede prior ones via the standard <code>superseded-by-ADR-N</code> mechanism.</p>
</section>
<section id="c.-assumption-ledger" class="level3">
<h3 class="anchored" data-anchor-id="c.-assumption-ledger">C. Assumption ledger</h3>
<p><a href="./assumptions.html"><code>assumptions.md</code></a> — every assumption with severity ≥ medium appears in <a href="./WRITEUP/limitations-and-future-work.html"><code>WRITEUP/limitations-and-future-work.md</code></a> §8.2.</p>
</section>
<section id="d.-audit-trail" class="level3">
<h3 class="anchored" data-anchor-id="d.-audit-trail">D. Audit trail</h3>
<p><a href="./EVIDENCE.html"><code>EVIDENCE.md</code></a> — what external evidence was verified, what couldn’t be, what was left unresolved.</p>
</section>
<section id="e.-linked-claude-transcripts" class="level3">
<h3 class="anchored" data-anchor-id="e.-linked-claude-transcripts">E. Linked Claude transcripts</h3>
<p>Transcripts referenced by ADR <code>transcript:</code> frontmatter fields are bundled and emailed to the reviewer at submission time per <code>transcripts/README.md</code>; the <code>/save-transcript</code> skill produces them.</p>
</section>
<section id="f.-eval-toolkit-methodology-curriculum" class="level3">
<h3 class="anchored" data-anchor-id="f.-eval-toolkit-methodology-curriculum">F. eval-toolkit methodology curriculum</h3>
<p><a href="https://github.com/brandon-behring/eval-toolkit/tree/main/docs/methodology"><code>docs/methodology/</code></a> — 17-chapter curriculum. Cross-linked from each WRITEUP/ spoke.</p>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/brandon-behring\.github\.io\/prompt-injection-detection-prototype\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Prompt-injection classification — methodology + capability characterisation</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>**Author**: Brandon Behring · **Date**: 2026-05-18 · **Status**: <span class="in">`v1.0.0`</span> submission tag (Phase 5 close)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>This document is the **TOC + landing page**: the cover narrative</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>(§1 Motivation, §2 Approach overview, §Results, §Lessons,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>§Appendix) lives here; the detailed sections live as spokes</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>under <span class="co">[</span><span class="ot">`WRITEUP/`</span><span class="co">](./WRITEUP/)</span> (linked below).</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading guide</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Spoke <span class="pp">|</span> Coverage <span class="pp">|</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/data-decisions.md`</span><span class="co">](./WRITEUP/data-decisions.md)</span> <span class="pp">|</span> §3 Data design — source slate selection + dedup + leakage + LODO splits <span class="pp">|</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/model-rungs.md`</span><span class="co">](./WRITEUP/model-rungs.md)</span> <span class="pp">|</span> §4 Rung ladder — classical floor + ModernBERT × {frozen-probe, LoRA, full-FT} + ProtectAI v1/v2 <span class="pp">|</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/eval-design.md`</span><span class="co">](./WRITEUP/eval-design.md)</span> <span class="pp">|</span> §5.1, §5.2, §5.4, §5.5 — metric battery + paired-bootstrap + MDE + calibration + OOD slate composition <span class="pp">|</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/threshold-policy.md`</span><span class="co">](./WRITEUP/threshold-policy.md)</span> <span class="pp">|</span> §5.3 — dual-policy detection + verification operating points + val→test reachability <span class="pp">|</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/reference-scorer-audit.md`</span><span class="co">](./WRITEUP/reference-scorer-audit.md)</span> <span class="pp">|</span> §3.3 + §5.6 + §7.2/3 — ADR-005 contamination taxonomy applied to reference scorers + adversarial-robustness scope <span class="pp">|</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/methodology-guarantees.md`</span><span class="co">](./WRITEUP/methodology-guarantees.md)</span> <span class="pp">|</span> §6 Tooling — eval-toolkit + runpod-deploy + SDD process + library-first invariant <span class="pp">|</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/limitations-and-future-work.md`</span><span class="co">](./WRITEUP/limitations-and-future-work.md)</span> <span class="pp">|</span> §8 scope deferrals + §8.2 methodology caveats + §9 negative results + §11 lessons <span class="pp">|</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="co">[</span><span class="ot">`WRITEUP/reproducibility.md`</span><span class="co">](./WRITEUP/reproducibility.md)</span> <span class="pp">|</span> §10 T0 + T1 + T3 reproduction tiers <span class="pp">|</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>For the audit trail of external-evidence claims, see <span class="co">[</span><span class="ot">`EVIDENCE.md`</span><span class="co">](./EVIDENCE.md)</span>.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>For the per-decision ADR record, see <span class="co">[</span><span class="ot">`decisions/`</span><span class="co">](./decisions/)</span> +</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`SUBMISSION_AUDIT.md`</span><span class="co">](./SUBMISSION_AUDIT.md)</span>.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Motivation</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; My main concern after reading the literature: most prompt-injection detectors are evaluated on data that leaks into training, so their reported OOD numbers don't tell you much. A classifier that cross-validates on a single direct-prompt-injection dataset is trivial to build, but it gives a poor read on OOD performance and raises real leakage concerns. This project is my attempt to build a fairer evaluation harness around that — not to find the best model, but to lay the groundwork for fairer evaluation and to identify weaknesses of our model and of some existing reference scorers.</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>Prompt-injection — text designed to override or subvert the instructions an LLM-based system is operating under — is one of the load-bearing failure modes for any system that exposes an LLM to untrusted input. Ciphero's verification-layer thesis is that we cannot govern what we cannot verify; one primitive in that stack is a classifier that scores whether a span of text is an injection attempt.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>The same scores serve two operational contexts:</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Detection** — *catch injections coming in*. Tolerates false positives more than false negatives (an alert costs less than a missed attack at the input boundary).</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Verification** — *confirm clean text actually is clean*. Tolerates false negatives more than false positives (a confidently-clean assertion is the dangerous one).</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>These are not two classifiers; they are two threshold policies on the same scores, with different cost weights. See <span class="co">[</span><span class="ot">`WRITEUP/threshold-policy.md`</span><span class="co">](./WRITEUP/threshold-policy.md)</span> for how the same primitive is configured to characterise both.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>This writeup characterises a 5-rung ladder of prompt-injection classifiers — TF-IDF+LR classical floor + ModernBERT-base × {frozen-probe, LoRA, full-FT} + ProtectAI v1 + ProtectAI v2 reference scorers (locked at Phase 0-03 per ADR-015 + ADR-017 + ADR-018 + ADR-050 + ADR-052) — across an OOD slate, with the question: *what does each capability layer add, and where does the IID/OOD gap fall?* The work is **methodology + capability characterisation braided**: the ladder is the instrument; the eval methodology rigor is what makes the characterisation defensible; the brief's two asks (models of increasing complexity + OOD coverage) are the targets.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>**Honest-OOD thesis**: IID numbers are the easy part. The interesting question for any classifier that might one day touch a deployment surface is *which capabilities help when the distribution shifts, and which ones only inflate the IID number*. That question — not "what's the best PR-AUC" — drives this document's structure.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>**Deployment is not on the roadmap.** This is characterisation, not recommendation. No rung is promoted as the deployment choice; each rung's trade-offs are reported and the reader is left to draw their own deployment conclusions if they have one to make.</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>**Linked ADRs**: ADR-001 (brief alignment), ADR-013 (deliverable scope + WRITEUP shape), ADR-017 (rung-slate expansion).</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scope (single-turn English text classifier)</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>This submission characterises a *prompt-injection text classifier* on an English-only fixed slate (4 LODO training sources + 5 OOD test slices). What is **deliberately out of scope** (per ADR-014 + [`WRITEUP/limitations-and-future-work.md`](./WRITEUP/limitations-and-future-work.md) §8.1; named explicitly so a reviewer reading only this section knows what the numbers do *not* cover):</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Multi-turn / agentic-flow injection** — payload split across multiple conversation turns or tool-use steps. *Named in the test slate via InjecAgent to quantify the gap; not detected by the single-turn classifier scope.*</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Encoded payloads** — base64 / leetspeak / hex / Unicode confusables / ROT13.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Paraphrase attacks** — semantic equivalents that don't share surface n-grams with training injections.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Adversarial perturbations** — gradient-guided or search-based evasion against a specific classifier.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Cross-language coverage** — the slate is English-only by source-slate construction.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Conformal prediction + adversarial red-teaming** — see WRITEUP/limitations-and-future-work.md §8.1.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>The work is **methodology + capability characterisation braided**: the ladder is the instrument; the eval methodology rigor is what makes the characterisation defensible. Deployment recommendations are explicitly out of scope.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1.5 Attack-type taxonomy + train/test composition</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>Five operationally-distinct injection types are relevant to this submission. Each type is defined in a single sentence; the table below maps which types appear in the 4 LODO training-pool sources vs the 5 OOD test slices. The mismatch is the load-bearing story for §Results — the OOD slate probes injection types that are *not* in the training pool.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>**Type definitions:**</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`direct_injection`** — adversarial text in the user's input attempting to override system instructions. Single-turn, in-channel. Examples: "ignore the above and …", "you are now …".</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`indirect_injection`** — adversarial text arriving via a context channel the LLM processes (a retrieved document, an email body, a tool's output). The user's *direct* input is benign; the injection rides on data the LLM was meant to consume.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`agentic_flow_injection`** — payload split across multi-turn tool-use; detecting it requires intermediate-state interception (tool-call args, function-output contamination), not just classifying a single text span.</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`jailbreak_as_question`** — safety-bypass framed as a legitimate-looking question rather than an instruction override (e.g., "for a story I'm writing, how would a character …").</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`false_positive_probe`** — benign text structurally similar to injections (e.g., literal discussions of injection attacks). Tests whether the classifier discriminates *intent* from *form*.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>**Train/test composition** — <span class="in">`Y`</span> = type present (or dominantly present in that source); <span class="in">`-`</span> = type absent. Training sources locked per ADR-016; OOD slices per ADR-021.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Injection type <span class="pp">|</span> TRAIN: <span class="in">`deepset/prompt-injections`</span> <span class="pp">|</span> TRAIN: <span class="in">`Lakera/gandalf_ignore_instructions`</span> <span class="pp">|</span> TRAIN: <span class="in">`Lakera/mosscap_prompt_injection`</span> <span class="pp">|</span> TRAIN: <span class="in">`hackaprompt/hackaprompt-dataset`</span> <span class="pp">|</span> TEST: <span class="in">`bipia`</span> <span class="pp">|</span> TEST: <span class="in">`injecagent`</span> <span class="pp">|</span> TEST: <span class="in">`jbb_behaviors`</span> <span class="pp">|</span> TEST: <span class="in">`xstest`</span> <span class="pp">|</span> TEST: <span class="in">`notinject`</span> <span class="pp">|</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span>:--:<span class="pp">|</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`direct_injection`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> partial <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`indirect_injection`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`agentic_flow_injection`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`jailbreak_as_question`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> partial <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`false_positive_probe`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`-`</span> <span class="pp">|</span> <span class="in">`Y`</span> <span class="pp">|</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>**Key reads from the table:**</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The 4 LODO training sources are **direct-injection-heavy**. The training pool teaches the classifier to recognise instruction-override style attacks in user input.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>BIPIA (test) is the **only indirect-injection slate**; *zero* indirect-injection coverage in training. This is a structural train/test mismatch by design — the OOD wall on BIPIA quantifies it.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>InjecAgent (test) is the **only agentic-flow slate**; *zero* agentic-flow coverage in training. Agentic flow is also out-of-scope for the single-turn classifier per §Scope above — InjecAgent is included in the test set to quantify the gap, not because we expect the classifier to do well.</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>NotInject (test) is a **pure false-positive probe**; no counterpart in training. Tests intent-vs-form discrimination.</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>JBB-Behaviors + XSTest (test) carry jailbreak-as-question style attacks. HackAPrompt partially covers this; the other 3 training sources do not.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>The §Results section reads against this table — performance per OOD slice tracks whether that slice's injection type is represented in the training pool.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>**Note on what "OOD" means here.** "In-domain test" is still a direct-injection attack — just an unseen source held out by LODO. The 5-slice "OOD" slate is something else entirely: **indirect injection via email-body context (BIPIA), multi-turn agentic-flow attacks (InjecAgent), jailbreaks (JBB-Behaviors), and benign-but-injection-shaped texts that test false-positive robustness (NotInject, XSTest).** The OOD wall in §Results is **cross-family**, not cross-source: the trained rungs are tested on attack types absent from their training pool. Direct prompt-injection training and evaluation performance alone do not translate into these other attack families — that is the load-bearing finding of this submission.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Approach overview</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>The brief asked for two things: *models of increasing complexity* and *the right amount of OOD coverage*. The rung ladder satisfies the first ask and is the **instrument** for the second: when a rung helps IID but not OOD, that tells us its added capability is data-pattern-fitting rather than generalisation; when a rung helps both, the added capability is more durable.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Element <span class="pp">|</span> Role <span class="pp">|</span> Why <span class="pp">|</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rung ladder (locked Phase 0-03 per ADR-015 + ADR-017 + ADR-050) <span class="pp">|</span> Instrument <span class="pp">|</span> Each step's lift over the previous decomposes *which capability* matters. <span class="pp">|</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> OOD slate (5 slices locked Phase 0-04 per ADR-016 + ADR-021) <span class="pp">|</span> Measurement <span class="pp">|</span> Quantifies what each capability adds when the distribution shifts. <span class="pp">|</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Dual cost-weight thresholds <span class="pp">|</span> Score-behaviour characterisation <span class="pp">|</span> Shows what the same scores deliver under two different operational cost regimes. <span class="pp">|</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Statistical rigor (CIs + paired comparisons + MDE) <span class="pp">|</span> Defensibility <span class="pp">|</span> Lets us claim differences honestly and quantify when we lack the power to claim anything. <span class="pp">|</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>We do **not** pick a deployment leader. The intent is to demonstrate what each rung delivers and where it breaks; readers with a specific deployment context can map our characterisation onto their cost constraints.</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>**Linked ADRs**: ADR-002 (approach scaffold), ADR-014 (single-backbone slate framing), ADR-017 (rung-slate expansion), ADR-021 (slice aggregation + headline-metric protocol).</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>**Known gaps**: this approach evaluates EACH rung against the same slate; cross-rung-ensemble strategies (e.g., LoRA-with-frozen-probe-temperature) are out of scope per the project compute budget.</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>**The negative result IS the result.** None of the rungs decisively beats the classical TF-IDF+LR floor on the 5-slice OOD slate, and the OOD wall is **cross-family** (read against the §1.5 train/test table): training pool is 4 direct-injection sources; OOD slate probes indirect injection via email-body context (BIPIA), multi-turn agentic-flow (InjecAgent), jailbreaks (JBB-Behaviors), and benign-but-injection-shaped texts that test false-positive robustness (NotInject, XSTest) — attack types absent from training. Direct prompt-injection training and evaluation performance alone do not translate into these other attack families. That finding is the argument for a fairer evaluation framework, which is what this project is.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>Specifically: across the rung ladder + two reference scorers, **none of the rungs clears the `pooled_ood` positive-class prevalence baseline (0.374) under AUPRC** (range 0.291–0.364; even frozen-probe at 0.364 lands just under prevalence). The trained transformer rungs (frozen-probe + LoRA) and the ProtectAI reference scorers cluster within a band that is statistically distinguishable on the in-distribution-like slices (jbb_behaviors, xstest) but compresses to at-or-below the prevalence baseline on pooled_ood. The story is not "the ladder works" — it is *the ladder works on IID-shaped attacks and fails to generalize to genuinely OOD distributions*, and the numbers below back that up.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>**Metric note.** Headline metric is **AUPRC** per WRITEUP/eval-design.md §5.1 ("the most relevant ranking metric for class-imbalanced tasks where precision and recall both matter"). Random-predictor AUPRC equals the positive-class prevalence on each slice. AUROC (chance baseline 0.5, prior-independent) is reported as a secondary diagnostic for cross-paper comparison.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>Source data: <span class="in">`evals/metrics/per_cell.parquet`</span> (per-cell, post-Item-4 single-class filter), <span class="in">`evals/bootstrap/marginal_cells.parquet`</span> (BCa CI per ADR-022), <span class="in">`evals/bootstrap/paired_cells.parquet`</span> + <span class="in">`paired_cells_seed2.parquet`</span> (paired-Δ CI per ADR-022), <span class="in">`evals/audit/mde_per_cell.parquet`</span>, <span class="in">`evals/operating_points/dual_policy.parquet`</span> (72 op-points).</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="fu">### The IID-vs-OOD gap (primary narrative)</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>Per-rung marginal AUPRC + BCa 95 % CI (seed=1 headline; seed=2 stability check 0/40 cells flagged at 5 pct threshold per ADR-022 + A-008):</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rung <span class="pp">|</span> jbb_behaviors AUPRC <span class="pp">|</span> xstest AUPRC <span class="pp">|</span> pooled_ood AUPRC <span class="pp">|</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TF-IDF + LR (classical floor) <span class="pp">|</span> 0.470 <span class="co">[</span><span class="ot">0.443, 0.496</span><span class="co">]</span> <span class="pp">|</span> 0.395 <span class="co">[</span><span class="ot">0.379, 0.410</span><span class="co">]</span> <span class="pp">|</span> 0.291 <span class="co">[</span><span class="ot">0.283, 0.298</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe <span class="pp">|</span> 0.552 <span class="co">[</span><span class="ot">0.520, 0.580</span><span class="co">]</span> <span class="pp">|</span> 0.468 <span class="co">[</span><span class="ot">0.448, 0.486</span><span class="co">]</span> <span class="pp">|</span> 0.364 <span class="co">[</span><span class="ot">0.354, 0.375</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA <span class="pp">|</span> 0.535 <span class="co">[</span><span class="ot">0.504, 0.563</span><span class="co">]</span> <span class="pp">|</span> 0.467 <span class="co">[</span><span class="ot">0.447, 0.486</span><span class="co">]</span> <span class="pp">|</span> 0.293 <span class="co">[</span><span class="ot">0.286, 0.301</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v1 <span class="pp">|</span> 0.519 <span class="co">[</span><span class="ot">0.437, 0.597</span><span class="co">]</span> <span class="pp">|</span> 0.469 <span class="co">[</span><span class="ot">0.415, 0.523</span><span class="co">]</span> <span class="pp">|</span> 0.361 <span class="co">[</span><span class="ot">0.330, 0.391</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v2 <span class="pp">|</span> 0.556 <span class="co">[</span><span class="ot">0.453, 0.648</span><span class="co">]</span> <span class="pp">|</span> 0.382 <span class="co">[</span><span class="ot">0.333, 0.429</span><span class="co">]</span> <span class="pp">|</span> 0.314 <span class="co">[</span><span class="ot">0.283, 0.345</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>Pooled_ood positive-class prevalence: **0.374** (15 656 positives / 41 838 rows). Random-predictor AUPRC on <span class="in">`pooled_ood`</span> equals 0.374.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>The gap pattern:</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**frozen-probe** is the strongest on <span class="in">`pooled_ood`</span> (0.364 <span class="co">[</span><span class="ot">0.354, 0.375</span><span class="co">]</span>) — but lands ~0.01 below the prevalence baseline (0.374). The CI upper bound (0.375) just barely touches the baseline. Even the best trained rung does not lift above what a positive-class-prior predictor would produce by AUPRC.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**LoRA's `pooled_ood` AUPRC (0.293)** is essentially tied with the classical floor (0.291; within CI overlap) and far below frozen-probe (-0.071 AUPRC; paired-bootstrap CI does not include zero on this comparison). **LoRA fine-tuning hurts OOD generalization** relative to the frozen probe — a known phenomenon when the fine-tuning distribution mismatch is large.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**TF-IDF + LR** is competitive on <span class="in">`pooled_ood`</span> (0.291) and only modestly below the trained rungs on jbb_behaviors / xstest. The classical floor is hard to beat without much stronger inductive biases.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**ProtectAI v2** beats ProtectAI v1 on jbb_behaviors (0.556 vs 0.519) but loses on xstest (0.382 vs 0.469) — version-to-version updates do not monotonically improve across distributions.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>**AUROC secondary view** (chance baseline 0.5, prior-independent): <span class="in">`pooled_ood`</span> AUROC range is 0.371–0.515; only frozen-probe at 0.515 <span class="co">[</span><span class="ot">0.505, 0.525</span><span class="co">]</span> clears chance with margin. The relative ordering reads identically to the AUPRC narrative; AUPRC is reported in the headline because it accounts for the class prior (per WRITEUP/eval-design.md §5.1).</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>Per-scorer contamination findings (ProtectAI v1 + v2) detail lives in <span class="co">[</span><span class="ot">`WRITEUP/reference-scorer-audit.md`</span><span class="co">](./WRITEUP/reference-scorer-audit.md)</span> and <span class="co">[</span><span class="ot">`EVIDENCE.md`</span><span class="co">](./EVIDENCE.md)</span> §1-2.</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="fu">### Which capabilities help OOD vs only help IID</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>Rung-by-rung lift over the classical floor (delta AUPRC, <span class="in">`pooled_ood`</span>):</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rung vs floor <span class="pp">|</span> delta AUPRC (pooled_ood) <span class="pp">|</span> Interpretation <span class="pp">|</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe vs tfidf-lr <span class="pp">|</span> +0.073 <span class="pp">|</span> Pretrained ModernBERT embeddings DO help OOD — modest lift <span class="pp">|</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA vs tfidf-lr <span class="pp">|</span> +0.002 <span class="pp">|</span> Adapter fine-tuning collapses the frozen-probe advantage on OOD; essentially indistinguishable from classical floor <span class="pp">|</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA vs frozen-probe <span class="pp">|</span> -0.071 <span class="pp">|</span> LoRA hurts; the adapter weights specialise to training distribution <span class="pp">|</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v1 vs tfidf-lr <span class="pp">|</span> +0.070 <span class="pp">|</span> Off-the-shelf injection detector adds modest signal — comparable to frozen-probe lift <span class="pp">|</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v2 vs tfidf-lr <span class="pp">|</span> +0.023 <span class="pp">|</span> v2 update does not propagate to our OOD slate <span class="pp">|</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>(AUROC equivalents for cross-paper comparison: frozen-probe +0.144; LoRA +0.012; LoRA vs frozen-probe -0.132; ProtectAI v1 +0.069; ProtectAI v2 +0.031. Same direction; AUROC magnitudes differ because AUROC is prior-independent while AUPRC weights by positive-class prevalence.)</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>**Implication**: the pretrained backbone (ModernBERT) provides the bulk of the OOD generalization budget. Fine-tuning (LoRA) on the in-distribution training pool causes generalization-tax: the rung does better on the training-distribution-shaped jbb_behaviors / xstest slices, but loses on <span class="in">`pooled_ood`</span>. This is the canonical fine-tuning-overfit signature.</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="fu">### Score-behaviour at the two operating points</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>Dual-policy thresholds fit on val per ADR-025 + ADR-050 (full-FT excluded; 3 trained rungs only). Mean per-cell achieved metrics on test (LODO held-out attack source):</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rung <span class="pp">|</span> Policy <span class="pp">|</span> Mean threshold <span class="pp">|</span> Mean test recall <span class="pp">|</span> Mean test FPR <span class="pp">|</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---:|---:|---:|</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> tfidf-lr <span class="pp">|</span> detection (FPR ≤ 1 %) <span class="pp">|</span> 0.657 <span class="pp">|</span> 0.333 <span class="pp">|</span> 0.067 <span class="pp">|</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> tfidf-lr <span class="pp">|</span> verification (recall ≥ 99 %) <span class="pp">|</span> 0.162 <span class="pp">|</span> 0.674 <span class="pp">|</span> 0.508 <span class="pp">|</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe <span class="pp">|</span> detection <span class="pp">|</span> 0.829 <span class="pp">|</span> 0.063 <span class="pp">|</span> 0.010 <span class="pp">|</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe <span class="pp">|</span> verification <span class="pp">|</span> 0.215 <span class="pp">|</span> 0.957 <span class="pp">|</span> 0.891 <span class="pp">|</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA <span class="pp">|</span> detection <span class="pp">|</span> 0.795 <span class="pp">|</span> 0.424 <span class="pp">|</span> 0.115 <span class="pp">|</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA <span class="pp">|</span> verification <span class="pp">|</span> 0.019 <span class="pp">|</span> 0.724 <span class="pp">|</span> 0.411 <span class="pp">|</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>Two findings:</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**All targets reachable on val** (target_reachable=True for all 72 op-points), but **the val→test transfer is large**: detection-policy FPR creeps above target on every rung; verification-policy recall drops well below target on tfidf-lr + LoRA. The frozen-probe verification policy holds (mean test recall 0.957, close to 0.99 target) — but at catastrophic FPR (0.891).</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The verification regime is fundamentally limited on LODO**: held-out attack sources produce test distributions different enough from val that any "guarantee recall ≥ 99 %" threshold has either tiny test recall (LoRA: 0.724) or near-100 % test FPR (frozen-probe: 0.891).</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>For the full narrative + reachability-audit detail see <span class="co">[</span><span class="ot">`WRITEUP/threshold-policy.md`</span><span class="co">](./WRITEUP/threshold-policy.md)</span>.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="fu">### Calibration findings</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>Per-rung mean across both-class slices:</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rung <span class="pp">|</span> Mean ECE (equal-mass) <span class="pp">|</span> Mean Brier <span class="pp">|</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe <span class="pp">|</span> 0.144 <span class="pp">|</span> 0.265 <span class="pp">|</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> tfidf-lr <span class="pp">|</span> 0.350 <span class="pp">|</span> 0.376 <span class="pp">|</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LoRA <span class="pp">|</span> 0.444 <span class="pp">|</span> 0.451 <span class="pp">|</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v1 <span class="pp">|</span> 0.452 <span class="pp">|</span> 0.470 <span class="pp">|</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ProtectAI v2 <span class="pp">|</span> 0.460 <span class="pp">|</span> 0.471 <span class="pp">|</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>**Finding**: frozen-probe has the BEST calibration on both-class OOD slices (ECE 0.144; Brier 0.265). LoRA fine-tuning DEGRADES calibration substantially (ECE 0.444 — 3× worse than frozen-probe). This is consistent with the per-row finding that LoRA over-confidently mis-classifies OOD examples; both the discrimination AND the calibration of the head distribution shift away from honest probabilistic estimates after fine-tuning. ProtectAI v1/v2 both show high ECE (~0.45+) which is consistent with their out-of-distribution scoring against our slate.</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="fu">### Frozen probe vs adapter fine-tuned (paired bootstrap)</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>Per ADR-022 paired-bootstrap (percentile-method, 10K resamples × 2 seeds; 0/40 stability flags at 5 pct threshold):</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Comparison <span class="pp">|</span> Slice <span class="pp">|</span> Metric <span class="pp">|</span> delta (b − a) <span class="pp">|</span> 95 % CI <span class="pp">|</span> Conclusion <span class="pp">|</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---:|---:|---|</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe vs LoRA <span class="pp">|</span> jbb_behaviors <span class="pp">|</span> AUPRC <span class="pp">|</span> −0.016 <span class="pp">|</span> <span class="co">[</span><span class="ot">−0.024, −0.009</span><span class="co">]</span> <span class="pp">|</span> LoRA worse; CI clears zero <span class="pp">|</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe vs LoRA <span class="pp">|</span> jbb_behaviors <span class="pp">|</span> AUROC <span class="pp">|</span> −0.014 <span class="pp">|</span> <span class="co">[</span><span class="ot">−0.021, −0.006</span><span class="co">]</span> <span class="pp">|</span> LoRA worse; CI clears zero <span class="pp">|</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe vs LoRA <span class="pp">|</span> xstest <span class="pp">|</span> AUPRC <span class="pp">|</span> −0.001 <span class="pp">|</span> <span class="co">[</span><span class="ot">−0.006, +0.004</span><span class="co">]</span> <span class="pp">|</span> Indistinguishable; CI crosses zero <span class="pp">|</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> frozen-probe vs LoRA <span class="pp">|</span> xstest <span class="pp">|</span> AUROC <span class="pp">|</span> −0.007 <span class="pp">|</span> <span class="co">[</span><span class="ot">−0.013, −0.002</span><span class="co">]</span> <span class="pp">|</span> LoRA marginally worse; CI clears zero <span class="pp">|</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>**Headline**: LoRA fine-tuning is *not* a free lunch on this task. On 3 of 4 slice × metric comparisons against frozen-probe, LoRA is significantly worse at the 95 % level. The adapter weights specialise to the training distribution, costing the model the OOD generalization that the pretrained backbone alone provided.</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="fu">### The headline characterisation claims</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>Distilled summary:</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Claim 1**: No rung in the trained-or-reference slate clears the <span class="in">`pooled_ood`</span> positive-class prevalence baseline (0.374) under AUPRC. The best rung (frozen-probe AUPRC 0.364 <span class="co">[</span><span class="ot">0.354, 0.375</span><span class="co">]</span>) lands ~0.01 below the prevalence baseline; the CI upper bound just barely touches it. By AUROC (chance baseline 0.5), only frozen-probe at 0.515 <span class="co">[</span><span class="ot">0.505, 0.525</span><span class="co">]</span> clears chance with margin. The case-study lesson: "honest OOD generalization for prompt-injection classifiers is harder than the in-distribution numbers suggest" — not "look at this great classifier".</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Claim 2**: LoRA fine-tuning *hurts* OOD generalization relative to the frozen probe. Paired bootstrap on jbb_behaviors AUPRC delta = −0.016 <span class="co">[</span><span class="ot">−0.024, −0.009</span><span class="co">]</span>; <span class="in">`pooled_ood`</span> AUPRC delta = −0.071 (AUROC equivalent: −0.014 jbb_behaviors; −0.132 <span class="in">`pooled_ood`</span> — same direction). The adapter weights specialise to the training distribution. Pretrained backbone embeddings carry the OOD generalization budget; fine-tuning consumes it.</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Claim 3**: ProtectAI v1 → v2 is *not* a monotone improvement across the OOD slate: v2 beats v1 on jbb_behaviors (+0.037 AUPRC; +0.06 AUROC) and loses on xstest (-0.087 AUPRC; -0.15 AUROC). Off-the-shelf detector updates can regress on specific OOD distributions; downstream consumers should not assume v2 dominates v1 universally.</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Claim 4**: Dual-policy thresholds fit on val do not transfer to LODO test. Detection-policy FPR creeps 1-12 % on test vs 1 % val target across all 3 trained rungs; verification-policy recall drops well below target on 2 of 3 rungs. The val→LODO gap is the dominant calibration story; per-rung temperature scaling would not fix it without OOD-aware threshold selection.</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>Each claim is supported by a specific row × CI above, not a hand-wave.</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>**Linked ADRs**: ADR-018 (reference slate; partially superseded by ADR-050), ADR-019 (transformer training recipe), ADR-021 (slice aggregation), ADR-022 (statistical inference apparatus), ADR-024 (cross-fold CI), ADR-025 (dual-policy operating points), ADR-046 (Phase 4 analysis bundle), ADR-050 (rung-slate narrowing — LLM judges + full-FT OOD drops).</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>**Known gaps**: per-fold calibration-battery + temperature/isotonic fitting outputs not exercised this Phase 5; per-row predictions for full-FT OOD ABSENT (FUSE EIO crash per ADR-050). Canonical-data wire-up of figures F1–F7 pending upstream eval-toolkit issues #14–#16 + #22.</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="fu">### Takeaways (for the intro-only reader)</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>Three takeaways for the reviewer who reads only §1 + §1.5 + §2 + §Results.</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**What was characterised.** A 5-rung ladder (TF-IDF+LR classical floor + ModernBERT-base frozen-probe + ModernBERT-base LoRA + ProtectAI v1 + ProtectAI v2) on 5 OOD slices spanning the five injection types in §1.5: `direct_injection`, `indirect_injection`, `agentic_flow_injection`, `jailbreak_as_question`, `false_positive_probe`. **Single-turn English text classification only**, with bootstrap CIs + paired-bootstrap rung-vs-rung + calibration battery + dual-policy thresholds per ADR-022 / ADR-023 / ADR-025.</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**What the OOD wall reveals — read against the §1.5 train/test table.** The OOD slate is hardest on the injection types *not* in the training pool. BIPIA (the only `indirect_injection` slate) and InjecAgent (the only `agentic_flow_injection` slate) both have zero counterparts in the 4 LODO training sources. The trained transformer rungs land at or below the `pooled_ood` positive-class prevalence baseline of 0.374 under AUPRC (frozen-probe 0.364; LoRA 0.293; classical floor 0.291). **LoRA's `pooled_ood` AUPRC is essentially tied with the classical floor and -0.071 below frozen-probe** — fine-tuning the head onto direct-injection training data DECREASES OOD generalization vs leaving the pretrained backbone embeddings intact. **The pretrained backbone — not the LODO training pool — carries what little OOD generalization budget exists**, and even that doesn't lift above the prevalence baseline in absolute terms. On the injection types that *are* in training (`direct_injection` via jbb_behaviors partial; `jailbreak_as_question` via XSTest), the trained rungs do modestly better but still cluster in a tight band around 0.47–0.55 AUPRC. By AUROC (chance baseline 0.5), only frozen-probe at 0.515 [0.505, 0.525] clears chance with margin; LoRA at 0.383 falls below. *In short: the rung ladder is doing approximately as well as could be expected given what it was shown, and the OOD gap quantifies what training data alone cannot fix.*</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**What's deferred, what to take away.** Multi-turn agentic flows, encoded payloads, paraphrase attacks, and adversarial perturbations are NOT tested (per §Scope above). A deployment context that includes those attack classes cannot rely on these numbers; [`WRITEUP/limitations-and-future-work.md`](./WRITEUP/limitations-and-future-work.md) §9.4 names what would need to land to extend coverage (OOD-aware training data, backbone scaling, OOD-aware threshold selection). **The honest reading**: this is a methodology + capability *characterisation*, not a leaderboard claim. The headline finding — *fine-tuning consumes the OOD generalization budget the pretrained backbone provides* — is methodologically richer than a "great classifier" framing would have allowed.</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="fu">## Lessons (brief)</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>Long form in <span class="co">[</span><span class="ot">`WRITEUP/limitations-and-future-work.md`</span><span class="co">](./WRITEUP/limitations-and-future-work.md)</span> §11. Punch lines:</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The OOD generalization wall is the dominant signal; honest framing surfaces it where a "great classifier" framing would have hidden it.</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The SDD process bought reproducibility + audit trail at the cost of a ~50-decision Phase 0 interview flow. ADR-050 (rung-slate narrowing) is the supersession-on-supersession proof point — when reality forced a methodology drift, the discipline ate it cleanly.</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The library-first invariant retrofit (ADR-047) was a discipline lapse caught at Phase 4 entry and recovered in one carryforward refactor. The cost-overrun on LLM judges (ADR-050 driver 1) was a similar lapse — original estimate didn't account for actual token volume.</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>FUSE-on-RunPod is a non-deterministic bug class; ~50 % of cumulative spend ($15.74) was FUSE-recovery overhead. Filed upstream issues + PRs at brandon-behring/runpod-deploy.</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Per-step commits + 2-checkpoint push cadence survived multi-day context auto-compaction.</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="fu">## 12. Appendix</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a><span class="fu">### A. Glossary</span></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Detection policy** — threshold selection targeting FPR ≤ 1 % on validation; characterises high-recall-low-FP behaviour.</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Verification policy** — threshold selection targeting FNR ≤ 1 % on validation; characterises high-precision-on-clean behaviour.</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**LODO** — leave-one-dataset-out cross-validation; source-disjoint k-fold where each fold holds out an entire dataset source.</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**LoRA** — Low-Rank Adaptation; parameter-efficient fine-tuning method.</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**PR-AUC** — area under the precision-recall curve; threshold-free ranking metric for class-imbalanced tasks.</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**ECE** — expected calibration error; mean absolute gap between predicted-probability bins and observed frequencies.</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**MDE** — minimum detectable effect; the smallest difference your sample size can reliably detect at a given power.</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**IID** — independent and identically distributed; evaluation on data drawn from the same source/distribution as training.</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**OOD** — out-of-distribution; evaluation on data deliberately drawn from a different source or distribution.</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Rung ladder** — a sequence of classifiers of increasing complexity, designed so each step's lift decomposes which capability is responsible.</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="fu">### B. ADR index</span></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`decisions/README.md`</span><span class="co">](./decisions/README.md)</span> — single version-neutral sequence; ADRs supersede prior ones via the standard <span class="in">`superseded-by-ADR-N`</span> mechanism.</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="fu">### C. Assumption ledger</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`assumptions.md`</span><span class="co">](./assumptions.md)</span> — every assumption with severity ≥ medium appears in <span class="co">[</span><span class="ot">`WRITEUP/limitations-and-future-work.md`</span><span class="co">](./WRITEUP/limitations-and-future-work.md)</span> §8.2.</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="fu">### D. Audit trail</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`EVIDENCE.md`</span><span class="co">](./EVIDENCE.md)</span> — what external evidence was verified, what couldn't be, what was left unresolved.</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="fu">### E. Linked Claude transcripts</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>Transcripts referenced by ADR <span class="in">`transcript:`</span> frontmatter fields are bundled and emailed to the reviewer at submission time per <span class="in">`transcripts/README.md`</span>; the <span class="in">`/save-transcript`</span> skill produces them.</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### F. eval-toolkit methodology curriculum</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`docs/methodology/`</span><span class="co">](https://github.com/brandon-behring/eval-toolkit/tree/main/docs/methodology)</span> — 17-chapter curriculum. Cross-linked from each WRITEUP/ spoke.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>