"""LLM-judge pre-label pass for data/dedup_holdout.jsonl (per ADR-042).

Refines ADR-041 Q5 with an LLM-pre-label bootstrap step: for each candidate
pair generated by `scripts/build_dedup_holdout.py`, queries gpt-4o-2024-08-06
to set `llm_judge_label: bool` + `llm_judge_reasoning: str`. The `true_duplicate`
field is initialized to the LLM label so `scripts/calibrate_dedup.py` can run
immediately for a preliminary calibration; Brandon's hand-examination overrides
any pair where the LLM label is wrong via the `human_label` field.

Provenance fields persisted per pair:
- `llm_judge_label: bool` — what the LLM said
- `llm_judge_reasoning: str` — brief rationale (truncated to ~200 chars)
- `llm_judge_model: str` — model + snapshot used
- `human_label: bool | null` — Brandon's override (null = not yet reviewed)
- `true_duplicate: bool` — effective label (human_label if non-null, else llm_judge_label)

Calibration JSON discloses `human_verified_pct` so reviewer sees the labeling
provenance.

Usage:
    OPENAI_API_KEY=sk-... uv run python scripts/llm_prelabel_dedup_holdout.py

Cost (per OpenAI gpt-4o-2024-08-06 pricing as of 2026-05; ADR-018 snapshot):
    ~$0.0025 per pair (single-call); 50 pairs ~= $0.12 total.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

from openai import OpenAI

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Locked judge model — same snapshot as ADR-018 headline LLM-as-rater for consistency.
JUDGE_MODEL: str = "gpt-4o-2024-08-06"

JUDGE_SYSTEM_PROMPT = """You are a strict semantic-similarity judge for prompt-injection \
attack texts. Your task: decide whether two given prompts are near-duplicates for \
deduplication purposes. Two prompts are near-duplicates if they convey the same \
attack intent + technique even with surface-form differences (paraphrase, word reorder, \
synonym swap, minor template variation). Two prompts are NOT near-duplicates if they \
target different attack vectors, use different exploit techniques, or differ in any \
load-bearing semantic content. Respond with a JSON object: \
{"is_duplicate": true|false, "reasoning": "one-sentence justification (max 200 chars)"}."""

JUDGE_USER_TEMPLATE = """Prompt A:
{text_a}

Prompt B:
{text_b}

Are these near-duplicates (same attack intent + technique with only surface-form differences)?"""


class PrelabelError(RuntimeError):
    """Raised when an LLM pre-label call fails irrecoverably."""


def _judge_pair(
    client: OpenAI, text_a: str, text_b: str, *, max_retries: int = 3
) -> dict[str, Any]:
    """Query the LLM judge for a single pair; return parsed JSON or raise."""
    user_msg = JUDGE_USER_TEMPLATE.format(text_a=text_a[:2000], text_b=text_b[:2000])
    for attempt in range(max_retries):
        try:
            resp = client.chat.completions.create(
                model=JUDGE_MODEL,
                messages=[
                    {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
                temperature=0.0,
                response_format={"type": "json_object"},
                max_tokens=300,
            )
            raw = resp.choices[0].message.content or "{}"
            parsed = json.loads(raw)
            if "is_duplicate" not in parsed:
                raise PrelabelError(f"Judge response missing is_duplicate field: {raw!r}")
            return {
                "is_duplicate": bool(parsed["is_duplicate"]),
                "reasoning": str(parsed.get("reasoning", ""))[:250],
                "raw_tokens_in": resp.usage.prompt_tokens if resp.usage else None,
                "raw_tokens_out": resp.usage.completion_tokens if resp.usage else None,
            }
        except Exception as exc:  # noqa: BLE001
            if attempt == max_retries - 1:
                raise PrelabelError(f"Judge failed after {max_retries} attempts: {exc}") from exc
            wait = 2**attempt
            print(f"  retry {attempt + 1}/{max_retries} in {wait}s — {type(exc).__name__}")
            time.sleep(wait)
    raise PrelabelError("Unreachable — retry loop fell through")


def main() -> int:
    """Entry — read holdout, query judge per pair, persist labels back to JSONL."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--holdout",
        type=Path,
        default=_REPO_ROOT / "data" / "dedup_holdout.jsonl",
        help="Holdout JSONL path (default data/dedup_holdout.jsonl)",
    )
    parser.add_argument(
        "--skip-already-labeled",
        action="store_true",
        help="Skip pairs that already have llm_judge_label (resume after partial run)",
    )
    args = parser.parse_args()

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("ERROR: OPENAI_API_KEY environment variable not set.")
        print("Set it via: export OPENAI_API_KEY=sk-... OR via .env.local + your shell loader.")
        return 2

    if not args.holdout.exists():
        print(f"ERROR: Holdout not found at {args.holdout}.")
        print("Run scripts/build_dedup_holdout.py first.")
        return 2

    # Read all lines (first is metadata; rest are pairs).
    lines = args.holdout.read_text(encoding="utf-8").splitlines()
    if not lines:
        print(f"ERROR: Holdout {args.holdout} is empty.")
        return 2
    metadata = json.loads(lines[0])
    pairs = [json.loads(line) for line in lines[1:]]
    print(f"[llm_prelabel] Loaded {len(pairs)} candidate pairs from {args.holdout}")
    print(f"[llm_prelabel] Judge model: {JUDGE_MODEL}")

    client = OpenAI(api_key=api_key)
    total_tokens_in = 0
    total_tokens_out = 0
    n_labeled = 0
    n_skipped = 0
    n_failed = 0

    for i, pair in enumerate(pairs):
        if args.skip_already_labeled and pair.get("llm_judge_label") is not None:
            n_skipped += 1
            continue
        try:
            result = _judge_pair(client, pair["text_a"], pair["text_b"])
        except PrelabelError as exc:
            n_failed += 1
            print(f"  pair {i}: FAILED — {exc}")
            pair["llm_judge_label"] = None
            pair["llm_judge_reasoning"] = f"FAILED: {exc}"
            pair["llm_judge_model"] = JUDGE_MODEL
            continue

        pair["llm_judge_label"] = result["is_duplicate"]
        pair["llm_judge_reasoning"] = result["reasoning"]
        pair["llm_judge_model"] = JUDGE_MODEL
        # Initialize human_label as null + true_duplicate from LLM (override-pending).
        if "human_label" not in pair:
            pair["human_label"] = None
        pair["true_duplicate"] = pair["llm_judge_label"]
        total_tokens_in += result.get("raw_tokens_in") or 0
        total_tokens_out += result.get("raw_tokens_out") or 0
        n_labeled += 1
        label_glyph = "DUP" if result["is_duplicate"] else "non-dup"
        cos = pair.get("cosine", float("nan"))
        print(f"  pair {i:2d}  cos={cos:.3f}  {label_glyph:>7}  {result['reasoning'][:80]}")

    # Persist updated metadata + pairs.
    metadata["llm_prelabel_model"] = JUDGE_MODEL
    metadata["llm_prelabel_n_labeled"] = n_labeled
    metadata["llm_prelabel_n_skipped"] = n_skipped
    metadata["llm_prelabel_n_failed"] = n_failed
    metadata["llm_prelabel_tokens_in_total"] = total_tokens_in
    metadata["llm_prelabel_tokens_out_total"] = total_tokens_out

    with args.holdout.open("w", encoding="utf-8") as fh:
        fh.write(json.dumps(metadata) + "\n")
        for pair in pairs:
            fh.write(json.dumps(pair, ensure_ascii=False) + "\n")

    cost_estimate = (total_tokens_in * 2.5 / 1_000_000) + (total_tokens_out * 10.0 / 1_000_000)
    print(f"[llm_prelabel] Labeled {n_labeled} / Skipped {n_skipped} / Failed {n_failed}")
    print(
        f"[llm_prelabel] Tokens: in={total_tokens_in:,}  out={total_tokens_out:,}  "
        f"cost~=${cost_estimate:.4f} (gpt-4o-2024-08-06)"
    )
    print(f"[llm_prelabel] Updated {args.holdout}")
    print(
        "[llm_prelabel] Next step: hand-examine each pair, set `human_label` "
        "where LLM judgment is wrong."
    )
    print("[llm_prelabel] Then run: uv run python scripts/calibrate_dedup.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
