<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-21">

<title>Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0 – Prompt-injection classifier evaluation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-83d6731c42c83706f5616676628995c1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Prompt-injection classifier evaluation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../RESULTS.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="../WRITEUP_PAPER.html">
 <span class="dropdown-text">Academic paper (IMRAD)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP_NARRATIVE.html">
 <span class="dropdown-text">Narrative arc (story)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP.html">
 <span class="dropdown-text">Router (pick a guide)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../READING_GUIDE.html">
 <span class="dropdown-text">Reading guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/data-decisions.html">
 <span class="dropdown-text">Data decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/model-rungs.html">
 <span class="dropdown-text">Model details</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/eval-design.html">
 <span class="dropdown-text">Evaluation design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/threshold-policy.html">
 <span class="dropdown-text">Threshold policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/reference-scorer-audit.html">
 <span class="dropdown-text">Reference-scorer audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/methodology-guarantees.html">
 <span class="dropdown-text">Methodology guarantees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/limitations-and-future-work.html">
 <span class="dropdown-text">Limitations and future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/reproducibility.html">
 <span class="dropdown-text">Reproducibility — three reproduction tiers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../decisions/README.html"> 
<span class="menu-text">Decisions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reference">    
        <li>
    <a class="dropdown-item" href="../docs/for-hiring-managers.html">
 <span class="dropdown-text">Project at a glance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../docs/site-reader-map.html">
 <span class="dropdown-text">Public site reader map</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../EVIDENCE.html">
 <span class="dropdown-text">Evidence ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../SPEC_SHEET.html">
 <span class="dropdown-text">Spec lock sheet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../SUBMISSION_AUDIT.html">
 <span class="dropdown-text">Submission audit ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../NEXT_STEPS.html">
 <span class="dropdown-text">Carryforward + future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assumptions.html">
 <span class="dropdown-text">Assumptions registry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/01_canonical_results.html">
 <span class="dropdown-text">Notebook: canonical results</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/02_frozen_vs_lora.html">
 <span class="dropdown-text">Notebook: frozen vs LoRA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/03_calibration.html">
 <span class="dropdown-text">Notebook: calibration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/04_ood_slate.html">
 <span class="dropdown-text">Notebook: OOD slate</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/brandon-behring/prompt-injection-detection-prototype" target="_blank"> 
<span class="menu-text">Repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../decisions/README.html">Decisions (ADRs)</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-001-submission-deadline-and-scope-ambition.html">Decisions</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-079-two-guide-reader-architecture.html">Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Entry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Landing page (results + meaning)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">README + executive summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../RESULTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Results: tables, figures, and source artifacts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology guides (pick a style)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP_PAPER.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Academic paper (IMRAD)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP_NARRATIVE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrative arc (story)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Router (1-page chooser)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../READING_GUIDE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading guide</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Detailed spokes (8 topics)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/data-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/model-rungs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/eval-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/threshold-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threshold policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/reference-scorer-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/limitations-and-future-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Limitations and future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility — three reproduction tiers</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/01_canonical_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 — Canonical results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/02_frozen_vs_lora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/03_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 — Calibration battery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/04_ood_slate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 — OOD slate gap visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence + audit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../EVIDENCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evidence ledger</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../docs/site-reader-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Public site reader map</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../SPEC_SHEET.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spec lock sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../SUBMISSION_AUDIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission audit ledger</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../NEXT_STEPS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carryforward + future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions registry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions (ADRs)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architecture Decision Records (ADRs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/upstream_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Upstream issues filed during this iteration</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-001-submission-deadline-and-scope-ambition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission deadline 2026-05-18 morning with infra-leveraged Long-scope attempt and fallback ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-002-deliverable-format-pdf-and-repo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — focused PDF plus public GitHub repo as evidence locker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-003-repo-visibility-public.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repository visibility — public from start (kit default ratified)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-004-reviewer-profile-and-hub-and-spoke-writeup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer profile A1+A2 with hub-and-spoke writeup structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-005-methodology-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-level methodology principles — methodology over metrics, honest evaluation preferred, structured limitations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-006-headline-metrics-and-statistical-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Headline metrics, operating-point pinpoints, and statistical apparatus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-007-rung-architecture-and-reference-scorers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology rung architecture — trained backbones, LLM-judge reference rungs, Cohen’s kappa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-008-data-scope-public-only-hybrid-splits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data scope — public-only sources, hybrid splits, NotInject inclusion (brief-level lock)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-009-process-mandates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Process mandates — two-tier reproducibility, marker-based testing, compute disclosure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-010-scope-limits-with-extension-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scope limits with per-bound extension conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-011-methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees — eight banned approaches surfaced as project commitments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-012-soft-signals-and-artifact-engagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Soft-signals naming discipline and external artifact engagement set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-013-kit-ratify-bulk-strictness-intake-notebook-persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kit-ratify bulk — Phase 0 strictness, brief-intake protocol, notebook role and RunPod persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-014-threat-model-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threat-model bundle — attack-class scope, language, length cap, truncation policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-015-rung-architecture-refinement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung architecture refinement — ModernBERT-base only trained slate, supersedes ADR-007</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-016-data-design-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data design bundle — source slate, splits, HF pinning, dedup, ordering, ceilings, ref-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-017-trained-rung-slate-expansion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trained-rung-slate expansion — TF-IDF plus LR classical floor and frozen-probe dual role</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-018-reference-scorer-slate-and-contamination-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference scorer slate and contamination stratification — OpenAI plus Anthropic LLM-judges plus ProtectAI v1 and v2 plus per-axis matched-budget</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-019-lora-and-transformer-training-recipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA and transformer-rung training recipe — hyperparameters, epochs, precision, class weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-020-compute-infrastructure-and-cost-discipline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute infrastructure and cost discipline — runpod-deploy 0.7.7 primitives, GPU failover, adaptive batch sizing, dual-layer cost tracking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-021-eval-slate-aggregation-and-recall-fpr-pinpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eval slate aggregation — pooled headline plus per-slice spoke and recall@FPR pinpoint feasibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-022-statistical-inference-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference apparatus — bootstrap N + stability check, multi-comparison stance, multi-seed protocol, paired-test method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-023-calibration-battery-and-interventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery composition — raw plus temperature plus isotonic interventions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-024-cross-fold-ci-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-fold CI methodology — cv_clt_ci (Bayle 2020) headline plus block-bootstrap-on-folds spoke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-025-dual-policy-threshold-characterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dual-policy threshold characterization at symmetric 1% cost weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-026-module-layout-concern-grouped-subpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module layout — concern-grouped sub-packages under src/</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-027-smoke-vs-canonical-execution-context-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Smoke vs canonical separation — three Makefile targets stratified by execution context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-028-coverage-floor-70pct-with-upstream-issue-filing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test coverage floor — 70% flat with co-locked upstream-issue-filing discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-029-test-marker-strategy-four-marker-ratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test marker strategy — ratify 4-marker stratification (unit / smoke / integration / network)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-030-deliverable-format-quarto-html-site.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — repo-only with Quarto-rendered HTML site via GitHub Actions (supersedes ADR-002)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-031-reviewer-reading-paths-quarto-site-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer reading paths — index.qmd entry-point with Quarto sidebar nav (supersedes ADR-004)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-032-hf-hub-publication-headline-rungs-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HF Hub checkpoint publication — publish primary headline rungs only with model card discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-033-github-release-strategy-rehearsal-plus-submission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitHub release strategy — rehearsal tag plus SemVer submission tag plus post-submission patches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-034-reproducibility-tier-full-ladder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility tier — full ladder T0 (eval-from-hub) plus T1 (smoke) plus T3 (headline-cloud)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-035-secrets-management-three-store-split.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secrets management — three-store split aligned with execution context (.env + RunPod pod-secrets + GH Actions repo Secrets)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-036-library-version-pins-tag-pin-plus-freeze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library version pins — tag pin to latest stable plus freeze for submission window (eval-toolkit v0.31.0 + runpod-deploy v0.7.7 + research_toolkit v1.9.1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-037-python-version-pin-3-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python version pin — ratify requires-python &gt;=3.13 (matches existing .python-version + bc8ce4e commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-038-phase-tailoring-light-roadmap-edits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase tailoring — light ROADMAP edits to Phase 4 close + Phase 5 description (preserves 5-phase structure)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-039-acceptance-criteria-six-gate-integration-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-specific acceptance criteria — 6-gate integration checklist for v1.0.0 submission tag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-040-phase-0-audit-findings-and-assumption-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 0 final audit findings + 7-assumption backfill (A-010 through A-016)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-041-phase-1-data-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 (Data) implementation bundle — manifest schema, SHA pinning, validator placement, loader arch, holdout sourcing, contamination corpus, output materialization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-042-llm-prelabel-dedup-holdout-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-judge pre-label as Q5 holdout-labeling bootstrap with human override</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-043-post-split-cross-source-leakage-cleanup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-split cross-source leakage cleanup — drop train+val rows that exact-match or cosine-near-match test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-044-phase-2-training-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 training implementation bundle — seed slate reconciliation + manifest move + classical-floor location + YAML config schema + trainer split + per-rung orchestration + fixture preflight</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-045-phase-3-evaluation-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 evaluation implementation bundle — scoring-first contract + 6-commit cadence + tiered reference scorers + classical-scaffold + full-pairwise persistence with headline-only WRITEUP + pydantic schema validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-046-phase-4-analysis-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 analysis implementation bundle — 6-commit cadence + scaffold-with-classical + always-emit-both-CIs auto-flag + MDE-on-every-emitted-CI + LLM-rater audit included (user-overridden from defer) + library-first hybrid figures + Phase 5 prep deferred</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-047-phase-1-library-first-carryforward-refactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 library-first carryforward refactor — audit findings + remediation plan (splits + dedup + leakage_report + contamination_scan migration to eval-toolkit primitives; orphaned code removed in-commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-048-llm-rater-reference-scorer-audit-protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-rater reference-scorer audit protocol — disagreement-with-LoRA baseline + stratified (5 OOD slices × 3 contamination_states) sampling + fixed 2-axis rubric + inter-rater gpt-4o-plus-claude-sonnet + dry-run-then-single-approval cost UX</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-049-gpu-order-priority-refresh-a100-80g.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPU failover ladder priority refresh — A100-SXM4-80GB to position 1 + US-WA-1/US-CA-2 datacenter additions + EU-RO-1 drop (frozen-probe + LoRA canonical; full-FT deferred to post-rehearsal)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-050-rung-slate-narrowing-llm-judges-and-full-ft-ood-dropped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung slate narrowing — LLM judges dropped (cost) + full-FT OOD dropped (FUSE EIO crash); narrow supersession of ADR-018 reference slate + ADR-021 OOD comparison scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-051-v1.0.x-carryforward-of-t0-and-invariant-scaffolds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">v1.0.x carryforward of ADR-034 T0 score-match wiring + ADR-039 gate-3 invariant-scaffold unskip; narrow supersession with explicit v1.1.x landing condition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-052-full-ft-ood-drop-methodological-reframing-of-adr-050-r2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full-FT OOD inference drop — methodological reframing; narrow supersession of ADR-050 Revision 2 (FUSE-crash-only framing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-053-reading-guide-governance-and-newcomer-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading-guide governance + newcomer onboarding paths — two entry artifacts + 3 reading paths + Headline-finding-block + interpretation pedagogy + pointer convention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-054-results-page-as-third-entry-artifact-extending-adr-053.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RESULTS.md as third entry artifact — narrow supersession of ADR-053 dimension 1 (two-entry-artifacts); dimensions 2-5 unchanged</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-055-eval-toolkit-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">eval-toolkit installs from PyPI (not git+https) at v0.40.0+ — narrow supersession of ADR-036 “git URL is the only viable spec format”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-056-binary-calibrator-refactor-and-platt-beta-narrow-supersession-of-adr-023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery refactor to eval-toolkit <code>_binary</code> API + Platt + Beta calibrators landed — narrow supersession of ADR-023 “temperature + isotonic only” scope deferral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-057-manifest-schema-v3-backfill-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Per-prediction provenance manifests via scripts/backfill_provenance.py — schema, location, naming, idempotency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-058-eval-from-hub-non-dry-run-body-narrow-supersession-of-adr-051-block-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">scripts/eval_from_hub.py non-dry-run body wired — narrow supersession of ADR-051 Block A (T0 score-match carryforward); Block B (38 invariant scaffolds) remains carryforward</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-059-runpod-deploy-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">runpod-deploy installs from PyPI (not git+https) at v0.8.4+ — narrow supersession of ADR-036 “git URL is the only viable spec format” sub-claim for runpod-deploy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation methodology — chunk-and-average vs head-truncation × 5-slice OOD; infrastructure-only at v1.1.0; execution deferred to v1.1.1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-061-quarto-site-navigation-restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto site navigation restructure — landing-page rebuild + navbar consolidation + sidebar hub-spoke nesting (narrow supersession of ADR-053 navigation contract)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-062-quarto-writeup-clarity-and-canonical-figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto writeup clarity rewrite and canonical reviewer figure slate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation execution (v1.1.2 carryforward; narrow renaming-only supersession of ADR-060 “v1.1.1” body references) — null result, backbone-dominant interpretation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-064-writeup-hiring-manager-clarity-and-consistency-pass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup hiring-manager clarity polish + documentation-wide consistency conventions — additive layer on top of ADR-062</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup accuracy-audit methodology + Quarto callout-note convention + narrative invariants — additive layer on top of ADR-064</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-066-library-first-carryforward-refactor-v1-2-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library-first carryforward refactor v1.2.2 — consume 7 closed eval-toolkit primitives across 6 sites</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for factual-typo fixes in cross-reference slug filenames</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-069-immutability-narrow-relaxation-for-publisher-url-to-doi-canonicalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for academic publisher-URL → DOI canonicalization in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-070-quarto-render-only-markdown-corrections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for render-only Markdown corrections in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-071-adr-cross-reference-slug-sweep-closure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Execute the slug-sweep authorized by ADR-067 + ADR-068 + ADR-069 that was never actually completed in any prior commit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-072-adr-051-052-frontmatter-and-structural-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill missing frontmatter fields + Alternatives sections + Status headings for ADR-051 + ADR-052 per ADR-067-style narrow-relaxation discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-073-adr-immutability-rule-consolidated-re-statement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collapse the four-ADR narrow-relaxation chain (ADR-067/068/069/070) into a single consolidated immutability rule with four named exception classes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-074-adr-064-self-criticism-quote-redaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Replace verbatim self-criticism quote in ADR-064 frontmatter claim + body context with a neutral paraphrase preserving the decision</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-075-full-ft-ood-drop-rationale-unified-narrative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unify the ADR-050 Revision 2 (FUSE-crash-forced-drop) and ADR-052 (methodology-load-bearing-with-crash-as-trigger) framings into a single account</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-076-superseded-by-and-closing-commit-frontmatter-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill superseded_by on ADR-046 + ADR-054 + ADR-061 (→ ADR-062) + closing_commit on ADR-071-075 per ADR-072 frontmatter-backfill discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-077-supersession-backlink-and-frontmatter-octal-quoting-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Backfill supersession back-links + quote octal-risk YAML integer fields in ADR-007 + ADR-015 + ADR-018 + ADR-021 + ADR-052 frontmatter per ADR-076 frontmatter-backfill discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-078-executive-summary-absorbed-into-readme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Absorb EXECUTIVE_SUMMARY content into README; retire EXECUTIVE_SUMMARY.md as standalone file</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-079-two-guide-reader-architecture.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-080-reviewer-url-pin-numeric-correction-adr-078-079.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correct reviewer URL pin numeric defect in ADR-078 + ADR-079 (tree/v1.2.8 → tree/v1.0.0); axis-only supersession on the reviewer-URL-pin axis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-081-frontmatter-status-field-split-narrow-relaxation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authorize frontmatter <code>status:</code> field split (verbose-context → pure-Nygard <code>status:</code> + new <code>lifecycle-note:</code>) as an extension of the ADR-072 / ADR-076 / ADR-077 frontmatter-backfill narrow-relaxation discipline; apply to ADR-060 as the seed case</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#adr-079-two-guide-reader-architecture" id="toc-adr-079-two-guide-reader-architecture" class="nav-link active" data-scroll-target="#adr-079-two-guide-reader-architecture">ADR-079: Two-guide reader architecture</a>
  <ul class="collapse">
  <li><a href="#status" id="toc-status" class="nav-link" data-scroll-target="#status">Status</a></li>
  <li><a href="#context" id="toc-context" class="nav-link" data-scroll-target="#context">Context</a></li>
  <li><a href="#decision" id="toc-decision" class="nav-link" data-scroll-target="#decision">Decision</a>
  <ul class="collapse">
  <li><a href="#architecture" id="toc-architecture" class="nav-link" data-scroll-target="#architecture">Architecture</a></li>
  <li><a href="#guide-content-outlines" id="toc-guide-content-outlines" class="nav-link" data-scroll-target="#guide-content-outlines">Guide content outlines</a></li>
  <li><a href="#headline-prominence-per-style" id="toc-headline-prominence-per-style" class="nav-link" data-scroll-target="#headline-prominence-per-style">Headline prominence per style</a></li>
  <li><a href="#voice-register-per-q4-lock" id="toc-voice-register-per-q4-lock" class="nav-link" data-scroll-target="#voice-register-per-q4-lock">Voice register per Q4 lock</a></li>
  <li><a href="#both-guides-explain-jargon" id="toc-both-guides-explain-jargon" class="nav-link" data-scroll-target="#both-guides-explain-jargon">Both guides explain jargon</a></li>
  <li><a href="#writeup.md-retired-as-stub-redirect" id="toc-writeup.md-retired-as-stub-redirect" class="nav-link" data-scroll-target="#writeup.md-retired-as-stub-redirect">WRITEUP.md retired as stub-redirect</a></li>
  <li><a href="#supersession-scope" id="toc-supersession-scope" class="nav-link" data-scroll-target="#supersession-scope">Supersession scope</a></li>
  <li><a href="#submission_audit.md-cascade" id="toc-submission_audit.md-cascade" class="nav-link" data-scroll-target="#submission_audit.md-cascade">SUBMISSION_AUDIT.md cascade</a></li>
  </ul></li>
  <li><a href="#consequences" id="toc-consequences" class="nav-link" data-scroll-target="#consequences">Consequences</a></li>
  <li><a href="#alternatives-considered" id="toc-alternatives-considered" class="nav-link" data-scroll-target="#alternatives-considered">Alternatives Considered</a></li>
  <li><a href="#linked-adrs" id="toc-linked-adrs" class="nav-link" data-scroll-target="#linked-adrs">Linked ADRs</a></li>
  <li><a href="#transcript" id="toc-transcript" class="nav-link" data-scroll-target="#transcript">Transcript</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../decisions/README.html">Decisions (ADRs)</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-001-submission-deadline-and-scope-ambition.html">Decisions</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-079-two-guide-reader-architecture.html">Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Two-guide reader architecture (academic IMRAD + narrative arc) replacing the single-hybrid WRITEUP for v1.3.0</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout-warning">
<p><strong>Superseded on one or more axes</strong> by <strong>ADR-080</strong>. The body below retains its original prose per the <a href="ADR-073-adr-immutability-rule-consolidated-re-statement.html">ADR-073 immutability rule</a>; the corrected position lives in the superseding ADR. See the <a href="README.html">Decisions index</a> to navigate.</p>
</div>
<section id="adr-079-two-guide-reader-architecture" class="level1">
<h1>ADR-079: Two-guide reader architecture</h1>
<section id="status" class="level2">
<h2 class="anchored" data-anchor-id="status">Status</h2>
<p>Accepted.</p>
</section>
<section id="context" class="level2">
<h2 class="anchored" data-anchor-id="context">Context</h2>
<p>User feedback in the 2026-05-21 v1.3.0 planning session diagnosed the existing single-guide architecture (WRITEUP.md hub + 8 WRITEUP/ spokes + EXECUTIVE_SUMMARY.md + RESULTS.md + index.qmd) as:</p>
<blockquote class="blockquote">
<p>“neither a narrative structure to quarto nor is there an academic structure like in a journal paper — it seems random parts of the results all over the place with no story. I had a headline and still wanted to make sure the other results were shown — but it feels so jumbled”</p>
</blockquote>
<p>Root-cause analysis from the structural heading map confirmed two distinct failures:</p>
<ol type="1">
<li><p><strong>Cross-page redundancy.</strong> The same content (headline finding, mechanism, direct-detection check, metrics primer) was rendered in 3-4 different framings across <code>index.qmd</code> + <code>EXECUTIVE_SUMMARY</code> + <code>WRITEUP</code> + <code>RESULTS</code>. Drift was incidental — each surface evolved independently across the v1.0.x patch trail rather than being designed as one coherent reader experience.</p></li>
<li><p><strong>Within-page register inconsistency.</strong> WRITEUP.md mixed summary-style (executive-y) and detail-style (academic-y) without committing to either register. Methodology (§9 “in one paragraph”) appeared AFTER Findings (§7) — backwards from academic IMRAD convention. The 7 findings were enumerated (academic-style) but framed narratively (story-style sentences with bolded takeaways), making each finding read like a story chapter even though they were listed like academic results.</p></li>
</ol>
<p>The diagnosis: the existing WRITEUP was an enthusiastic-explainer wearing an ill-fitting academic suit. Not coherent as a paper; not coherent as a story.</p>
</section>
<section id="decision" class="level2">
<h2 class="anchored" data-anchor-id="decision">Decision</h2>
<p>Adopt a <strong>two-guide reader architecture</strong> for v1.3.0 in which both guides cover the same content but in different reading-style registers. Companion to ADR-078 (EXECUTIVE_SUMMARY absorbed into README).</p>
<section id="architecture" class="level3">
<h3 class="anchored" data-anchor-id="architecture">Architecture</h3>
<pre><code>README.md                       # top-fold executive summary (per ADR-078) + 2-guide chooser
index.qmd                       # 60-sec landing + 2-guide chooser
WRITEUP_PAPER.md (NEW)          # ACADEMIC: IMRAD discipline (~530 lines)
WRITEUP_NARRATIVE.md (NEW)      # NARRATIVE: 5-act story (~570 lines)
WRITEUP.md                      # STUB-REDIRECT: 1-page router preserving backward refs
RESULTS.md                      # APPENDIX: tables-only (cross-ref'd by both guides; trim deferred to v1.3.1 if needed)
READING_GUIDE.md                # NAVIGATION: 2-path router
WRITEUP/data-decisions.md       # UNCHANGED: 8 domain spokes serve as deep-dive references for both guides
WRITEUP/eval-design.md          # ...
WRITEUP/model-rungs.md
WRITEUP/methodology-guarantees.md
WRITEUP/threshold-policy.md
WRITEUP/reference-scorer-audit.md
WRITEUP/reproducibility.md
WRITEUP/limitations-and-future-work.md</code></pre>
</section>
<section id="guide-content-outlines" class="level3">
<h3 class="anchored" data-anchor-id="guide-content-outlines">Guide content outlines</h3>
<p><strong>WRITEUP_PAPER.md</strong> (academic IMRAD; ~530 lines): - §0 Abstract (5-sentence structured: motivation / approach / finding / mechanism / implication) - §1 Introduction (research question + contribution) - §2 Background (prompt-injection landscape; existing detectors; data sources) - §3 Methods (4 subsections: LODO splits / model rungs / evaluation slate / statistical apparatus) - §4 Results (7 numbered equal-weight findings; headline = Finding 3 of 7; no dedicated headline section) - §5 Discussion (mechanism: lexical overfitting + label-relevance shift + implications) - §6 Limitations (6 subsections incl.&nbsp;incomplete-experiment status) - §7 Conclusion - §8 References (ADR refs + external bibliography + project artifacts) - Glossary (in-paper definitions; cross-ref to docs/GLOSSARY.md)</p>
<p><strong>WRITEUP_NARRATIVE.md</strong> (narrative arc; ~570 lines): - Act 0 — Hook (the surprise: anti-correlation; dramatic opening) - Act 1 — Setup (what we wanted to know + threat-model context + out-of-scope) - Act 2 — Investigation (LODO discipline + cross-family slate + 5-rung detector ladder + statistical apparatus) - Act 3 — Revelation (headline finding rendered as dramatic third- act reveal: AUPRC at floor + AUROC below 0.5 anti-correlation + mechanism interpretation) - Act 4 — The other findings (Findings 4-7 as supporting cast in equal-weight enumeration; preserves the “don’t bury the other results” requirement) - Act 5 — Implications (3 cautious claims + 5 future-work priorities + broader-field implication) - Epilogue — Limits + reproduction instructions + dig-deeper pointers + closing note</p>
</section>
<section id="headline-prominence-per-style" class="level3">
<h3 class="anchored" data-anchor-id="headline-prominence-per-style">Headline prominence per style</h3>
<p>Each guide treats the headline finding natively per its style (per the v1.3.0 plan Q4 lock):</p>
<ul>
<li><strong>PAPER</strong>: Finding 3 is one of 7 equal-weight numbered results in §4 Results. Academic neutrality; no dedicated headline section.</li>
<li><strong>NARRATIVE</strong>: Headline is the dramatic Act-3 revelation. Story- arc convention demands a climactic third-act reveal; this is it.</li>
</ul>
<p>The structural variation IS the reader-experience difference. Same factual content; different rhetoric. This resolves the “headline yet other results shown” tension explicitly — both guides cover all 7 findings; the headline gets prominence native to the guide’s style.</p>
</section>
<section id="voice-register-per-q4-lock" class="level3">
<h3 class="anchored" data-anchor-id="voice-register-per-q4-lock">Voice register per Q4 lock</h3>
<ul>
<li><strong>PAPER</strong>: formal academic. Passive voice (“The methodology applies…”); technical terminology; numbered subsections; explicit confidence intervals; cross-references to ADRs and external papers; on-first-use jargon definitions + cross-ref to GLOSSARY.</li>
<li><strong>NARRATIVE</strong>: plain-English first-person plural (‘we’). Active voice (“We wanted to know…”); minimal jargon; defined on first use + cross-ref to GLOSSARY. Extends the precedent set by docs/for-hiring-managers.md (per ADR-064: the only first-person surface) to first-person-plural for narrative.</li>
</ul>
</section>
<section id="both-guides-explain-jargon" class="level3">
<h3 class="anchored" data-anchor-id="both-guides-explain-jargon">Both guides explain jargon</h3>
<p>Both guides define jargon on first use and cross-reference the canonical glossary at docs/GLOSSARY.md. This means PAPER doesn’t assume the reader knows all the ML terms (academic reviewer might be from a different ML subfield), and NARRATIVE’s accessibility doesn’t drop precision (story reader still gets accurate definitions). The Q4 lock comment: “in both we should still explain jargon and include the glossary.”</p>
</section>
<section id="writeup.md-retired-as-stub-redirect" class="level3">
<h3 class="anchored" data-anchor-id="writeup.md-retired-as-stub-redirect">WRITEUP.md retired as stub-redirect</h3>
<p>The current WRITEUP.md (the jumbled hybrid) becomes a 1-page stub: “Pick how you’d like to read this: <code>[academic](../WRITEUP_PAPER.md)</code> or <code>[narrative](../WRITEUP_NARRATIVE.md)</code>”. This preserves backward references from the 8 WRITEUP/ spokes + ADRs without breaking links. The historical WRITEUP.md content is accessible at the reviewer URL pin (<code>tree/v1.2.8</code>) per ADR-033.</p>
</section>
<section id="supersession-scope" class="level3">
<h3 class="anchored" data-anchor-id="supersession-scope">Supersession scope</h3>
<p>This ADR supersedes ADR-053, ADR-054, ADR-061 on <strong>specific reading- guide architecture axes only</strong>, not on their full decision content:</p>
<ul>
<li><strong>ADR-053</strong>: superseded on dimension 1 (“Quarto reading-guide architecture” — the two-entry-artifact framing). Dimensions 3 (3-reading-paths), 4 (Headline-finding-block requirement), and 5 (interpretation-pedagogy + pointer-convention) unchanged. ADR-053 dimension 2 was separately superseded by ADR-078 (EXECUTIVE_SUMMARY absorption).</li>
<li><strong>ADR-054</strong>: superseded on the “RESULTS.md as third entry artifact” framing. RESULTS becomes an appendix / tables-only reference in v1.3.0, not an entry artifact. ADR-054’s body content (5 sections defining RESULTS structure) survives in form even though the artifact role changes.</li>
<li><strong>ADR-061</strong>: superseded on the navbar/sidebar restructure axis. v1.3.0 navbar gains “Academic paper” + “Narrative arc” entries; sidebar “Entry” section drops EXECUTIVE_SUMMARY; new “Methodology guides (pick a style)” section introduces the two guides.</li>
</ul>
<p>ADR-062 (writeup clarity + canonical figures) is preserved unchanged; the canonical figures + reader-facing prose-style work informs both new guides.</p>
<p>ADR-004 (reviewer-profile-and-hub-and-spoke-writeup) is preserved unchanged; the 8 WRITEUP/ spokes still serve as deep-dive references for both guides.</p>
</section>
<section id="submission_audit.md-cascade" class="level3">
<h3 class="anchored" data-anchor-id="submission_audit.md-cascade">SUBMISSION_AUDIT.md cascade</h3>
<p>This ADR’s creation moves the ADR count from 78 → 79. The v1.2.14 <code>audit_adr_count_claims.py</code> invariant catches reader-facing ADR-count claims that would go stale: - <code>README.md</code>: 78 → 79 - <code>docs/for-hiring-managers.md</code>: 78 → 79 - <code>WRITEUP/methodology-guarantees.md</code>: 78 → 79 - <code>CLAUDE.md</code>: 78 → 79</p>
<p><code>SUBMISSION_AUDIT.md</code> regenerates via <code>scripts/regenerate_audit.py</code>; CLAIM count goes 78 → 79. Fourth time the audit_adr_count_claims invariant has correctly fired across the v1.2.13/14/15/16 → v1.3.0 trail — validates v1.2.14 design intent.</p>
</section>
</section>
<section id="consequences" class="level2">
<h2 class="anchored" data-anchor-id="consequences">Consequences</h2>
<ul>
<li>Reader path simplifies: index (60-sec) → README (full executive summary + chooser) → either guide (PAPER or NARRATIVE) → 8 spokes (depth). Each layer has a unique role; no cross-layer redundancy.</li>
<li>Maintenance burden reduces in the long run (single-source-of-truth per surface); doubles temporarily during v1.3.x while both guides exist (any future result update touches PAPER + NARRATIVE + RESULTS; mitigation: results are frozen at v1.0.0, so write-once is acceptable).</li>
<li>Reader-experience differentiation: academic reviewer gets a paper; story reader gets a story; both get the same content.</li>
<li>The “headline but also other results” tension is structurally resolved: PAPER treats all 7 findings equal-weight (Finding 3 is just one of them); NARRATIVE gives the headline dramatic Act-3 prominence + Acts 4’s equal-weight enumeration of the other 6.</li>
<li>Historical reviewer link to WRITEUP.md remains stable via the <code>tree/v1.2.8</code> pin (per ADR-033). Current-state WRITEUP.md is a redirect stub; readers following links land on the chooser and pick a guide.</li>
<li>audit_adr_count_claims invariant catches the cascade (78→79); 4th time it has fired correctly in the trail.</li>
<li>audit_superseded_by_backlinks invariant catches the ADR-079 → ADR-053/054/061 supersession edges; comment-heuristic classifies them as axis-only (correct).</li>
</ul>
</section>
<section id="alternatives-considered" class="level2">
<h2 class="anchored" data-anchor-id="alternatives-considered">Alternatives Considered</h2>
<ol type="1">
<li><strong>Three guides</strong> (academic + narrative + hybrid). Initial Q1 lock was 3 guides; user reconsidered (“lets think for a second”) + reduced to 2 + README-absorbs-EXEC-SUMMARY. Rationale: 3 guides produced 3× content duplication for a frozen artifact; well-executed 2 guides serve the same reader-types without the third “hybrid” guide (since hybrid is what the current jumbled WRITEUP.md was).</li>
<li><strong>One guide done well</strong> (restructure WRITEUP to clean hybrid + add README Abstract). Rejected per Q1 lock — user prefers reader-type choice between paradigms. Hybrid alone doesn’t address the “neither narrative nor academic” complaint structurally.</li>
<li><strong>Minimal triage</strong> (kill redundancy, no restructure). Rejected per Q1 lock — symptomatic fix only; doesn’t address the user-stated need for a story or academic structure.</li>
<li><strong>Pure academic IMRAD only</strong> (one guide). Rejected — loses the story-reader path. The “for-hiring-managers” persona page exists but is only 5-min depth; the NARRATIVE guide serves the longer story-style read.</li>
<li><strong>Pure narrative arc only</strong> (one guide). Rejected — loses the academic-reviewer path. Defensibility at peer review weaker without IMRAD discipline.</li>
<li><strong>Add MIGRATION.md mapping old WRITEUP sections to new guides</strong>. Considered for v1.3.1; not in v1.3.0 scope. The WRITEUP.md stub-redirect + the historical reviewer URL pin together cover the migration use case.</li>
</ol>
</section>
<section id="linked-adrs" class="level2">
<h2 class="anchored" data-anchor-id="linked-adrs">Linked ADRs</h2>
<ul>
<li><strong>ADR-004</strong> (Reviewer profile + hub-and-spoke writeup): preserved unchanged. The 8 WRITEUP/ spokes still serve as deep-dive references; the “hub” is now distributed between WRITEUP_PAPER and WRITEUP_NARRATIVE (cited from both as “WRITEUP/ spokes”).</li>
<li><strong>ADR-033</strong> (Release strategy + reviewer URL pin): preserves the v1.0.0 EXECUTIVE_SUMMARY.md and v1.0.0 WRITEUP.md hybrid at the historical reviewer pin. v1.3.0 ships on live site + main only.</li>
<li><strong>ADR-053</strong> (Reading-guide governance): superseded on dimension 1 axis only (entry artifacts framing); other dimensions unchanged.</li>
<li><strong>ADR-054</strong> (RESULTS as third entry artifact): superseded on the entry-artifacts framing axis. RESULTS becomes appendix/reference, not an entry artifact.</li>
<li><strong>ADR-061</strong> (Navbar/sidebar restructure): superseded on the navbar/sidebar structure axis. v1.3.0 introduces “Methodology guides (pick a style)” sidebar section + navbar entries for the two guides.</li>
<li><strong>ADR-062</strong> (Writeup clarity + canonical figures): preserved. Canonical figures inform both new guides.</li>
<li><strong>ADR-064</strong> (Writeup hiring-manager clarity): preserved. First- person-precedent at for-hiring-managers.md extended to NARRATIVE’s first-person-plural.</li>
<li><strong>ADR-078</strong> (EXECUTIVE_SUMMARY absorbed into README): companion ADR for v1.3.0. Together with ADR-079 discharges the v1.3.0 restructure governance.</li>
</ul>
</section>
<section id="transcript" class="level2">
<h2 class="anchored" data-anchor-id="transcript">Transcript</h2>
<p>Transcript file (gitignored per AGENTS.md): the 2026-05-21 v1.3.0 planning session — diagnosis of the jumbled-structure complaint, 4-question /exploring-options walk (paradigm + headline prominence + version bump + v1.2.16 cleanup), follow-up 4-question slate (file naming + sub-PR strategy + authorship + voice register), user- locked 2-guide architecture after “lets think for a second” deliberation. <code>/save-transcript 2026-05-21__v1-3-0-two-guide- restructure</code> will land this file post-v1.3.0 close.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>