<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-19">

<title>Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs) – Prompt-injection classifier evaluation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6417478169390d5200ae675d66b5a4f4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Prompt-injection classifier evaluation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../RESULTS.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methodology" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methodology</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methodology">    
        <li>
    <a class="dropdown-item" href="../WRITEUP.html">
 <span class="dropdown-text">Cover narrative (hub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../READING_GUIDE.html">
 <span class="dropdown-text">Reading guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/data-decisions.html">
 <span class="dropdown-text">Data decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/model-rungs.html">
 <span class="dropdown-text">Model details</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/eval-design.html">
 <span class="dropdown-text">Evaluation design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/threshold-policy.html">
 <span class="dropdown-text">Threshold policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/reference-scorer-audit.html">
 <span class="dropdown-text">Reference-scorer audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/methodology-guarantees.html">
 <span class="dropdown-text">Methodology guarantees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/limitations-and-future-work.html">
 <span class="dropdown-text">Limitations and future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../WRITEUP/reproducibility.html">
 <span class="dropdown-text">Reproducibility — three reproduction tiers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../decisions/README.html"> 
<span class="menu-text">Decisions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reference">    
        <li>
    <a class="dropdown-item" href="../docs/for-hiring-managers.html">
 <span class="dropdown-text">For hiring managers in a hurry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../EXECUTIVE_SUMMARY.html">
 <span class="dropdown-text">Executive summary: prompt-injection classifier evaluation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../EVIDENCE.html">
 <span class="dropdown-text">Evidence — audit trail</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../SPEC_SHEET.html">
 <span class="dropdown-text">Project specification (filled at end of Phase 0)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../SUBMISSION_AUDIT.html">
 <span class="dropdown-text">Submission audit — claim status ledger</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../NEXT_STEPS.html">
 <span class="dropdown-text">Carryforward + future work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assumptions.html">
 <span class="dropdown-text">Assumptions registry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/01_canonical_results.html">
 <span class="dropdown-text">01 — Canonical results</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/02_frozen_vs_lora.html">
 <span class="dropdown-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/03_calibration.html">
 <span class="dropdown-text">03 — Calibration battery</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/04_ood_slate.html">
 <span class="dropdown-text">04 — OOD slate gap visualization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/brandon-behring/prompt-injection-detection-prototype" target="_blank"> 
<span class="menu-text">Repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../decisions/README.html">Decisions (ADRs)</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-001-submission-deadline-and-scope-ambition.html">Decisions</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Entry</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Landing page (results + meaning)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../RESULTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Results: tables, figures, and source artifacts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../EXECUTIVE_SUMMARY.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Executive summary: prompt-injection classifier evaluation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cover narrative (hub)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../READING_GUIDE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading guide</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Detailed spokes (8 topics)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/data-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/model-rungs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/eval-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/threshold-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threshold policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/reference-scorer-audit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/limitations-and-future-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Limitations and future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../WRITEUP/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility — three reproduction tiers</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/01_canonical_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 — Canonical results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/02_frozen_vs_lora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 — Frozen-probe vs LoRA paired-bootstrap rung-comparison</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/03_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 — Calibration battery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/04_ood_slate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 — OOD slate gap visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence + audit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../EVIDENCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evidence — audit trail</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../SPEC_SHEET.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project specification (filled at end of Phase 0)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../SUBMISSION_AUDIT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission audit — claim status ledger</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../NEXT_STEPS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carryforward + future work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assumptions registry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions (ADRs)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/README.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architecture Decision Records (ADRs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/upstream_issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Upstream issues filed during this iteration</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Decisions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-001-submission-deadline-and-scope-ambition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Submission deadline 2026-05-18 morning with infra-leveraged Long-scope attempt and fallback ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-002-deliverable-format-pdf-and-repo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — focused PDF plus public GitHub repo as evidence locker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-003-repo-visibility-public.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repository visibility — public from start (kit default ratified)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-004-reviewer-profile-and-hub-and-spoke-writeup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer profile A1+A2 with hub-and-spoke writeup structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-005-methodology-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-level methodology principles — methodology over metrics, honest evaluation preferred, structured limitations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-006-headline-metrics-and-statistical-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Headline metrics, operating-point pinpoints, and statistical apparatus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-007-rung-architecture-and-reference-scorers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology rung architecture — trained backbones, LLM-judge reference rungs, Cohen’s kappa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-008-data-scope-public-only-hybrid-splits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data scope — public-only sources, hybrid splits, NotInject inclusion (brief-level lock)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-009-process-mandates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Process mandates — two-tier reproducibility, marker-based testing, compute disclosure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-010-scope-limits-with-extension-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scope limits with per-bound extension conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-011-methodology-guarantees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology guarantees — eight banned approaches surfaced as project commitments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-012-soft-signals-and-artifact-engagement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Soft-signals naming discipline and external artifact engagement set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-013-kit-ratify-bulk-strictness-intake-notebook-persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kit-ratify bulk — Phase 0 strictness, brief-intake protocol, notebook role and RunPod persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-014-threat-model-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Threat-model bundle — attack-class scope, language, length cap, truncation policy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-015-rung-architecture-refinement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung architecture refinement — ModernBERT-base only trained slate, supersedes ADR-007</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-016-data-design-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data design bundle — source slate, splits, HF pinning, dedup, ordering, ceilings, ref-scorer audit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-017-trained-rung-slate-expansion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trained-rung-slate expansion — TF-IDF plus LR classical floor and frozen-probe dual role</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-018-reference-scorer-slate-and-contamination-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reference scorer slate and contamination stratification — OpenAI plus Anthropic LLM-judges plus ProtectAI v1 and v2 plus per-axis matched-budget</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-019-lora-and-transformer-training-recipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA and transformer-rung training recipe — hyperparameters, epochs, precision, class weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-020-compute-infrastructure-and-cost-discipline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compute infrastructure and cost discipline — runpod-deploy 0.7.7 primitives, GPU failover, adaptive batch sizing, dual-layer cost tracking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-021-eval-slate-aggregation-and-recall-fpr-pinpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eval slate aggregation — pooled headline plus per-slice spoke and recall@FPR pinpoint feasibility</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-022-statistical-inference-apparatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference apparatus — bootstrap N + stability check, multi-comparison stance, multi-seed protocol, paired-test method</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-023-calibration-battery-and-interventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery composition — raw plus temperature plus isotonic interventions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-024-cross-fold-ci-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-fold CI methodology — cv_clt_ci (Bayle 2020) headline plus block-bootstrap-on-folds spoke</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-025-dual-policy-threshold-characterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dual-policy threshold characterization at symmetric 1% cost weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-026-module-layout-concern-grouped-subpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module layout — concern-grouped sub-packages under src/</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-027-smoke-vs-canonical-execution-context-stratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Smoke vs canonical separation — three Makefile targets stratified by execution context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-028-coverage-floor-70pct-with-upstream-issue-filing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test coverage floor — 70% flat with co-locked upstream-issue-filing discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-029-test-marker-strategy-four-marker-ratification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Test marker strategy — ratify 4-marker stratification (unit / smoke / integration / network)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-030-deliverable-format-quarto-html-site.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverable format — repo-only with Quarto-rendered HTML site via GitHub Actions (supersedes ADR-002)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-031-reviewer-reading-paths-quarto-site-entry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reviewer reading paths — index.qmd entry-point with Quarto sidebar nav (supersedes ADR-004)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-032-hf-hub-publication-headline-rungs-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HF Hub checkpoint publication — publish primary headline rungs only with model card discipline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-033-github-release-strategy-rehearsal-plus-submission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitHub release strategy — rehearsal tag plus SemVer submission tag plus post-submission patches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-034-reproducibility-tier-full-ladder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducibility tier — full ladder T0 (eval-from-hub) plus T1 (smoke) plus T3 (headline-cloud)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-035-secrets-management-three-store-split.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secrets management — three-store split aligned with execution context (.env + RunPod pod-secrets + GH Actions repo Secrets)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-036-library-version-pins-tag-pin-plus-freeze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library version pins — tag pin to latest stable plus freeze for submission window (eval-toolkit v0.31.0 + runpod-deploy v0.7.7 + research_toolkit v1.9.1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-037-python-version-pin-3-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python version pin — ratify requires-python &gt;=3.13 (matches existing .python-version + bc8ce4e commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-038-phase-tailoring-light-roadmap-edits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase tailoring — light ROADMAP edits to Phase 4 close + Phase 5 description (preserves 5-phase structure)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-039-acceptance-criteria-six-gate-integration-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project-specific acceptance criteria — 6-gate integration checklist for v1.0.0 submission tag</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-040-phase-0-audit-findings-and-assumption-backfill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 0 final audit findings + 7-assumption backfill (A-010 through A-016)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-041-phase-1-data-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 (Data) implementation bundle — manifest schema, SHA pinning, validator placement, loader arch, holdout sourcing, contamination corpus, output materialization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-042-llm-prelabel-dedup-holdout-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-judge pre-label as Q5 holdout-labeling bootstrap with human override</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-043-post-split-cross-source-leakage-cleanup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-split cross-source leakage cleanup — drop train+val rows that exact-match or cosine-near-match test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-044-phase-2-training-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 training implementation bundle — seed slate reconciliation + manifest move + classical-floor location + YAML config schema + trainer split + per-rung orchestration + fixture preflight</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-045-phase-3-evaluation-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 evaluation implementation bundle — scoring-first contract + 6-commit cadence + tiered reference scorers + classical-scaffold + full-pairwise persistence with headline-only WRITEUP + pydantic schema validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-046-phase-4-analysis-implementation-bundle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 analysis implementation bundle — 6-commit cadence + scaffold-with-classical + always-emit-both-CIs auto-flag + MDE-on-every-emitted-CI + LLM-rater audit included (user-overridden from defer) + library-first hybrid figures + Phase 5 prep deferred</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-047-phase-1-library-first-carryforward-refactor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 library-first carryforward refactor — audit findings + remediation plan (splits + dedup + leakage_report + contamination_scan migration to eval-toolkit primitives; orphaned code removed in-commit)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-048-llm-rater-reference-scorer-audit-protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM-rater reference-scorer audit protocol — disagreement-with-LoRA baseline + stratified (5 OOD slices × 3 contamination_states) sampling + fixed 2-axis rubric + inter-rater gpt-4o-plus-claude-sonnet + dry-run-then-single-approval cost UX</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-049-gpu-order-priority-refresh-a100-80g.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPU failover ladder priority refresh — A100-SXM4-80GB to position 1 + US-WA-1/US-CA-2 datacenter additions + EU-RO-1 drop (frozen-probe + LoRA canonical; full-FT deferred to post-rehearsal)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-050-rung-slate-narrowing-llm-judges-and-full-ft-ood-dropped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rung slate narrowing — LLM judges dropped (cost) + full-FT OOD dropped (FUSE EIO crash); narrow supersession of ADR-018 reference slate + ADR-021 OOD comparison scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-051-v1.0.x-carryforward-of-t0-and-invariant-scaffolds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">v1.0.x carryforward of ADR-034 T0 score-match wiring + ADR-039 gate-3 invariant-scaffold unskip; narrow supersession with explicit v1.1.x landing condition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-052-full-ft-ood-drop-methodological-reframing-of-adr-050-r2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full-FT OOD inference drop — methodological reframing; narrow supersession of ADR-050 Revision 2 (FUSE-crash-only framing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-053-reading-guide-governance-and-newcomer-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading-guide governance + newcomer onboarding paths — two entry artifacts + 3 reading paths + Headline-finding-block + interpretation pedagogy + pointer convention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-054-results-page-as-third-entry-artifact-extending-adr-053.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RESULTS.md as third entry artifact — narrow supersession of ADR-053 dimension 1 (two-entry-artifacts); dimensions 2-5 unchanged</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-055-eval-toolkit-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">eval-toolkit installs from PyPI (not git+https) at v0.40.0+ — narrow supersession of ADR-036 “git URL is the only viable spec format”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-056-binary-calibrator-refactor-and-platt-beta-narrow-supersession-of-adr-023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration battery refactor to eval-toolkit <code>_binary</code> API + Platt + Beta calibrators landed — narrow supersession of ADR-023 “temperature + isotonic only” scope deferral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-057-manifest-schema-v3-backfill-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Per-prediction provenance manifests via scripts/backfill_provenance.py — schema, location, naming, idempotency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-058-eval-from-hub-non-dry-run-body-narrow-supersession-of-adr-051-block-a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">scripts/eval_from_hub.py non-dry-run body wired — narrow supersession of ADR-051 Block A (T0 score-match carryforward); Block B (38 invariant scaffolds) remains carryforward</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-059-runpod-deploy-pypi-install-narrow-supersession-of-adr-036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">runpod-deploy installs from PyPI (not git+https) at v0.8.4+ — narrow supersession of ADR-036 “git URL is the only viable spec format” sub-claim for runpod-deploy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-060-deberta-v3-base-long-context-ablation-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation methodology — chunk-and-average vs head-truncation × 5-slice OOD; infrastructure-only at v1.1.0; execution deferred to v1.1.1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-061-quarto-site-navigation-restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto site navigation restructure — landing-page rebuild + navbar consolidation + sidebar hub-spoke nesting (narrow supersession of ADR-053 navigation contract)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-062-quarto-writeup-clarity-and-canonical-figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto writeup clarity rewrite and canonical reviewer figure slate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-063-deberta-ablation-v1-1-2-execution-and-slot-shift.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DeBERTa-v3-base medium ablation execution (v1.1.2 carryforward; narrow renaming-only supersession of ADR-060 “v1.1.1” body references) — null result, backbone-dominant interpretation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-064-writeup-hiring-manager-clarity-and-consistency-pass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup hiring-manager clarity polish + documentation-wide consistency conventions — additive layer on top of ADR-062</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writeup accuracy-audit methodology + Quarto callout-note convention + narrative invariants — additive layer on top of ADR-064</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-066-library-first-carryforward-refactor-v1-2-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Library-first carryforward refactor v1.2.2 — consume 7 closed eval-toolkit primitives across 6 sites</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for factual-typo fixes in cross-reference slug filenames</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-069-immutability-narrow-relaxation-for-publisher-url-to-doi-canonicalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for academic publisher-URL → DOI canonicalization in immutable ADRs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decisions/ADR-070-quarto-render-only-markdown-corrections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Narrow immutability relaxation for render-only Markdown corrections in immutable ADRs</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#adr-068-narrow-immutability-relaxation-for-broken-external-references-in-immutable-adrs" id="toc-adr-068-narrow-immutability-relaxation-for-broken-external-references-in-immutable-adrs" class="nav-link active" data-scroll-target="#adr-068-narrow-immutability-relaxation-for-broken-external-references-in-immutable-adrs">ADR-068 — Narrow immutability relaxation for broken external references in immutable ADRs</a>
  <ul class="collapse">
  <li><a href="#status" id="toc-status" class="nav-link" data-scroll-target="#status">Status</a></li>
  <li><a href="#a-context-discovery-from-the-first-end-to-end-lychee-scan" id="toc-a-context-discovery-from-the-first-end-to-end-lychee-scan" class="nav-link" data-scroll-target="#a-context-discovery-from-the-first-end-to-end-lychee-scan">§A Context — discovery from the first end-to-end lychee scan</a></li>
  <li><a href="#b-decision-narrow-extension-covering-two-additional-classes" id="toc-b-decision-narrow-extension-covering-two-additional-classes" class="nav-link" data-scroll-target="#b-decision-narrow-extension-covering-two-additional-classes">§B Decision — narrow extension covering two additional classes</a>
  <ul class="collapse">
  <li><a href="#b1-in-scope-corrections-allowed-in-place-per-this-adr-068" id="toc-b1-in-scope-corrections-allowed-in-place-per-this-adr-068" class="nav-link" data-scroll-target="#b1-in-scope-corrections-allowed-in-place-per-this-adr-068">B1 — In-scope corrections (allowed in-place per this ADR-068)</a></li>
  <li><a href="#b2-out-of-scope-changes-require-superseding-adr-per-existing-rule" id="toc-b2-out-of-scope-changes-require-superseding-adr-per-existing-rule" class="nav-link" data-scroll-target="#b2-out-of-scope-changes-require-superseding-adr-per-existing-rule">B2 — Out-of-scope changes (REQUIRE superseding ADR per existing rule)</a></li>
  <li><a href="#b3-commit-message-convention" id="toc-b3-commit-message-convention" class="nav-link" data-scroll-target="#b3-commit-message-convention">B3 — Commit message convention</a></li>
  <li><a href="#b4-future-pr-review-discipline-unchanged-from-adr-067" id="toc-b4-future-pr-review-discipline-unchanged-from-adr-067" class="nav-link" data-scroll-target="#b4-future-pr-review-discipline-unchanged-from-adr-067">B4 — Future PR review discipline (unchanged from ADR-067)</a></li>
  </ul></li>
  <li><a href="#c-decision-apply-in-the-v1.2.6-fix-forward-consolidated-inventory" id="toc-c-decision-apply-in-the-v1.2.6-fix-forward-consolidated-inventory" class="nav-link" data-scroll-target="#c-decision-apply-in-the-v1.2.6-fix-forward-consolidated-inventory">§C Decision — apply in the v1.2.6 fix-forward (consolidated inventory)</a>
  <ul class="collapse">
  <li><a href="#c1-immutable-adr-markdown-links-covered-by-adr-068-3-fixes" id="toc-c1-immutable-adr-markdown-links-covered-by-adr-068-3-fixes" class="nav-link" data-scroll-target="#c1-immutable-adr-markdown-links-covered-by-adr-068-3-fixes">C1 — Immutable-ADR markdown links covered by ADR-068 (3 fixes)</a></li>
  <li><a href="#c2-mutable-files-not-covered-by-adr-068-fixed-separately-in-the-v1.2.6-fix-forward" id="toc-c2-mutable-files-not-covered-by-adr-068-fixed-separately-in-the-v1.2.6-fix-forward" class="nav-link" data-scroll-target="#c2-mutable-files-not-covered-by-adr-068-fixed-separately-in-the-v1.2.6-fix-forward">C2 — Mutable files (NOT covered by ADR-068; fixed separately in the v1.2.6 fix-forward)</a></li>
  </ul></li>
  <li><a href="#d-decision-claude.md-decisionsreadme.md-updates" id="toc-d-decision-claude.md-decisionsreadme.md-updates" class="nav-link" data-scroll-target="#d-decision-claude.md-decisionsreadme.md-updates">§D Decision — CLAUDE.md + decisions/README.md updates</a></li>
  <li><a href="#e-consequences" id="toc-e-consequences" class="nav-link" data-scroll-target="#e-consequences">§E Consequences</a>
  <ul class="collapse">
  <li><a href="#e1-reader-experience-improved-immutable-adr-class" id="toc-e1-reader-experience-improved-immutable-adr-class" class="nav-link" data-scroll-target="#e1-reader-experience-improved-immutable-adr-class">E1 — Reader experience improved (immutable-ADR class)</a></li>
  <li><a href="#e2-audit-trail-discipline-preserved" id="toc-e2-audit-trail-discipline-preserved" class="nav-link" data-scroll-target="#e2-audit-trail-discipline-preserved">E2 — Audit-trail discipline preserved</a></li>
  <li><a href="#e3-documentation-debt-paid-down-v1.1.4-v1.2.6-trail" id="toc-e3-documentation-debt-paid-down-v1.1.4-v1.2.6-trail" class="nav-link" data-scroll-target="#e3-documentation-debt-paid-down-v1.1.4-v1.2.6-trail">E3 — Documentation debt paid down (v1.1.4 → v1.2.6 trail)</a></li>
  <li><a href="#e4-two-adr-symmetry" id="toc-e4-two-adr-symmetry" class="nav-link" data-scroll-target="#e4-two-adr-symmetry">E4 — Two-ADR symmetry</a></li>
  <li><a href="#e5-future-prs-flagged-on-out-of-scope-edits" id="toc-e5-future-prs-flagged-on-out-of-scope-edits" class="nav-link" data-scroll-target="#e5-future-prs-flagged-on-out-of-scope-edits">E5 — Future PRs flagged on out-of-scope edits</a></li>
  <li><a href="#e6-cost-trivial" id="toc-e6-cost-trivial" class="nav-link" data-scroll-target="#e6-cost-trivial">E6 — Cost-trivial</a></li>
  </ul></li>
  <li><a href="#linked-adrs" id="toc-linked-adrs" class="nav-link" data-scroll-target="#linked-adrs">Linked ADRs</a></li>
  <li><a href="#transcript" id="toc-transcript" class="nav-link" data-scroll-target="#transcript">Transcript</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../decisions/README.html">Decisions (ADRs)</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-001-submission-deadline-and-scope-ambition.html">Decisions</a></li><li class="breadcrumb-item"><a href="../decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="adr-068-narrow-immutability-relaxation-for-broken-external-references-in-immutable-adrs" class="level1">
<h1>ADR-068 — Narrow immutability relaxation for broken external references in immutable ADRs</h1>
<section id="status" class="level2">
<h2 class="anchored" data-anchor-id="status">Status</h2>
<p>Accepted (2026-05-19; second narrow clarification of the existing CLAUDE.md immutability rule — co-equal with ADR-067; covers a different class of factual defects).</p>
</section>
<section id="a-context-discovery-from-the-first-end-to-end-lychee-scan" class="level2">
<h2 class="anchored" data-anchor-id="a-context-discovery-from-the-first-end-to-end-lychee-scan">§A Context — discovery from the first end-to-end lychee scan</h2>
<p>The lychee link-check CI workflow was introduced at v1.1.4 (<code>d3f63d8</code>) but was non-functional from inception until v1.2.4 due to a chain of v0.23.0 compatibility issues (<code>--exclude-mail</code> removed; <code>--base .</code> rejected). The v1.2.3 patch fixed <code>--exclude-mail</code>; the v1.2.4 patch fixed <code>--base</code>. Only on the v1.2.4 push (<code>3c44032</code>) did lychee execute end-to-end for the first time, surfacing 35 unique broken markdown links across 35+ files that had been masked for 5 patches.</p>
<p>Root-cause analysis (v1.2.5 /exploring-options walk, 2026-05-19) classified the failures into 7 patterns. Two of them — <strong>A.1 local-filesystem path leakage</strong> and <strong>A.2 aspirational upstream references</strong> — appear inside immutable ADRs (<code>decisions/ADR-NNN-&lt;slug&gt;.md</code> files) and are therefore protected by the CLAUDE.md immutability rule from in-place editing.</p>
<p>ADR-067 (v1.2.2) established a precedent narrow exception for factual typos in cross-reference slug filenames. The two newly-surfaced classes share the same audit rationale that motivated ADR-067:</p>
<ol type="1">
<li><strong>No decision content is affected.</strong> A local-filesystem path is a citation/reference, not a methodology decision. An aspirational upstream link is a forward-reference to planned docs, not a methodology decision.</li>
<li><strong>CI cannot resolve them.</strong> <code>file:///home/&lt;author&gt;/...</code> and <code>../../../.claude/...</code> paths require the author’s own filesystem; they never resolve on any CI runner OR reviewer browser. Aspirational <code>eval-toolkit/blob/main/docs/methodology/*.md</code> URLs return 404 because those docs were planned but never created upstream.</li>
<li><strong>Reader experience strictly improves with in-place fix.</strong> A reader clicking the broken link sees a 404. Replacing with descriptive prose preserves the citation intent + eliminates the 404.</li>
<li><strong>Audit trail is preserved.</strong> The broken-link CONTENT is removed but the surrounding prose + the decision that referenced it remains immutable. Future <code>git log decisions/ADR-NNN.md</code> shows the original commit + the v1.2.6 broken-ref-fix commit; both are recoverable.</li>
</ol>
<p>Both classes meet the §B-style narrow-scope test that ADR-067 applies to its own exception.</p>
</section>
<section id="b-decision-narrow-extension-covering-two-additional-classes" class="level2">
<h2 class="anchored" data-anchor-id="b-decision-narrow-extension-covering-two-additional-classes">§B Decision — narrow extension covering two additional classes</h2>
<p>ADRs remain immutable for decision content (per CLAUDE.md + ADR-067 §B). ADR-067 covers the <strong>factual-typo-in-cross-reference-slug</strong> class. ADR-068 covers two additional narrow classes:</p>
<section id="b1-in-scope-corrections-allowed-in-place-per-this-adr-068" class="level3">
<h3 class="anchored" data-anchor-id="b1-in-scope-corrections-allowed-in-place-per-this-adr-068">B1 — In-scope corrections (allowed in-place per this ADR-068)</h3>
<p><strong>Class X — Local-filesystem path references.</strong> Markdown links (and YAML frontmatter URL strings) where the URL targets a path on the author’s local filesystem:</p>
<ul>
<li><code>file:///home/&lt;author&gt;/...</code></li>
<li><code>/home/&lt;author&gt;/.../&lt;anything&gt;.md</code></li>
<li><code>../../../.claude/projects/.../memory/&lt;anything&gt;.md</code></li>
<li>Any path resolving to a directory NOT present in the repo (verifiable via <code>[ -e &lt;path&gt; ]</code> check at CI runner).</li>
</ul>
<p>Fix discipline: replace the broken link with descriptive prose that preserves the citation intent. Example transformation: - Before: <code>[memory/library_first_is_project_wide_invariant.md](../../../.claude/projects/.../memory/library_first_is_project_wide_invariant.md)</code> - After: <code>`memory/library_first_is_project_wide_invariant.md` (project-local Claude memory; not committed)</code></p>
<p>The reader sees the SAME citation text (which is informative on its own — they know what concept is being referenced) without the broken-link target.</p>
<p><strong>Class Y — Aspirational upstream references.</strong> Markdown links pointing at upstream resources that do NOT exist on the upstream repo:</p>
<ul>
<li><code>https://github.com/&lt;owner&gt;/&lt;repo&gt;/blob/&lt;branch&gt;/&lt;path&gt;</code> where the path returns 404 from the upstream repo’s API.</li>
<li>Includes the 9 references to <code>github.com/brandon-behring/eval-toolkit/blob/main/docs/methodology/{bootstrap,calibration,comparison,leakage,reproducibility,splits,text_dedup,thresholds}.md</code> — verified non-existent via <code>gh api repos/brandon-behring/eval-toolkit/contents/docs/methodology</code> returns 404.</li>
</ul>
<p>Fix discipline: replace the broken link with either (a) a descriptive prose statement citing the actual upstream primitive (e.g., <code>eval_toolkit.bootstrap_ci</code> from the <a href="https://github.com/brandon-behring/eval-toolkit#readme">eval-toolkit README</a>) OR (b) the closest existing upstream URL (e.g., the repo’s top-level README or the relevant source file). Preserves citation intent without retaining the broken link target.</p>
</section>
<section id="b2-out-of-scope-changes-require-superseding-adr-per-existing-rule" class="level3">
<h3 class="anchored" data-anchor-id="b2-out-of-scope-changes-require-superseding-adr-per-existing-rule">B2 — Out-of-scope changes (REQUIRE superseding ADR per existing rule)</h3>
<p>Same as ADR-067 §B2; numeric values, methodology decisions, prose rationale, alternatives considered, non-slug frontmatter fields, and table content all remain immutable. ADR-068 covers ONLY the link-target text in broken external references; the surrounding sentence + paragraph + decision content stays as written.</p>
<p>Important: <strong>ADR-068 applies ONLY to IMMUTABLE ADRs</strong>. Mutable files (SPEC_SHEET.md, SPEC_GREENFIELD.md, WRITEUP/*.md, decisions/library_imports.md, CHANGELOG.md, NEXT_STEPS.md, README.md, etc.) can be edited freely per their existing mutability convention and do NOT need ADR-068 cover.</p>
</section>
<section id="b3-commit-message-convention" class="level3">
<h3 class="anchored" data-anchor-id="b3-commit-message-convention">B3 — Commit message convention</h3>
<p>In-place broken-external-reference fixes in immutable ADRs carry a commit message of the form:</p>
<pre><code>docs: ADR-NNN broken-external-reference fixes per ADR-068

Per ADR-068 narrow-relaxation rule (Class X / Class Y): broken external
references to local-filesystem paths or aspirational upstream resources
MAY be corrected in-place in immutable ADRs. This commit fixes:

- decisions/ADR-XXX.md:LINE — Class X local-fs path `&lt;path&gt;` → descriptive prose `&lt;replacement&gt;`
- decisions/ADR-YYY.md:LINE — Class Y aspirational upstream `&lt;url&gt;` → descriptive prose `&lt;replacement&gt;`
  ...

No decision content changed. ADR audit trail preserved.</code></pre>
</section>
<section id="b4-future-pr-review-discipline-unchanged-from-adr-067" class="level3">
<h3 class="anchored" data-anchor-id="b4-future-pr-review-discipline-unchanged-from-adr-067">B4 — Future PR review discipline (unchanged from ADR-067)</h3>
<p>In-place ADR edits that go beyond the narrow scopes (ADR-067 slug typos + ADR-068 broken external refs) should be flagged by PR review + require a new superseding ADR per the existing rule. ADR-068 does NOT establish a slippery slope; it codifies a specific narrow class adjacent to ADR-067.</p>
</section>
</section>
<section id="c-decision-apply-in-the-v1.2.6-fix-forward-consolidated-inventory" class="level2">
<h2 class="anchored" data-anchor-id="c-decision-apply-in-the-v1.2.6-fix-forward-consolidated-inventory">§C Decision — apply in the v1.2.6 fix-forward (consolidated inventory)</h2>
<section id="c1-immutable-adr-markdown-links-covered-by-adr-068-3-fixes" class="level3">
<h3 class="anchored" data-anchor-id="c1-immutable-adr-markdown-links-covered-by-adr-068-3-fixes">C1 — Immutable-ADR markdown links covered by ADR-068 (3 fixes)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>File:line</th>
<th>Class</th>
<th>Broken link</th>
<th>Replacement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.md:108</code></td>
<td>X</td>
<td><code>[memory/adr-029-immutability-misattribution-historical-drift.md](../../../.claude/projects/.../memory/adr-029-immutability-misattribution-historical-drift.md)</code></td>
<td><code>`memory/adr-029-immutability-misattribution-historical-drift.md` (project-local Claude memory; not committed)</code></td>
</tr>
<tr class="even">
<td><code>decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.md:122</code></td>
<td>X</td>
<td><code>[memory/library_first_is_project_wide_invariant.md](../../../.claude/projects/.../memory/library_first_is_project_wide_invariant.md)</code></td>
<td><code>`memory/library_first_is_project_wide_invariant.md` (project-local Claude memory; not committed)</code></td>
</tr>
<tr class="odd">
<td><code>decisions/ADR-025-dual-policy-threshold-characterization.md:13</code> (YAML frontmatter <code>references:</code> list-item)</td>
<td>Y</td>
<td><code>https://github.com/brandon-behring/eval-toolkit/blob/main/docs/methodology/thresholds.md</code></td>
<td>Replace with <code>eval_toolkit.thresholds</code> (the actual upstream primitive surface), OR closest-existing upstream URL: <code>https://github.com/brandon-behring/eval-toolkit#readme</code>. Choose the README pointer for ADR-025 line 13 since it’s the references-list field.</td>
</tr>
</tbody>
</table>
</section>
<section id="c2-mutable-files-not-covered-by-adr-068-fixed-separately-in-the-v1.2.6-fix-forward" class="level3">
<h3 class="anchored" data-anchor-id="c2-mutable-files-not-covered-by-adr-068-fixed-separately-in-the-v1.2.6-fix-forward">C2 — Mutable files (NOT covered by ADR-068; fixed separately in the v1.2.6 fix-forward)</h3>
<p>For completeness — mutable files have similar fixes applied without ADR-068 coverage:</p>
<ul>
<li><code>SPEC_SHEET.md</code> lines 313, 314, 316, 335: 4 aspirational eval-toolkit/methodology refs</li>
<li><code>SPEC_GREENFIELD.md</code> lines 82, 98, 111, 167, 172, 174, 203: 7 aspirational refs</li>
<li><code>WRITEUP/data-decisions.md</code> lines 96, 126, 134: 3 aspirational refs</li>
<li><code>WRITEUP/threshold-policy.md</code> line 56: 1 aspirational ref</li>
<li><code>decisions/library_imports.md</code> line 182: 1 local-fs path ref</li>
</ul>
<p>These edits don’t need ADR-068 cover; the mutability convention covers them.</p>
</section>
</section>
<section id="d-decision-claude.md-decisionsreadme.md-updates" class="level2">
<h2 class="anchored" data-anchor-id="d-decision-claude.md-decisionsreadme.md-updates">§D Decision — CLAUDE.md + decisions/README.md updates</h2>
<p>Both documents get the dual-narrow-exception update (cites both ADR-067 + ADR-068):</p>
<p><strong>CLAUDE.md §“Phase 0 workflow”</strong> (after the existing immutability line; replacing the prior ADR-067-only narrow-exception clause):</p>
<blockquote class="blockquote">
<p>The ADR is the source of truth. ADRs are immutable; supersede via new ADR marking prior <code>status: superseded-by-NNN</code>.</p>
<p><strong>Narrow exceptions</strong> (per <a href="../decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html">ADR-067</a> + <a href="../decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.html">ADR-068</a>): TWO factual-defect classes MAY be corrected in-place with a commit message citing the relevant ADR + listing per-file corrections:</p>
<ol type="1">
<li><strong>Cross-reference slug filename typos</strong> (per ADR-067) — a slug pointing at a wrong-but-existing file in <code>decisions/</code>.</li>
<li><strong>Broken external references</strong> (per ADR-068) — markdown links pointing at local-filesystem paths or aspirational upstream resources that do not exist.</li>
</ol>
<p>ALL other content (numeric values, methodology, prose, alternatives, non-slug frontmatter, table data) remains immutable per the existing rule.</p>
</blockquote>
<p><strong><code>decisions/README.md</code> §Lifecycle</strong> (similar dual-citation update).</p>
</section>
<section id="e-consequences" class="level2">
<h2 class="anchored" data-anchor-id="e-consequences">§E Consequences</h2>
<section id="e1-reader-experience-improved-immutable-adr-class" class="level3">
<h3 class="anchored" data-anchor-id="e1-reader-experience-improved-immutable-adr-class">E1 — Reader experience improved (immutable-ADR class)</h3>
<p>After the v1.2.6 fix-forward, readers reading ADR-025 / ADR-065 see descriptive prose where they previously saw broken markdown links. No more 404s on CI runners. No more misleading citation targets for non-author readers.</p>
</section>
<section id="e2-audit-trail-discipline-preserved" class="level3">
<h3 class="anchored" data-anchor-id="e2-audit-trail-discipline-preserved">E2 — Audit-trail discipline preserved</h3>
<p>The 3 immutable-ADR fixes do NOT change decision content; ADR audit trail remains intact. Per-file <code>git log</code> shows the original commit + the v1.2.6 broken-ref-fix commit; both are recoverable. The narrow scope (§B2 out-of-scope) prevents slippery-slope drift to decision-content edits.</p>
</section>
<section id="e3-documentation-debt-paid-down-v1.1.4-v1.2.6-trail" class="level3">
<h3 class="anchored" data-anchor-id="e3-documentation-debt-paid-down-v1.1.4-v1.2.6-trail">E3 — Documentation debt paid down (v1.1.4 → v1.2.6 trail)</h3>
<p>The lychee link-check CI was introduced at v1.1.4 as an “URL rot defense” but was non-functional from inception. v1.2.3 + v1.2.4 fixed the workflow’s v0.23.0 compat issues; v1.2.6 closes the surfaced content debt (35 unique broken URLs across 7 root-cause classes). The lychee CI now runs end-to-end + actually catches link rot going forward.</p>
</section>
<section id="e4-two-adr-symmetry" class="level3">
<h3 class="anchored" data-anchor-id="e4-two-adr-symmetry">E4 — Two-ADR symmetry</h3>
<p>ADR-067 and ADR-068 are co-equal narrow exceptions to the same CLAUDE.md immutability rule: - ADR-067: slug typos in cross-references (wrong-but-existing target) - ADR-068: broken external refs (target doesn’t exist anywhere)</p>
<p>Both follow the same §B-discipline: in-scope corrections + out-of-scope changes + commit-message-convention + future-PR-review-discipline.</p>
</section>
<section id="e5-future-prs-flagged-on-out-of-scope-edits" class="level3">
<h3 class="anchored" data-anchor-id="e5-future-prs-flagged-on-out-of-scope-edits">E5 — Future PRs flagged on out-of-scope edits</h3>
<p>If a future patch attempts to edit decision content in-place under the guise of ADR-067 or ADR-068, PR review should flag the diff + require a superseding ADR. The narrow-relaxation rules are NOT slippery slopes; they codify specific, well-defined factual-defect classes.</p>
</section>
<section id="e6-cost-trivial" class="level3">
<h3 class="anchored" data-anchor-id="e6-cost-trivial">E6 — Cost-trivial</h3>
<p>$0. CPU-only edits across 3 immutable-ADR lines (ADR-025 line 13 + ADR-065 lines 108, 122) + the CLAUDE.md / decisions/README.md / GLOSSARY clarification updates.</p>
</section>
</section>
<section id="linked-adrs" class="level2">
<h2 class="anchored" data-anchor-id="linked-adrs">Linked ADRs</h2>
<ul>
<li><strong>References</strong>:
<ul>
<li>CLAUDE.md — the source-of-truth for immutability (clarified by ADR-067 + ADR-068 dual-narrow-exception)</li>
<li>decisions/README.md — the ADR lifecycle + frontmatter schema (also gets the dual-citation update)</li>
<li><a href="../decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.html">ADR-067</a> — precedent narrow relaxation for slug typos; ADR-068 extends with two additional classes</li>
</ul></li>
<li><strong>Source</strong>: v1.2.6 link-check fix-forward; root-cause analysis began during the v1.2.5 /exploring-options 4-question walk (2026-05-19), where the user picked “Extend ADR-067 narrow relaxation → ADR-068 + in-place fix (Recommended)” on Question 1 + “Full structural fix — ADR-068 + DOI canon + triage (Recommended)” on Question 4.</li>
</ul>
</section>
<section id="transcript" class="level2">
<h2 class="anchored" data-anchor-id="transcript">Transcript</h2>
<p><code>transcripts/2026-05-19__v1-2-5-link-check-content-debt-and-immutability-extension.md</code> — captures the multi-class link-check content debt close + the ADR-068 narrow relaxation extension.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">adr_id:</span><span class="co"> "068"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">slug:</span><span class="co"> immutability-narrow-relaxation-for-broken-external-references</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> Narrow immutability relaxation for broken external references in immutable ADRs (local-filesystem paths + aspirational upstream refs)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-05-19</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="an">status:</span><span class="co"> Accepted</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="an">claim_id:</span><span class="co"> CLAIM-068</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="an">claim:</span><span class="co"> &gt;-</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">  ADR-067 established a narrow exception to the CLAUDE.md ADR-immutability</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">  rule for factual typos in cross-reference slug filenames (wrong-but-still-</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">  existing slug pointing at a wrong file in `decisions/`). The lychee CI</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">  introduced at v1.1.4 was non-functional from inception until v1.2.4</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">  (caught by the v1.2.3 patch + the additional v0.23.0 `--base` incompat</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">  fixed at v1.2.4); the FIRST end-to-end lychee scan at v1.2.4 surfaced</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">  TWO additional classes of broken markdown links inside immutable ADRs</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">  that are NOT covered by ADR-067's narrow exception but which exhibit</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">  the same audit-rationale (no decision content affected; CI can never</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">  resolve them; reader experience strictly improved by in-place fix):</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co">  (a) **local-filesystem path references** — markdown links pointing at</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">  paths under `/home/&lt;author&gt;/...` or `../../../.claude/...` (author's</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">  own machine's filesystem leaking into committed text) — cannot resolve</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co">  on any non-author machine, including CI runners and reviewer browsers;</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co">  (b) **aspirational upstream references** — markdown links pointing at</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co">  upstream resources (eval-toolkit/blob/main/docs/methodology/*.md) that</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co">  do NOT exist upstream (author's mental model of planned-but-never-</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co">  created upstream docs). ADR-068 extends the narrow-relaxation rule</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co">  to cover both classes with the SAME §B2-style out-of-scope-list</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co">  discipline (numeric values + methodology + prose + alternatives +</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co">  non-slug frontmatter remain immutable). v1.2.6 applies the rule to</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co">  fix 2 immutable-ADR markdown links (ADR-065 lines 108 + 122) plus</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co">  the YAML frontmatter list-item in ADR-025 line 13. Mutable files</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="co">  (SPEC_SHEET.md + SPEC_GREENFIELD.md + WRITEUP/*.md + decisions/</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="co">  library_imports.md + CHANGELOG.md) are fixed in a separate commit</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co">  without ADR-068 coverage (the rule applies ONLY to immutable ADRs).</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="an">source:</span><span class="co"> v1.2.6 link-check fix-forward (root-cause analysis began during the v1.2.5 /exploring-options 4-question walk on 2026-05-19) — user picked all 4 recommended options including "Extend ADR-067 narrow relaxation → ADR-068 + in-place fix" + "Full structural fix — ADR-068 + DOI canon + triage"</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="an">acceptance_criterion:</span><span class="co"> &gt;-</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="co">  At v1.2.6 close: `decisions/ADR-068-immutability-narrow-relaxation-for-broken-external-references.md`</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a><span class="co">  exists (this file). `CLAUDE.md` §"Phase 0 workflow" immutability-rule</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="co">  block updated to cite both ADR-067 + ADR-068 as the two narrow exceptions.</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="co">  `decisions/README.md` §Lifecycle updated with the same dual-citation.</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="co">  `docs/GLOSSARY.md` entry for "Immutability relaxation" updated to list</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a><span class="co">  both classes. All 2 immutable-ADR markdown links flagged by lychee CI</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co">  (ADR-065 lines 108 + 122) are replaced with descriptive prose preserving</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="co">  citation intent without retaining the broken link target. ADR-025 line 13</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="co">  (YAML frontmatter `references:` list-item pointing at non-existent</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="co">  eval-toolkit/blob/main/docs/methodology/thresholds.md) is replaced with a</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="co">  descriptive marker or the closest existing upstream URL. Lychee CI on</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="co">  the v1.2.6 push reports the affected immutable-ADR errors RESOLVED.</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="co">  Future PR reviews flag any in-place ADR edit that goes beyond the</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="co">  enumerated narrow scope (numeric values + methodology + prose + non-slug</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="co">  frontmatter + decision content remain immutable per the existing rule).</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a><span class="an">closing_commit:</span><span class="co"> v1.2.6</span></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="an">supersedes:</span><span class="co"> []</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="an">superseded_by:</span><span class="co"> []</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="an">references:</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a><span class="co">  - CLAUDE.md  # immutability rule lives here; gets dual-narrow-exception update</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a><span class="co">  - decisions/README.md  # ADR lifecycle; gets dual-narrow-exception update</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a><span class="co">  - decisions/ADR-067-immutability-clarification-and-canonical-slug-reference.md  # precedent narrow relaxation</span></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="co">  - docs/GLOSSARY.md</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a><span class="an">transcript:</span><span class="co"> transcripts/2026-05-19__v1-2-5-link-check-content-debt-and-immutability-extension.md</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="fu"># ADR-068 — Narrow immutability relaxation for broken external references in immutable ADRs</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## Status</span></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>Accepted (2026-05-19; second narrow clarification of the existing CLAUDE.md immutability rule — co-equal with ADR-067; covers a different class of factual defects).</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## §A Context — discovery from the first end-to-end lychee scan</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>The lychee link-check CI workflow was introduced at v1.1.4 (<span class="in">`d3f63d8`</span>) but was non-functional from inception until v1.2.4 due to a chain of v0.23.0 compatibility issues (<span class="in">`--exclude-mail`</span> removed; <span class="in">`--base .`</span> rejected). The v1.2.3 patch fixed <span class="in">`--exclude-mail`</span>; the v1.2.4 patch fixed <span class="in">`--base`</span>. Only on the v1.2.4 push (<span class="in">`3c44032`</span>) did lychee execute end-to-end for the first time, surfacing 35 unique broken markdown links across 35+ files that had been masked for 5 patches.</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>Root-cause analysis (v1.2.5 /exploring-options walk, 2026-05-19) classified the failures into 7 patterns. Two of them — **A.1 local-filesystem path leakage** and **A.2 aspirational upstream references** — appear inside immutable ADRs (<span class="in">`decisions/ADR-NNN-&lt;slug&gt;.md`</span> files) and are therefore protected by the CLAUDE.md immutability rule from in-place editing.</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>ADR-067 (v1.2.2) established a precedent narrow exception for factual typos in cross-reference slug filenames. The two newly-surfaced classes share the same audit rationale that motivated ADR-067:</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**No decision content is affected.** A local-filesystem path is a citation/reference, not a methodology decision. An aspirational upstream link is a forward-reference to planned docs, not a methodology decision.</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**CI cannot resolve them.** <span class="in">`file:///home/&lt;author&gt;/...`</span> and <span class="in">`../../../.claude/...`</span> paths require the author's own filesystem; they never resolve on any CI runner OR reviewer browser. Aspirational <span class="in">`eval-toolkit/blob/main/docs/methodology/*.md`</span> URLs return 404 because those docs were planned but never created upstream.</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Reader experience strictly improves with in-place fix.** A reader clicking the broken link sees a 404. Replacing with descriptive prose preserves the citation intent + eliminates the 404.</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Audit trail is preserved.** The broken-link CONTENT is removed but the surrounding prose + the decision that referenced it remains immutable. Future <span class="in">`git log decisions/ADR-NNN.md`</span> shows the original commit + the v1.2.6 broken-ref-fix commit; both are recoverable.</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>Both classes meet the §B-style narrow-scope test that ADR-067 applies to its own exception.</span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## §B Decision — narrow extension covering two additional classes</span></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>ADRs remain immutable for decision content (per CLAUDE.md + ADR-067 §B). ADR-067 covers the **factual-typo-in-cross-reference-slug** class. ADR-068 covers two additional narrow classes:</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a><span class="fu">### B1 — In-scope corrections (allowed in-place per this ADR-068)</span></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>**Class X — Local-filesystem path references.** Markdown links (and YAML frontmatter URL strings) where the URL targets a path on the author's local filesystem:</span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`file:///home/&lt;author&gt;/...`</span></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`/home/&lt;author&gt;/.../&lt;anything&gt;.md`</span></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`../../../.claude/projects/.../memory/&lt;anything&gt;.md`</span></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Any path resolving to a directory NOT present in the repo (verifiable via <span class="in">`[ -e &lt;path&gt; ]`</span> check at CI runner).</span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a>Fix discipline: replace the broken link with descriptive prose that preserves the citation intent. Example transformation:</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Before: <span class="in">`[memory/library_first_is_project_wide_invariant.md](../../../.claude/projects/.../memory/library_first_is_project_wide_invariant.md)`</span></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>After: `<span class="in">` `</span>memory/library_first_is_project_wide_invariant.md` (project-local Claude memory; not committed) ``</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a>The reader sees the SAME citation text (which is informative on its own — they know what concept is being referenced) without the broken-link target.</span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>**Class Y — Aspirational upstream references.** Markdown links pointing at upstream resources that do NOT exist on the upstream repo:</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`https://github.com/&lt;owner&gt;/&lt;repo&gt;/blob/&lt;branch&gt;/&lt;path&gt;`</span> where the path returns 404 from the upstream repo's API.</span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Includes the 9 references to <span class="in">`github.com/brandon-behring/eval-toolkit/blob/main/docs/methodology/{bootstrap,calibration,comparison,leakage,reproducibility,splits,text_dedup,thresholds}.md`</span> — verified non-existent via <span class="in">`gh api repos/brandon-behring/eval-toolkit/contents/docs/methodology`</span> returns 404.</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a>Fix discipline: replace the broken link with either (a) a descriptive prose statement citing the actual upstream primitive (e.g., <span class="in">`eval_toolkit.bootstrap_ci`</span> from the <span class="co">[</span><span class="ot">eval-toolkit README</span><span class="co">](https://github.com/brandon-behring/eval-toolkit#readme)</span>) OR (b) the closest existing upstream URL (e.g., the repo's top-level README or the relevant source file). Preserves citation intent without retaining the broken link target.</span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a><span class="fu">### B2 — Out-of-scope changes (REQUIRE superseding ADR per existing rule)</span></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a>Same as ADR-067 §B2; numeric values, methodology decisions, prose rationale, alternatives considered, non-slug frontmatter fields, and table content all remain immutable. ADR-068 covers ONLY the link-target text in broken external references; the surrounding sentence + paragraph + decision content stays as written.</span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a>Important: **ADR-068 applies ONLY to IMMUTABLE ADRs**. Mutable files (SPEC_SHEET.md, SPEC_GREENFIELD.md, WRITEUP/*.md, decisions/library_imports.md, CHANGELOG.md, NEXT_STEPS.md, README.md, etc.) can be edited freely per their existing mutability convention and do NOT need ADR-068 cover.</span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a><span class="fu">### B3 — Commit message convention</span></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a>In-place broken-external-reference fixes in immutable ADRs carry a commit message of the form:</span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="in">docs: ADR-NNN broken-external-reference fixes per ADR-068</span></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a><span class="in">Per ADR-068 narrow-relaxation rule (Class X / Class Y): broken external</span></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a><span class="in">references to local-filesystem paths or aspirational upstream resources</span></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="in">MAY be corrected in-place in immutable ADRs. This commit fixes:</span></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a><span class="in">- decisions/ADR-XXX.md:LINE — Class X local-fs path `&lt;path&gt;` → descriptive prose `&lt;replacement&gt;`</span></span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a><span class="in">- decisions/ADR-YYY.md:LINE — Class Y aspirational upstream `&lt;url&gt;` → descriptive prose `&lt;replacement&gt;`</span></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a><span class="in">  ...</span></span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a><span class="in">No decision content changed. ADR audit trail preserved.</span></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a><span class="fu">### B4 — Future PR review discipline (unchanged from ADR-067)</span></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a>In-place ADR edits that go beyond the narrow scopes (ADR-067 slug typos + ADR-068 broken external refs) should be flagged by PR review + require a new superseding ADR per the existing rule. ADR-068 does NOT establish a slippery slope; it codifies a specific narrow class adjacent to ADR-067.</span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a><span class="fu">## §C Decision — apply in the v1.2.6 fix-forward (consolidated inventory)</span></span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a><span class="fu">### C1 — Immutable-ADR markdown links covered by ADR-068 (3 fixes)</span></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> File:line <span class="pp">|</span> Class <span class="pp">|</span> Broken link <span class="pp">|</span> Replacement <span class="pp">|</span></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.md:108`</span> <span class="pp">|</span> X <span class="pp">|</span> <span class="in">`[memory/adr-029-immutability-misattribution-historical-drift.md](../../../.claude/projects/.../memory/adr-029-immutability-misattribution-historical-drift.md)`</span> <span class="pp">|</span> `<span class="in">` `</span>memory/adr-029-immutability-misattribution-historical-drift.md` (project-local Claude memory; not committed) `` <span class="pp">|</span></span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`decisions/ADR-065-writeup-accuracy-narrative-and-callout-conventions.md:122`</span> <span class="pp">|</span> X <span class="pp">|</span> <span class="in">`[memory/library_first_is_project_wide_invariant.md](../../../.claude/projects/.../memory/library_first_is_project_wide_invariant.md)`</span> <span class="pp">|</span> `<span class="in">` `</span>memory/library_first_is_project_wide_invariant.md` (project-local Claude memory; not committed) `` <span class="pp">|</span></span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`decisions/ADR-025-dual-policy-threshold-characterization.md:13`</span> (YAML frontmatter <span class="in">`references:`</span> list-item) <span class="pp">|</span> Y <span class="pp">|</span> <span class="in">`https://github.com/brandon-behring/eval-toolkit/blob/main/docs/methodology/thresholds.md`</span> <span class="pp">|</span> Replace with <span class="in">`eval_toolkit.thresholds`</span> (the actual upstream primitive surface), OR closest-existing upstream URL: <span class="in">`https://github.com/brandon-behring/eval-toolkit#readme`</span>. Choose the README pointer for ADR-025 line 13 since it's the references-list field. <span class="pp">|</span></span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### C2 — Mutable files (NOT covered by ADR-068; fixed separately in the v1.2.6 fix-forward)</span></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a>For completeness — mutable files have similar fixes applied without ADR-068 coverage:</span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`SPEC_SHEET.md`</span> lines 313, 314, 316, 335: 4 aspirational eval-toolkit/methodology refs</span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`SPEC_GREENFIELD.md`</span> lines 82, 98, 111, 167, 172, 174, 203: 7 aspirational refs</span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`WRITEUP/data-decisions.md`</span> lines 96, 126, 134: 3 aspirational refs</span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`WRITEUP/threshold-policy.md`</span> line 56: 1 aspirational ref</span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`decisions/library_imports.md`</span> line 182: 1 local-fs path ref</span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a>These edits don't need ADR-068 cover; the mutability convention covers them.</span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a><span class="fu">## §D Decision — CLAUDE.md + decisions/README.md updates</span></span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a>Both documents get the dual-narrow-exception update (cites both ADR-067 + ADR-068):</span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a>**CLAUDE.md §"Phase 0 workflow"** (after the existing immutability line; replacing the prior ADR-067-only narrow-exception clause):</span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The ADR is the source of truth. ADRs are immutable; supersede via new ADR marking prior </span><span class="in">`status: superseded-by-NNN`</span><span class="at">.</span></span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Narrow exceptions** (per </span><span class="co">[</span><span class="ot">ADR-067</span><span class="co">](./ADR-067-immutability-clarification-and-canonical-slug-reference.md)</span><span class="at"> + </span><span class="co">[</span><span class="ot">ADR-068</span><span class="co">](./ADR-068-immutability-narrow-relaxation-for-broken-external-references.md)</span><span class="at">): TWO factual-defect classes MAY be corrected in-place with a commit message citing the relevant ADR + listing per-file corrections:</span></span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 1. **Cross-reference slug filename typos** (per ADR-067) — a slug pointing at a wrong-but-existing file in </span><span class="in">`decisions/`</span><span class="at">.</span></span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; 2. **Broken external references** (per ADR-068) — markdown links pointing at local-filesystem paths or aspirational upstream resources that do not exist.</span></span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; ALL other content (numeric values, methodology, prose, alternatives, non-slug frontmatter, table data) remains immutable per the existing rule.</span></span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a>**`decisions/README.md` §Lifecycle** (similar dual-citation update).</span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a><span class="fu">## §E Consequences</span></span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a><span class="fu">### E1 — Reader experience improved (immutable-ADR class)</span></span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a>After the v1.2.6 fix-forward, readers reading ADR-025 / ADR-065 see descriptive prose where they previously saw broken markdown links. No more 404s on CI runners. No more misleading citation targets for non-author readers.</span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a><span class="fu">### E2 — Audit-trail discipline preserved</span></span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a>The 3 immutable-ADR fixes do NOT change decision content; ADR audit trail remains intact. Per-file <span class="in">`git log`</span> shows the original commit + the v1.2.6 broken-ref-fix commit; both are recoverable. The narrow scope (§B2 out-of-scope) prevents slippery-slope drift to decision-content edits.</span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a><span class="fu">### E3 — Documentation debt paid down (v1.1.4 → v1.2.6 trail)</span></span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a>The lychee link-check CI was introduced at v1.1.4 as an "URL rot defense" but was non-functional from inception. v1.2.3 + v1.2.4 fixed the workflow's v0.23.0 compat issues; v1.2.6 closes the surfaced content debt (35 unique broken URLs across 7 root-cause classes). The lychee CI now runs end-to-end + actually catches link rot going forward.</span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a><span class="fu">### E4 — Two-ADR symmetry</span></span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a>ADR-067 and ADR-068 are co-equal narrow exceptions to the same CLAUDE.md immutability rule:</span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ADR-067: slug typos in cross-references (wrong-but-existing target)</span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ADR-068: broken external refs (target doesn't exist anywhere)</span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-197"><a href="#cb2-197" aria-hidden="true" tabindex="-1"></a>Both follow the same §B-discipline: in-scope corrections + out-of-scope changes + commit-message-convention + future-PR-review-discipline.</span>
<span id="cb2-198"><a href="#cb2-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-199"><a href="#cb2-199" aria-hidden="true" tabindex="-1"></a><span class="fu">### E5 — Future PRs flagged on out-of-scope edits</span></span>
<span id="cb2-200"><a href="#cb2-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-201"><a href="#cb2-201" aria-hidden="true" tabindex="-1"></a>If a future patch attempts to edit decision content in-place under the guise of ADR-067 or ADR-068, PR review should flag the diff + require a superseding ADR. The narrow-relaxation rules are NOT slippery slopes; they codify specific, well-defined factual-defect classes.</span>
<span id="cb2-202"><a href="#cb2-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-203"><a href="#cb2-203" aria-hidden="true" tabindex="-1"></a><span class="fu">### E6 — Cost-trivial</span></span>
<span id="cb2-204"><a href="#cb2-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-205"><a href="#cb2-205" aria-hidden="true" tabindex="-1"></a>$0. CPU-only edits across 3 immutable-ADR lines (ADR-025 line 13 + ADR-065 lines 108, 122) + the CLAUDE.md / decisions/README.md / GLOSSARY clarification updates.</span>
<span id="cb2-206"><a href="#cb2-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-207"><a href="#cb2-207" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linked ADRs</span></span>
<span id="cb2-208"><a href="#cb2-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-209"><a href="#cb2-209" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**References**:</span>
<span id="cb2-210"><a href="#cb2-210" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>CLAUDE.md — the source-of-truth for immutability (clarified by ADR-067 + ADR-068 dual-narrow-exception)</span>
<span id="cb2-211"><a href="#cb2-211" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>decisions/README.md — the ADR lifecycle + frontmatter schema (also gets the dual-citation update)</span>
<span id="cb2-212"><a href="#cb2-212" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span><span class="co">[</span><span class="ot">ADR-067</span><span class="co">](./ADR-067-immutability-clarification-and-canonical-slug-reference.md)</span> — precedent narrow relaxation for slug typos; ADR-068 extends with two additional classes</span>
<span id="cb2-213"><a href="#cb2-213" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Source**: v1.2.6 link-check fix-forward; root-cause analysis began during the v1.2.5 /exploring-options 4-question walk (2026-05-19), where the user picked "Extend ADR-067 narrow relaxation → ADR-068 + in-place fix (Recommended)" on Question 1 + "Full structural fix — ADR-068 + DOI canon + triage (Recommended)" on Question 4.</span>
<span id="cb2-214"><a href="#cb2-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-215"><a href="#cb2-215" aria-hidden="true" tabindex="-1"></a><span class="fu">## Transcript</span></span>
<span id="cb2-216"><a href="#cb2-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-217"><a href="#cb2-217" aria-hidden="true" tabindex="-1"></a><span class="in">`transcripts/2026-05-19__v1-2-5-link-check-content-debt-and-immutability-extension.md`</span> — captures the multi-class link-check content debt close + the ADR-068 narrow relaxation extension.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>